package com.dhl.tools.mapper;

import com.dhl.tools.domain.AuthorityInfo;
import com.dhl.tools.domain.AuthorityInfoExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface AuthorityInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AuthorityInfo
     *
     * @mbg.generated
     */
    long countByExample(AuthorityInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AuthorityInfo
     *
     * @mbg.generated
     */
    int deleteByExample(AuthorityInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AuthorityInfo
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AuthorityInfo
     *
     * @mbg.generated
     */
    int insert(AuthorityInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AuthorityInfo
     *
     * @mbg.generated
     */
    int insertSelective(AuthorityInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AuthorityInfo
     *
     * @mbg.generated
     */
    List<AuthorityInfo> selectByExample(AuthorityInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AuthorityInfo
     *
     * @mbg.generated
     */
    AuthorityInfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AuthorityInfo
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") AuthorityInfo record, @Param("example") AuthorityInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AuthorityInfo
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") AuthorityInfo record, @Param("example") AuthorityInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AuthorityInfo
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(AuthorityInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AuthorityInfo
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(AuthorityInfo record);
}