package com.dhl.tools.mapper;

import com.dhl.tools.domain.MaterialCargoLocationTypeData;
import com.dhl.tools.domain.MaterialCargoLocationTypeDataExample;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import java.util.List;

@Mapper
public interface MaterialCargoLocationTypeDataMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Material_CargoLocationType_Data
     *
     * @mbg.generated
     */
    long countByExample(MaterialCargoLocationTypeDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Material_CargoLocationType_Data
     *
     * @mbg.generated
     */
    int deleteByExample(MaterialCargoLocationTypeDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Material_CargoLocationType_Data
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Material_CargoLocationType_Data
     *
     * @mbg.generated
     */
    int insert(MaterialCargoLocationTypeData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Material_CargoLocationType_Data
     *
     * @mbg.generated
     */
    int insertSelective(MaterialCargoLocationTypeData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Material_CargoLocationType_Data
     *
     * @mbg.generated
     */
    List<MaterialCargoLocationTypeData> selectByExample(MaterialCargoLocationTypeDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Material_CargoLocationType_Data
     *
     * @mbg.generated
     */
    MaterialCargoLocationTypeData selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Material_CargoLocationType_Data
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") MaterialCargoLocationTypeData record, @Param("example") MaterialCargoLocationTypeDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Material_CargoLocationType_Data
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") MaterialCargoLocationTypeData record, @Param("example") MaterialCargoLocationTypeDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Material_CargoLocationType_Data
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(MaterialCargoLocationTypeData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Material_CargoLocationType_Data
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(MaterialCargoLocationTypeData record);
}