package com.dhl.tools.mapper;

import com.dhl.tools.domain.UserInfoRoleInfo;
import com.dhl.tools.domain.UserInfoRoleInfoExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface UserInfoRoleInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UserInfo_RoleInfo
     *
     * @mbg.generated
     */
    long countByExample(UserInfoRoleInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UserInfo_RoleInfo
     *
     * @mbg.generated
     */
    int deleteByExample(UserInfoRoleInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UserInfo_RoleInfo
     *
     * @mbg.generated
     */
    int insert(UserInfoRoleInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UserInfo_RoleInfo
     *
     * @mbg.generated
     */
    int insertSelective(UserInfoRoleInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UserInfo_RoleInfo
     *
     * @mbg.generated
     */
    List<UserInfoRoleInfo> selectByExample(UserInfoRoleInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UserInfo_RoleInfo
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") UserInfoRoleInfo record, @Param("example") UserInfoRoleInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UserInfo_RoleInfo
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") UserInfoRoleInfo record, @Param("example") UserInfoRoleInfoExample example);
}