package com.dhl.tools.mapper;

import com.dhl.tools.domain.WareHouseType;
import com.dhl.tools.domain.WareHouseTypeExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface WareHouseTypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WareHouseType
     *
     * @mbg.generated
     */
    long countByExample(WareHouseTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WareHouseType
     *
     * @mbg.generated
     */
    int deleteByExample(WareHouseTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WareHouseType
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WareHouseType
     *
     * @mbg.generated
     */
    int insert(WareHouseType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WareHouseType
     *
     * @mbg.generated
     */
    int insertSelective(WareHouseType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WareHouseType
     *
     * @mbg.generated
     */
    List<WareHouseType> selectByExample(WareHouseTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WareHouseType
     *
     * @mbg.generated
     */
    WareHouseType selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WareHouseType
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") WareHouseType record, @Param("example") WareHouseTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WareHouseType
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") WareHouseType record, @Param("example") WareHouseTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WareHouseType
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(WareHouseType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WareHouseType
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(WareHouseType record);
}