package com.dhl.tools.mapper;

import com.dhl.tools.domain.WareHouse;
import com.dhl.tools.domain.WareHouseExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface WareHouseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WareHouse
     *
     * @mbg.generated
     */
    long countByExample(WareHouseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WareHouse
     *
     * @mbg.generated
     */
    int deleteByExample(WareHouseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WareHouse
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WareHouse
     *
     * @mbg.generated
     */
    int insert(WareHouse record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WareHouse
     *
     * @mbg.generated
     */
    int insertSelective(WareHouse record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WareHouse
     *
     * @mbg.generated
     */
    List<WareHouse> selectByExample(WareHouseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WareHouse
     *
     * @mbg.generated
     */
    WareHouse selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WareHouse
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") WareHouse record, @Param("example") WareHouseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WareHouse
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") WareHouse record, @Param("example") WareHouseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WareHouse
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(WareHouse record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WareHouse
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(WareHouse record);
}