package com.dhl.tools.domain;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class CargoLocationTypeExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table CargoLocationType
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table CargoLocationType
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table CargoLocationType
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CargoLocationType
     *
     * @mbg.generated
     */
    public CargoLocationTypeExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CargoLocationType
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CargoLocationType
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CargoLocationType
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CargoLocationType
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CargoLocationType
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CargoLocationType
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CargoLocationType
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CargoLocationType
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CargoLocationType
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CargoLocationType
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table CargoLocationType
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andCodeIsNull() {
            addCriterion("code is null");
            return (Criteria) this;
        }

        public Criteria andCodeIsNotNull() {
            addCriterion("code is not null");
            return (Criteria) this;
        }

        public Criteria andCodeEqualTo(String value) {
            addCriterion("code =", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeNotEqualTo(String value) {
            addCriterion("code <>", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeGreaterThan(String value) {
            addCriterion("code >", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeGreaterThanOrEqualTo(String value) {
            addCriterion("code >=", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeLessThan(String value) {
            addCriterion("code <", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeLessThanOrEqualTo(String value) {
            addCriterion("code <=", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeLike(String value) {
            addCriterion("code like", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeNotLike(String value) {
            addCriterion("code not like", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeIn(List<String> values) {
            addCriterion("code in", values, "code");
            return (Criteria) this;
        }

        public Criteria andCodeNotIn(List<String> values) {
            addCriterion("code not in", values, "code");
            return (Criteria) this;
        }

        public Criteria andCodeBetween(String value1, String value2) {
            addCriterion("code between", value1, value2, "code");
            return (Criteria) this;
        }

        public Criteria andCodeNotBetween(String value1, String value2) {
            addCriterion("code not between", value1, value2, "code");
            return (Criteria) this;
        }

        public Criteria andLengthIsNull() {
            addCriterion("length is null");
            return (Criteria) this;
        }

        public Criteria andLengthIsNotNull() {
            addCriterion("length is not null");
            return (Criteria) this;
        }

        public Criteria andLengthEqualTo(Double value) {
            addCriterion("length =", value, "length");
            return (Criteria) this;
        }

        public Criteria andLengthNotEqualTo(Double value) {
            addCriterion("length <>", value, "length");
            return (Criteria) this;
        }

        public Criteria andLengthGreaterThan(Double value) {
            addCriterion("length >", value, "length");
            return (Criteria) this;
        }

        public Criteria andLengthGreaterThanOrEqualTo(Double value) {
            addCriterion("length >=", value, "length");
            return (Criteria) this;
        }

        public Criteria andLengthLessThan(Double value) {
            addCriterion("length <", value, "length");
            return (Criteria) this;
        }

        public Criteria andLengthLessThanOrEqualTo(Double value) {
            addCriterion("length <=", value, "length");
            return (Criteria) this;
        }

        public Criteria andLengthIn(List<Double> values) {
            addCriterion("length in", values, "length");
            return (Criteria) this;
        }

        public Criteria andLengthNotIn(List<Double> values) {
            addCriterion("length not in", values, "length");
            return (Criteria) this;
        }

        public Criteria andLengthBetween(Double value1, Double value2) {
            addCriterion("length between", value1, value2, "length");
            return (Criteria) this;
        }

        public Criteria andLengthNotBetween(Double value1, Double value2) {
            addCriterion("length not between", value1, value2, "length");
            return (Criteria) this;
        }

        public Criteria andWidthIsNull() {
            addCriterion("width is null");
            return (Criteria) this;
        }

        public Criteria andWidthIsNotNull() {
            addCriterion("width is not null");
            return (Criteria) this;
        }

        public Criteria andWidthEqualTo(Double value) {
            addCriterion("width =", value, "width");
            return (Criteria) this;
        }

        public Criteria andWidthNotEqualTo(Double value) {
            addCriterion("width <>", value, "width");
            return (Criteria) this;
        }

        public Criteria andWidthGreaterThan(Double value) {
            addCriterion("width >", value, "width");
            return (Criteria) this;
        }

        public Criteria andWidthGreaterThanOrEqualTo(Double value) {
            addCriterion("width >=", value, "width");
            return (Criteria) this;
        }

        public Criteria andWidthLessThan(Double value) {
            addCriterion("width <", value, "width");
            return (Criteria) this;
        }

        public Criteria andWidthLessThanOrEqualTo(Double value) {
            addCriterion("width <=", value, "width");
            return (Criteria) this;
        }

        public Criteria andWidthIn(List<Double> values) {
            addCriterion("width in", values, "width");
            return (Criteria) this;
        }

        public Criteria andWidthNotIn(List<Double> values) {
            addCriterion("width not in", values, "width");
            return (Criteria) this;
        }

        public Criteria andWidthBetween(Double value1, Double value2) {
            addCriterion("width between", value1, value2, "width");
            return (Criteria) this;
        }

        public Criteria andWidthNotBetween(Double value1, Double value2) {
            addCriterion("width not between", value1, value2, "width");
            return (Criteria) this;
        }

        public Criteria andHeightIsNull() {
            addCriterion("height is null");
            return (Criteria) this;
        }

        public Criteria andHeightIsNotNull() {
            addCriterion("height is not null");
            return (Criteria) this;
        }

        public Criteria andHeightEqualTo(Double value) {
            addCriterion("height =", value, "height");
            return (Criteria) this;
        }

        public Criteria andHeightNotEqualTo(Double value) {
            addCriterion("height <>", value, "height");
            return (Criteria) this;
        }

        public Criteria andHeightGreaterThan(Double value) {
            addCriterion("height >", value, "height");
            return (Criteria) this;
        }

        public Criteria andHeightGreaterThanOrEqualTo(Double value) {
            addCriterion("height >=", value, "height");
            return (Criteria) this;
        }

        public Criteria andHeightLessThan(Double value) {
            addCriterion("height <", value, "height");
            return (Criteria) this;
        }

        public Criteria andHeightLessThanOrEqualTo(Double value) {
            addCriterion("height <=", value, "height");
            return (Criteria) this;
        }

        public Criteria andHeightIn(List<Double> values) {
            addCriterion("height in", values, "height");
            return (Criteria) this;
        }

        public Criteria andHeightNotIn(List<Double> values) {
            addCriterion("height not in", values, "height");
            return (Criteria) this;
        }

        public Criteria andHeightBetween(Double value1, Double value2) {
            addCriterion("height between", value1, value2, "height");
            return (Criteria) this;
        }

        public Criteria andHeightNotBetween(Double value1, Double value2) {
            addCriterion("height not between", value1, value2, "height");
            return (Criteria) this;
        }

        public Criteria andExtendIsNull() {
            addCriterion("extend is null");
            return (Criteria) this;
        }

        public Criteria andExtendIsNotNull() {
            addCriterion("extend is not null");
            return (Criteria) this;
        }

        public Criteria andExtendEqualTo(Boolean value) {
            addCriterion("extend =", value, "extend");
            return (Criteria) this;
        }

        public Criteria andExtendNotEqualTo(Boolean value) {
            addCriterion("extend <>", value, "extend");
            return (Criteria) this;
        }

        public Criteria andExtendGreaterThan(Boolean value) {
            addCriterion("extend >", value, "extend");
            return (Criteria) this;
        }

        public Criteria andExtendGreaterThanOrEqualTo(Boolean value) {
            addCriterion("extend >=", value, "extend");
            return (Criteria) this;
        }

        public Criteria andExtendLessThan(Boolean value) {
            addCriterion("extend <", value, "extend");
            return (Criteria) this;
        }

        public Criteria andExtendLessThanOrEqualTo(Boolean value) {
            addCriterion("extend <=", value, "extend");
            return (Criteria) this;
        }

        public Criteria andExtendIn(List<Boolean> values) {
            addCriterion("extend in", values, "extend");
            return (Criteria) this;
        }

        public Criteria andExtendNotIn(List<Boolean> values) {
            addCriterion("extend not in", values, "extend");
            return (Criteria) this;
        }

        public Criteria andExtendBetween(Boolean value1, Boolean value2) {
            addCriterion("extend between", value1, value2, "extend");
            return (Criteria) this;
        }

        public Criteria andExtendNotBetween(Boolean value1, Boolean value2) {
            addCriterion("extend not between", value1, value2, "extend");
            return (Criteria) this;
        }

        public Criteria andIncreaseLengthIsNull() {
            addCriterion("increaseLength is null");
            return (Criteria) this;
        }

        public Criteria andIncreaseLengthIsNotNull() {
            addCriterion("increaseLength is not null");
            return (Criteria) this;
        }

        public Criteria andIncreaseLengthEqualTo(Double value) {
            addCriterion("increaseLength =", value, "increaseLength");
            return (Criteria) this;
        }

        public Criteria andIncreaseLengthNotEqualTo(Double value) {
            addCriterion("increaseLength <>", value, "increaseLength");
            return (Criteria) this;
        }

        public Criteria andIncreaseLengthGreaterThan(Double value) {
            addCriterion("increaseLength >", value, "increaseLength");
            return (Criteria) this;
        }

        public Criteria andIncreaseLengthGreaterThanOrEqualTo(Double value) {
            addCriterion("increaseLength >=", value, "increaseLength");
            return (Criteria) this;
        }

        public Criteria andIncreaseLengthLessThan(Double value) {
            addCriterion("increaseLength <", value, "increaseLength");
            return (Criteria) this;
        }

        public Criteria andIncreaseLengthLessThanOrEqualTo(Double value) {
            addCriterion("increaseLength <=", value, "increaseLength");
            return (Criteria) this;
        }

        public Criteria andIncreaseLengthIn(List<Double> values) {
            addCriterion("increaseLength in", values, "increaseLength");
            return (Criteria) this;
        }

        public Criteria andIncreaseLengthNotIn(List<Double> values) {
            addCriterion("increaseLength not in", values, "increaseLength");
            return (Criteria) this;
        }

        public Criteria andIncreaseLengthBetween(Double value1, Double value2) {
            addCriterion("increaseLength between", value1, value2, "increaseLength");
            return (Criteria) this;
        }

        public Criteria andIncreaseLengthNotBetween(Double value1, Double value2) {
            addCriterion("increaseLength not between", value1, value2, "increaseLength");
            return (Criteria) this;
        }

        public Criteria andIncreaseWidthIsNull() {
            addCriterion("increaseWidth is null");
            return (Criteria) this;
        }

        public Criteria andIncreaseWidthIsNotNull() {
            addCriterion("increaseWidth is not null");
            return (Criteria) this;
        }

        public Criteria andIncreaseWidthEqualTo(Double value) {
            addCriterion("increaseWidth =", value, "increaseWidth");
            return (Criteria) this;
        }

        public Criteria andIncreaseWidthNotEqualTo(Double value) {
            addCriterion("increaseWidth <>", value, "increaseWidth");
            return (Criteria) this;
        }

        public Criteria andIncreaseWidthGreaterThan(Double value) {
            addCriterion("increaseWidth >", value, "increaseWidth");
            return (Criteria) this;
        }

        public Criteria andIncreaseWidthGreaterThanOrEqualTo(Double value) {
            addCriterion("increaseWidth >=", value, "increaseWidth");
            return (Criteria) this;
        }

        public Criteria andIncreaseWidthLessThan(Double value) {
            addCriterion("increaseWidth <", value, "increaseWidth");
            return (Criteria) this;
        }

        public Criteria andIncreaseWidthLessThanOrEqualTo(Double value) {
            addCriterion("increaseWidth <=", value, "increaseWidth");
            return (Criteria) this;
        }

        public Criteria andIncreaseWidthIn(List<Double> values) {
            addCriterion("increaseWidth in", values, "increaseWidth");
            return (Criteria) this;
        }

        public Criteria andIncreaseWidthNotIn(List<Double> values) {
            addCriterion("increaseWidth not in", values, "increaseWidth");
            return (Criteria) this;
        }

        public Criteria andIncreaseWidthBetween(Double value1, Double value2) {
            addCriterion("increaseWidth between", value1, value2, "increaseWidth");
            return (Criteria) this;
        }

        public Criteria andIncreaseWidthNotBetween(Double value1, Double value2) {
            addCriterion("increaseWidth not between", value1, value2, "increaseWidth");
            return (Criteria) this;
        }

        public Criteria andFrontIncreaseIsNull() {
            addCriterion("frontIncrease is null");
            return (Criteria) this;
        }

        public Criteria andFrontIncreaseIsNotNull() {
            addCriterion("frontIncrease is not null");
            return (Criteria) this;
        }

        public Criteria andFrontIncreaseEqualTo(Double value) {
            addCriterion("frontIncrease =", value, "frontIncrease");
            return (Criteria) this;
        }

        public Criteria andFrontIncreaseNotEqualTo(Double value) {
            addCriterion("frontIncrease <>", value, "frontIncrease");
            return (Criteria) this;
        }

        public Criteria andFrontIncreaseGreaterThan(Double value) {
            addCriterion("frontIncrease >", value, "frontIncrease");
            return (Criteria) this;
        }

        public Criteria andFrontIncreaseGreaterThanOrEqualTo(Double value) {
            addCriterion("frontIncrease >=", value, "frontIncrease");
            return (Criteria) this;
        }

        public Criteria andFrontIncreaseLessThan(Double value) {
            addCriterion("frontIncrease <", value, "frontIncrease");
            return (Criteria) this;
        }

        public Criteria andFrontIncreaseLessThanOrEqualTo(Double value) {
            addCriterion("frontIncrease <=", value, "frontIncrease");
            return (Criteria) this;
        }

        public Criteria andFrontIncreaseIn(List<Double> values) {
            addCriterion("frontIncrease in", values, "frontIncrease");
            return (Criteria) this;
        }

        public Criteria andFrontIncreaseNotIn(List<Double> values) {
            addCriterion("frontIncrease not in", values, "frontIncrease");
            return (Criteria) this;
        }

        public Criteria andFrontIncreaseBetween(Double value1, Double value2) {
            addCriterion("frontIncrease between", value1, value2, "frontIncrease");
            return (Criteria) this;
        }

        public Criteria andFrontIncreaseNotBetween(Double value1, Double value2) {
            addCriterion("frontIncrease not between", value1, value2, "frontIncrease");
            return (Criteria) this;
        }

        public Criteria andBackIncreaseIsNull() {
            addCriterion("backIncrease is null");
            return (Criteria) this;
        }

        public Criteria andBackIncreaseIsNotNull() {
            addCriterion("backIncrease is not null");
            return (Criteria) this;
        }

        public Criteria andBackIncreaseEqualTo(Double value) {
            addCriterion("backIncrease =", value, "backIncrease");
            return (Criteria) this;
        }

        public Criteria andBackIncreaseNotEqualTo(Double value) {
            addCriterion("backIncrease <>", value, "backIncrease");
            return (Criteria) this;
        }

        public Criteria andBackIncreaseGreaterThan(Double value) {
            addCriterion("backIncrease >", value, "backIncrease");
            return (Criteria) this;
        }

        public Criteria andBackIncreaseGreaterThanOrEqualTo(Double value) {
            addCriterion("backIncrease >=", value, "backIncrease");
            return (Criteria) this;
        }

        public Criteria andBackIncreaseLessThan(Double value) {
            addCriterion("backIncrease <", value, "backIncrease");
            return (Criteria) this;
        }

        public Criteria andBackIncreaseLessThanOrEqualTo(Double value) {
            addCriterion("backIncrease <=", value, "backIncrease");
            return (Criteria) this;
        }

        public Criteria andBackIncreaseIn(List<Double> values) {
            addCriterion("backIncrease in", values, "backIncrease");
            return (Criteria) this;
        }

        public Criteria andBackIncreaseNotIn(List<Double> values) {
            addCriterion("backIncrease not in", values, "backIncrease");
            return (Criteria) this;
        }

        public Criteria andBackIncreaseBetween(Double value1, Double value2) {
            addCriterion("backIncrease between", value1, value2, "backIncrease");
            return (Criteria) this;
        }

        public Criteria andBackIncreaseNotBetween(Double value1, Double value2) {
            addCriterion("backIncrease not between", value1, value2, "backIncrease");
            return (Criteria) this;
        }

        public Criteria andLeftIncreaseIsNull() {
            addCriterion("leftIncrease is null");
            return (Criteria) this;
        }

        public Criteria andLeftIncreaseIsNotNull() {
            addCriterion("leftIncrease is not null");
            return (Criteria) this;
        }

        public Criteria andLeftIncreaseEqualTo(Double value) {
            addCriterion("leftIncrease =", value, "leftIncrease");
            return (Criteria) this;
        }

        public Criteria andLeftIncreaseNotEqualTo(Double value) {
            addCriterion("leftIncrease <>", value, "leftIncrease");
            return (Criteria) this;
        }

        public Criteria andLeftIncreaseGreaterThan(Double value) {
            addCriterion("leftIncrease >", value, "leftIncrease");
            return (Criteria) this;
        }

        public Criteria andLeftIncreaseGreaterThanOrEqualTo(Double value) {
            addCriterion("leftIncrease >=", value, "leftIncrease");
            return (Criteria) this;
        }

        public Criteria andLeftIncreaseLessThan(Double value) {
            addCriterion("leftIncrease <", value, "leftIncrease");
            return (Criteria) this;
        }

        public Criteria andLeftIncreaseLessThanOrEqualTo(Double value) {
            addCriterion("leftIncrease <=", value, "leftIncrease");
            return (Criteria) this;
        }

        public Criteria andLeftIncreaseIn(List<Double> values) {
            addCriterion("leftIncrease in", values, "leftIncrease");
            return (Criteria) this;
        }

        public Criteria andLeftIncreaseNotIn(List<Double> values) {
            addCriterion("leftIncrease not in", values, "leftIncrease");
            return (Criteria) this;
        }

        public Criteria andLeftIncreaseBetween(Double value1, Double value2) {
            addCriterion("leftIncrease between", value1, value2, "leftIncrease");
            return (Criteria) this;
        }

        public Criteria andLeftIncreaseNotBetween(Double value1, Double value2) {
            addCriterion("leftIncrease not between", value1, value2, "leftIncrease");
            return (Criteria) this;
        }

        public Criteria andRightIncreaseIsNull() {
            addCriterion("rightIncrease is null");
            return (Criteria) this;
        }

        public Criteria andRightIncreaseIsNotNull() {
            addCriterion("rightIncrease is not null");
            return (Criteria) this;
        }

        public Criteria andRightIncreaseEqualTo(Double value) {
            addCriterion("rightIncrease =", value, "rightIncrease");
            return (Criteria) this;
        }

        public Criteria andRightIncreaseNotEqualTo(Double value) {
            addCriterion("rightIncrease <>", value, "rightIncrease");
            return (Criteria) this;
        }

        public Criteria andRightIncreaseGreaterThan(Double value) {
            addCriterion("rightIncrease >", value, "rightIncrease");
            return (Criteria) this;
        }

        public Criteria andRightIncreaseGreaterThanOrEqualTo(Double value) {
            addCriterion("rightIncrease >=", value, "rightIncrease");
            return (Criteria) this;
        }

        public Criteria andRightIncreaseLessThan(Double value) {
            addCriterion("rightIncrease <", value, "rightIncrease");
            return (Criteria) this;
        }

        public Criteria andRightIncreaseLessThanOrEqualTo(Double value) {
            addCriterion("rightIncrease <=", value, "rightIncrease");
            return (Criteria) this;
        }

        public Criteria andRightIncreaseIn(List<Double> values) {
            addCriterion("rightIncrease in", values, "rightIncrease");
            return (Criteria) this;
        }

        public Criteria andRightIncreaseNotIn(List<Double> values) {
            addCriterion("rightIncrease not in", values, "rightIncrease");
            return (Criteria) this;
        }

        public Criteria andRightIncreaseBetween(Double value1, Double value2) {
            addCriterion("rightIncrease between", value1, value2, "rightIncrease");
            return (Criteria) this;
        }

        public Criteria andRightIncreaseNotBetween(Double value1, Double value2) {
            addCriterion("rightIncrease not between", value1, value2, "rightIncrease");
            return (Criteria) this;
        }

        public Criteria andPalletIsNull() {
            addCriterion("pallet is null");
            return (Criteria) this;
        }

        public Criteria andPalletIsNotNull() {
            addCriterion("pallet is not null");
            return (Criteria) this;
        }

        public Criteria andPalletEqualTo(Boolean value) {
            addCriterion("pallet =", value, "pallet");
            return (Criteria) this;
        }

        public Criteria andPalletNotEqualTo(Boolean value) {
            addCriterion("pallet <>", value, "pallet");
            return (Criteria) this;
        }

        public Criteria andPalletGreaterThan(Boolean value) {
            addCriterion("pallet >", value, "pallet");
            return (Criteria) this;
        }

        public Criteria andPalletGreaterThanOrEqualTo(Boolean value) {
            addCriterion("pallet >=", value, "pallet");
            return (Criteria) this;
        }

        public Criteria andPalletLessThan(Boolean value) {
            addCriterion("pallet <", value, "pallet");
            return (Criteria) this;
        }

        public Criteria andPalletLessThanOrEqualTo(Boolean value) {
            addCriterion("pallet <=", value, "pallet");
            return (Criteria) this;
        }

        public Criteria andPalletIn(List<Boolean> values) {
            addCriterion("pallet in", values, "pallet");
            return (Criteria) this;
        }

        public Criteria andPalletNotIn(List<Boolean> values) {
            addCriterion("pallet not in", values, "pallet");
            return (Criteria) this;
        }

        public Criteria andPalletBetween(Boolean value1, Boolean value2) {
            addCriterion("pallet between", value1, value2, "pallet");
            return (Criteria) this;
        }

        public Criteria andPalletNotBetween(Boolean value1, Boolean value2) {
            addCriterion("pallet not between", value1, value2, "pallet");
            return (Criteria) this;
        }

        public Criteria andTotalIsNull() {
            addCriterion("total is null");
            return (Criteria) this;
        }

        public Criteria andTotalIsNotNull() {
            addCriterion("total is not null");
            return (Criteria) this;
        }

        public Criteria andTotalEqualTo(Integer value) {
            addCriterion("total =", value, "total");
            return (Criteria) this;
        }

        public Criteria andTotalNotEqualTo(Integer value) {
            addCriterion("total <>", value, "total");
            return (Criteria) this;
        }

        public Criteria andTotalGreaterThan(Integer value) {
            addCriterion("total >", value, "total");
            return (Criteria) this;
        }

        public Criteria andTotalGreaterThanOrEqualTo(Integer value) {
            addCriterion("total >=", value, "total");
            return (Criteria) this;
        }

        public Criteria andTotalLessThan(Integer value) {
            addCriterion("total <", value, "total");
            return (Criteria) this;
        }

        public Criteria andTotalLessThanOrEqualTo(Integer value) {
            addCriterion("total <=", value, "total");
            return (Criteria) this;
        }

        public Criteria andTotalIn(List<Integer> values) {
            addCriterion("total in", values, "total");
            return (Criteria) this;
        }

        public Criteria andTotalNotIn(List<Integer> values) {
            addCriterion("total not in", values, "total");
            return (Criteria) this;
        }

        public Criteria andTotalBetween(Integer value1, Integer value2) {
            addCriterion("total between", value1, value2, "total");
            return (Criteria) this;
        }

        public Criteria andTotalNotBetween(Integer value1, Integer value2) {
            addCriterion("total not between", value1, value2, "total");
            return (Criteria) this;
        }

        public Criteria andUseCountIsNull() {
            addCriterion("useCount is null");
            return (Criteria) this;
        }

        public Criteria andUseCountIsNotNull() {
            addCriterion("useCount is not null");
            return (Criteria) this;
        }

        public Criteria andUseCountEqualTo(Integer value) {
            addCriterion("useCount =", value, "useCount");
            return (Criteria) this;
        }

        public Criteria andUseCountNotEqualTo(Integer value) {
            addCriterion("useCount <>", value, "useCount");
            return (Criteria) this;
        }

        public Criteria andUseCountGreaterThan(Integer value) {
            addCriterion("useCount >", value, "useCount");
            return (Criteria) this;
        }

        public Criteria andUseCountGreaterThanOrEqualTo(Integer value) {
            addCriterion("useCount >=", value, "useCount");
            return (Criteria) this;
        }

        public Criteria andUseCountLessThan(Integer value) {
            addCriterion("useCount <", value, "useCount");
            return (Criteria) this;
        }

        public Criteria andUseCountLessThanOrEqualTo(Integer value) {
            addCriterion("useCount <=", value, "useCount");
            return (Criteria) this;
        }

        public Criteria andUseCountIn(List<Integer> values) {
            addCriterion("useCount in", values, "useCount");
            return (Criteria) this;
        }

        public Criteria andUseCountNotIn(List<Integer> values) {
            addCriterion("useCount not in", values, "useCount");
            return (Criteria) this;
        }

        public Criteria andUseCountBetween(Integer value1, Integer value2) {
            addCriterion("useCount between", value1, value2, "useCount");
            return (Criteria) this;
        }

        public Criteria andUseCountNotBetween(Integer value1, Integer value2) {
            addCriterion("useCount not between", value1, value2, "useCount");
            return (Criteria) this;
        }

        public Criteria andWareHouseIdIsNull() {
            addCriterion("wareHouseId is null");
            return (Criteria) this;
        }

        public Criteria andWareHouseIdIsNotNull() {
            addCriterion("wareHouseId is not null");
            return (Criteria) this;
        }

        public Criteria andWareHouseIdEqualTo(Integer value) {
            addCriterion("wareHouseId =", value, "wareHouseId");
            return (Criteria) this;
        }

        public Criteria andWareHouseIdNotEqualTo(Integer value) {
            addCriterion("wareHouseId <>", value, "wareHouseId");
            return (Criteria) this;
        }

        public Criteria andWareHouseIdGreaterThan(Integer value) {
            addCriterion("wareHouseId >", value, "wareHouseId");
            return (Criteria) this;
        }

        public Criteria andWareHouseIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("wareHouseId >=", value, "wareHouseId");
            return (Criteria) this;
        }

        public Criteria andWareHouseIdLessThan(Integer value) {
            addCriterion("wareHouseId <", value, "wareHouseId");
            return (Criteria) this;
        }

        public Criteria andWareHouseIdLessThanOrEqualTo(Integer value) {
            addCriterion("wareHouseId <=", value, "wareHouseId");
            return (Criteria) this;
        }

        public Criteria andWareHouseIdIn(List<Integer> values) {
            addCriterion("wareHouseId in", values, "wareHouseId");
            return (Criteria) this;
        }

        public Criteria andWareHouseIdNotIn(List<Integer> values) {
            addCriterion("wareHouseId not in", values, "wareHouseId");
            return (Criteria) this;
        }

        public Criteria andWareHouseIdBetween(Integer value1, Integer value2) {
            addCriterion("wareHouseId between", value1, value2, "wareHouseId");
            return (Criteria) this;
        }

        public Criteria andWareHouseIdNotBetween(Integer value1, Integer value2) {
            addCriterion("wareHouseId not between", value1, value2, "wareHouseId");
            return (Criteria) this;
        }

        public Criteria andCreateByIsNull() {
            addCriterion("createBy is null");
            return (Criteria) this;
        }

        public Criteria andCreateByIsNotNull() {
            addCriterion("createBy is not null");
            return (Criteria) this;
        }

        public Criteria andCreateByEqualTo(String value) {
            addCriterion("createBy =", value, "createBy");
            return (Criteria) this;
        }

        public Criteria andCreateByNotEqualTo(String value) {
            addCriterion("createBy <>", value, "createBy");
            return (Criteria) this;
        }

        public Criteria andCreateByGreaterThan(String value) {
            addCriterion("createBy >", value, "createBy");
            return (Criteria) this;
        }

        public Criteria andCreateByGreaterThanOrEqualTo(String value) {
            addCriterion("createBy >=", value, "createBy");
            return (Criteria) this;
        }

        public Criteria andCreateByLessThan(String value) {
            addCriterion("createBy <", value, "createBy");
            return (Criteria) this;
        }

        public Criteria andCreateByLessThanOrEqualTo(String value) {
            addCriterion("createBy <=", value, "createBy");
            return (Criteria) this;
        }

        public Criteria andCreateByLike(String value) {
            addCriterion("createBy like", value, "createBy");
            return (Criteria) this;
        }

        public Criteria andCreateByNotLike(String value) {
            addCriterion("createBy not like", value, "createBy");
            return (Criteria) this;
        }

        public Criteria andCreateByIn(List<String> values) {
            addCriterion("createBy in", values, "createBy");
            return (Criteria) this;
        }

        public Criteria andCreateByNotIn(List<String> values) {
            addCriterion("createBy not in", values, "createBy");
            return (Criteria) this;
        }

        public Criteria andCreateByBetween(String value1, String value2) {
            addCriterion("createBy between", value1, value2, "createBy");
            return (Criteria) this;
        }

        public Criteria andCreateByNotBetween(String value1, String value2) {
            addCriterion("createBy not between", value1, value2, "createBy");
            return (Criteria) this;
        }

        public Criteria andCreateDateIsNull() {
            addCriterion("createDate is null");
            return (Criteria) this;
        }

        public Criteria andCreateDateIsNotNull() {
            addCriterion("createDate is not null");
            return (Criteria) this;
        }

        public Criteria andCreateDateEqualTo(Date value) {
            addCriterion("createDate =", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateNotEqualTo(Date value) {
            addCriterion("createDate <>", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateGreaterThan(Date value) {
            addCriterion("createDate >", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateGreaterThanOrEqualTo(Date value) {
            addCriterion("createDate >=", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateLessThan(Date value) {
            addCriterion("createDate <", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateLessThanOrEqualTo(Date value) {
            addCriterion("createDate <=", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateIn(List<Date> values) {
            addCriterion("createDate in", values, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateNotIn(List<Date> values) {
            addCriterion("createDate not in", values, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateBetween(Date value1, Date value2) {
            addCriterion("createDate between", value1, value2, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateNotBetween(Date value1, Date value2) {
            addCriterion("createDate not between", value1, value2, "createDate");
            return (Criteria) this;
        }

        public Criteria andLastModifiedByIsNull() {
            addCriterion("lastModifiedBy is null");
            return (Criteria) this;
        }

        public Criteria andLastModifiedByIsNotNull() {
            addCriterion("lastModifiedBy is not null");
            return (Criteria) this;
        }

        public Criteria andLastModifiedByEqualTo(String value) {
            addCriterion("lastModifiedBy =", value, "lastModifiedBy");
            return (Criteria) this;
        }

        public Criteria andLastModifiedByNotEqualTo(String value) {
            addCriterion("lastModifiedBy <>", value, "lastModifiedBy");
            return (Criteria) this;
        }

        public Criteria andLastModifiedByGreaterThan(String value) {
            addCriterion("lastModifiedBy >", value, "lastModifiedBy");
            return (Criteria) this;
        }

        public Criteria andLastModifiedByGreaterThanOrEqualTo(String value) {
            addCriterion("lastModifiedBy >=", value, "lastModifiedBy");
            return (Criteria) this;
        }

        public Criteria andLastModifiedByLessThan(String value) {
            addCriterion("lastModifiedBy <", value, "lastModifiedBy");
            return (Criteria) this;
        }

        public Criteria andLastModifiedByLessThanOrEqualTo(String value) {
            addCriterion("lastModifiedBy <=", value, "lastModifiedBy");
            return (Criteria) this;
        }

        public Criteria andLastModifiedByLike(String value) {
            addCriterion("lastModifiedBy like", value, "lastModifiedBy");
            return (Criteria) this;
        }

        public Criteria andLastModifiedByNotLike(String value) {
            addCriterion("lastModifiedBy not like", value, "lastModifiedBy");
            return (Criteria) this;
        }

        public Criteria andLastModifiedByIn(List<String> values) {
            addCriterion("lastModifiedBy in", values, "lastModifiedBy");
            return (Criteria) this;
        }

        public Criteria andLastModifiedByNotIn(List<String> values) {
            addCriterion("lastModifiedBy not in", values, "lastModifiedBy");
            return (Criteria) this;
        }

        public Criteria andLastModifiedByBetween(String value1, String value2) {
            addCriterion("lastModifiedBy between", value1, value2, "lastModifiedBy");
            return (Criteria) this;
        }

        public Criteria andLastModifiedByNotBetween(String value1, String value2) {
            addCriterion("lastModifiedBy not between", value1, value2, "lastModifiedBy");
            return (Criteria) this;
        }

        public Criteria andLastModifiedDateIsNull() {
            addCriterion("lastModifiedDate is null");
            return (Criteria) this;
        }

        public Criteria andLastModifiedDateIsNotNull() {
            addCriterion("lastModifiedDate is not null");
            return (Criteria) this;
        }

        public Criteria andLastModifiedDateEqualTo(Date value) {
            addCriterion("lastModifiedDate =", value, "lastModifiedDate");
            return (Criteria) this;
        }

        public Criteria andLastModifiedDateNotEqualTo(Date value) {
            addCriterion("lastModifiedDate <>", value, "lastModifiedDate");
            return (Criteria) this;
        }

        public Criteria andLastModifiedDateGreaterThan(Date value) {
            addCriterion("lastModifiedDate >", value, "lastModifiedDate");
            return (Criteria) this;
        }

        public Criteria andLastModifiedDateGreaterThanOrEqualTo(Date value) {
            addCriterion("lastModifiedDate >=", value, "lastModifiedDate");
            return (Criteria) this;
        }

        public Criteria andLastModifiedDateLessThan(Date value) {
            addCriterion("lastModifiedDate <", value, "lastModifiedDate");
            return (Criteria) this;
        }

        public Criteria andLastModifiedDateLessThanOrEqualTo(Date value) {
            addCriterion("lastModifiedDate <=", value, "lastModifiedDate");
            return (Criteria) this;
        }

        public Criteria andLastModifiedDateIn(List<Date> values) {
            addCriterion("lastModifiedDate in", values, "lastModifiedDate");
            return (Criteria) this;
        }

        public Criteria andLastModifiedDateNotIn(List<Date> values) {
            addCriterion("lastModifiedDate not in", values, "lastModifiedDate");
            return (Criteria) this;
        }

        public Criteria andLastModifiedDateBetween(Date value1, Date value2) {
            addCriterion("lastModifiedDate between", value1, value2, "lastModifiedDate");
            return (Criteria) this;
        }

        public Criteria andLastModifiedDateNotBetween(Date value1, Date value2) {
            addCriterion("lastModifiedDate not between", value1, value2, "lastModifiedDate");
            return (Criteria) this;
        }

        public Criteria andBatchNumIsNull() {
            addCriterion("batchNum is null");
            return (Criteria) this;
        }

        public Criteria andBatchNumIsNotNull() {
            addCriterion("batchNum is not null");
            return (Criteria) this;
        }

        public Criteria andBatchNumEqualTo(String value) {
            addCriterion("batchNum =", value, "batchNum");
            return (Criteria) this;
        }

        public Criteria andBatchNumNotEqualTo(String value) {
            addCriterion("batchNum <>", value, "batchNum");
            return (Criteria) this;
        }

        public Criteria andBatchNumGreaterThan(String value) {
            addCriterion("batchNum >", value, "batchNum");
            return (Criteria) this;
        }

        public Criteria andBatchNumGreaterThanOrEqualTo(String value) {
            addCriterion("batchNum >=", value, "batchNum");
            return (Criteria) this;
        }

        public Criteria andBatchNumLessThan(String value) {
            addCriterion("batchNum <", value, "batchNum");
            return (Criteria) this;
        }

        public Criteria andBatchNumLessThanOrEqualTo(String value) {
            addCriterion("batchNum <=", value, "batchNum");
            return (Criteria) this;
        }

        public Criteria andBatchNumLike(String value) {
            addCriterion("batchNum like", value, "batchNum");
            return (Criteria) this;
        }

        public Criteria andBatchNumNotLike(String value) {
            addCriterion("batchNum not like", value, "batchNum");
            return (Criteria) this;
        }

        public Criteria andBatchNumIn(List<String> values) {
            addCriterion("batchNum in", values, "batchNum");
            return (Criteria) this;
        }

        public Criteria andBatchNumNotIn(List<String> values) {
            addCriterion("batchNum not in", values, "batchNum");
            return (Criteria) this;
        }

        public Criteria andBatchNumBetween(String value1, String value2) {
            addCriterion("batchNum between", value1, value2, "batchNum");
            return (Criteria) this;
        }

        public Criteria andBatchNumNotBetween(String value1, String value2) {
            addCriterion("batchNum not between", value1, value2, "batchNum");
            return (Criteria) this;
        }

        public Criteria andBatchSerialNumberIsNull() {
            addCriterion("batchSerialNumber is null");
            return (Criteria) this;
        }

        public Criteria andBatchSerialNumberIsNotNull() {
            addCriterion("batchSerialNumber is not null");
            return (Criteria) this;
        }

        public Criteria andBatchSerialNumberEqualTo(Integer value) {
            addCriterion("batchSerialNumber =", value, "batchSerialNumber");
            return (Criteria) this;
        }

        public Criteria andBatchSerialNumberNotEqualTo(Integer value) {
            addCriterion("batchSerialNumber <>", value, "batchSerialNumber");
            return (Criteria) this;
        }

        public Criteria andBatchSerialNumberGreaterThan(Integer value) {
            addCriterion("batchSerialNumber >", value, "batchSerialNumber");
            return (Criteria) this;
        }

        public Criteria andBatchSerialNumberGreaterThanOrEqualTo(Integer value) {
            addCriterion("batchSerialNumber >=", value, "batchSerialNumber");
            return (Criteria) this;
        }

        public Criteria andBatchSerialNumberLessThan(Integer value) {
            addCriterion("batchSerialNumber <", value, "batchSerialNumber");
            return (Criteria) this;
        }

        public Criteria andBatchSerialNumberLessThanOrEqualTo(Integer value) {
            addCriterion("batchSerialNumber <=", value, "batchSerialNumber");
            return (Criteria) this;
        }

        public Criteria andBatchSerialNumberIn(List<Integer> values) {
            addCriterion("batchSerialNumber in", values, "batchSerialNumber");
            return (Criteria) this;
        }

        public Criteria andBatchSerialNumberNotIn(List<Integer> values) {
            addCriterion("batchSerialNumber not in", values, "batchSerialNumber");
            return (Criteria) this;
        }

        public Criteria andBatchSerialNumberBetween(Integer value1, Integer value2) {
            addCriterion("batchSerialNumber between", value1, value2, "batchSerialNumber");
            return (Criteria) this;
        }

        public Criteria andBatchSerialNumberNotBetween(Integer value1, Integer value2) {
            addCriterion("batchSerialNumber not between", value1, value2, "batchSerialNumber");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table CargoLocationType
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table CargoLocationType
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}