package com.dhl.tools.domain;

import java.io.Serializable;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table Material_CargoLocationType_Data
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class MaterialCargoLocationTypeData implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table Material_CargoLocationType_Data
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Material_CargoLocationType_Data.id
     *
     * @mbg.generated
     */
    private Integer id;
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Material_CargoLocationType_Data.wareHouseId
     *
     * @mbg.generated
     */
    private Integer wareHouseId;
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Material_CargoLocationType_Data.wareHouseCode
     *
     * @mbg.generated
     */
    private String wareHouseCode;
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Material_CargoLocationType_Data.materialId
     *
     * @mbg.generated
     */
    private Integer materialId;
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Material_CargoLocationType_Data.materialCode
     *
     * @mbg.generated
     */
    private String materialCode;
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Material_CargoLocationType_Data.materialLength
     *
     * @mbg.generated
     */
    private Double materialLength;
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Material_CargoLocationType_Data.materialWidth
     *
     * @mbg.generated
     */
    private Double materialWidth;
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Material_CargoLocationType_Data.materialHeight
     *
     * @mbg.generated
     */
    private Double materialHeight;
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Material_CargoLocationType_Data.materialMaxStore
     *
     * @mbg.generated
     */
    private Integer materialMaxStore;
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Material_CargoLocationType_Data.cargoLocationTypeId
     *
     * @mbg.generated
     */
    private Integer cargoLocationTypeId;
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Material_CargoLocationType_Data.cargoLocationTypeCode
     *
     * @mbg.generated
     */
    private String cargoLocationTypeCode;
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Material_CargoLocationType_Data.cargoLocationTypeCanUseCount
     *
     * @mbg.generated
     */
    private Integer cargoLocationTypeCanUseCount;
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Material_CargoLocationType_Data.cargoLocationTypeLength
     *
     * @mbg.generated
     */
    private Double cargoLocationTypeLength;
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Material_CargoLocationType_Data.cargoLocationTypeWidth
     *
     * @mbg.generated
     */
    private Double cargoLocationTypeWidth;
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Material_CargoLocationType_Data.cargoLocationTypeHeight
     *
     * @mbg.generated
     */
    private Double cargoLocationTypeHeight;
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Material_CargoLocationType_Data.cargoLocationTypeExtend
     *
     * @mbg.generated
     */
    private Boolean cargoLocationTypeExtend;
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Material_CargoLocationType_Data.cargoLocationTypePallet
     *
     * @mbg.generated
     */
    private Boolean cargoLocationTypePallet;
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Material_CargoLocationType_Data.storeCount
     *
     * @mbg.generated
     */
    private Integer storeCount;
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Material_CargoLocationType_Data.usageRate
     *
     * @mbg.generated
     */
    private Double usageRate;
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Material_CargoLocationType_Data.cargoLocationTypeVolume
     *
     * @mbg.generated
     */
    private Double cargoLocationTypeVolume;
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Material_CargoLocationType_Data.placement
     *
     * @mbg.generated
     */
    private String placement;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Material_CargoLocationType_Data.id
     *
     * @return the value of Material_CargoLocationType_Data.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Material_CargoLocationType_Data.id
     *
     * @param id the value for Material_CargoLocationType_Data.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Material_CargoLocationType_Data.wareHouseId
     *
     * @return the value of Material_CargoLocationType_Data.wareHouseId
     *
     * @mbg.generated
     */
    public Integer getWareHouseId() {
        return wareHouseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Material_CargoLocationType_Data.wareHouseId
     *
     * @param wareHouseId the value for Material_CargoLocationType_Data.wareHouseId
     *
     * @mbg.generated
     */
    public void setWareHouseId(Integer wareHouseId) {
        this.wareHouseId = wareHouseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Material_CargoLocationType_Data.wareHouseCode
     *
     * @return the value of Material_CargoLocationType_Data.wareHouseCode
     *
     * @mbg.generated
     */
    public String getWareHouseCode() {
        return wareHouseCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Material_CargoLocationType_Data.wareHouseCode
     *
     * @param wareHouseCode the value for Material_CargoLocationType_Data.wareHouseCode
     *
     * @mbg.generated
     */
    public void setWareHouseCode(String wareHouseCode) {
        this.wareHouseCode = wareHouseCode == null ? null : wareHouseCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Material_CargoLocationType_Data.materialId
     *
     * @return the value of Material_CargoLocationType_Data.materialId
     *
     * @mbg.generated
     */
    public Integer getMaterialId() {
        return materialId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Material_CargoLocationType_Data.materialId
     *
     * @param materialId the value for Material_CargoLocationType_Data.materialId
     *
     * @mbg.generated
     */
    public void setMaterialId(Integer materialId) {
        this.materialId = materialId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Material_CargoLocationType_Data.materialCode
     *
     * @return the value of Material_CargoLocationType_Data.materialCode
     *
     * @mbg.generated
     */
    public String getMaterialCode() {
        return materialCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Material_CargoLocationType_Data.materialCode
     *
     * @param materialCode the value for Material_CargoLocationType_Data.materialCode
     *
     * @mbg.generated
     */
    public void setMaterialCode(String materialCode) {
        this.materialCode = materialCode == null ? null : materialCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Material_CargoLocationType_Data.materialLength
     *
     * @return the value of Material_CargoLocationType_Data.materialLength
     *
     * @mbg.generated
     */
    public Double getMaterialLength() {
        return materialLength;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Material_CargoLocationType_Data.materialLength
     *
     * @param materialLength the value for Material_CargoLocationType_Data.materialLength
     *
     * @mbg.generated
     */
    public void setMaterialLength(Double materialLength) {
        this.materialLength = materialLength;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Material_CargoLocationType_Data.materialWidth
     *
     * @return the value of Material_CargoLocationType_Data.materialWidth
     *
     * @mbg.generated
     */
    public Double getMaterialWidth() {
        return materialWidth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Material_CargoLocationType_Data.materialWidth
     *
     * @param materialWidth the value for Material_CargoLocationType_Data.materialWidth
     *
     * @mbg.generated
     */
    public void setMaterialWidth(Double materialWidth) {
        this.materialWidth = materialWidth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Material_CargoLocationType_Data.materialHeight
     *
     * @return the value of Material_CargoLocationType_Data.materialHeight
     *
     * @mbg.generated
     */
    public Double getMaterialHeight() {
        return materialHeight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Material_CargoLocationType_Data.materialHeight
     *
     * @param materialHeight the value for Material_CargoLocationType_Data.materialHeight
     *
     * @mbg.generated
     */
    public void setMaterialHeight(Double materialHeight) {
        this.materialHeight = materialHeight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Material_CargoLocationType_Data.materialMaxStore
     *
     * @return the value of Material_CargoLocationType_Data.materialMaxStore
     *
     * @mbg.generated
     */
    public Integer getMaterialMaxStore() {
        return materialMaxStore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Material_CargoLocationType_Data.materialMaxStore
     *
     * @param materialMaxStore the value for Material_CargoLocationType_Data.materialMaxStore
     *
     * @mbg.generated
     */
    public void setMaterialMaxStore(Integer materialMaxStore) {
        this.materialMaxStore = materialMaxStore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Material_CargoLocationType_Data.cargoLocationTypeId
     *
     * @return the value of Material_CargoLocationType_Data.cargoLocationTypeId
     *
     * @mbg.generated
     */
    public Integer getCargoLocationTypeId() {
        return cargoLocationTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Material_CargoLocationType_Data.cargoLocationTypeId
     *
     * @param cargoLocationTypeId the value for Material_CargoLocationType_Data.cargoLocationTypeId
     *
     * @mbg.generated
     */
    public void setCargoLocationTypeId(Integer cargoLocationTypeId) {
        this.cargoLocationTypeId = cargoLocationTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Material_CargoLocationType_Data.cargoLocationTypeCode
     *
     * @return the value of Material_CargoLocationType_Data.cargoLocationTypeCode
     *
     * @mbg.generated
     */
    public String getCargoLocationTypeCode() {
        return cargoLocationTypeCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Material_CargoLocationType_Data.cargoLocationTypeCode
     *
     * @param cargoLocationTypeCode the value for Material_CargoLocationType_Data.cargoLocationTypeCode
     *
     * @mbg.generated
     */
    public void setCargoLocationTypeCode(String cargoLocationTypeCode) {
        this.cargoLocationTypeCode = cargoLocationTypeCode == null ? null : cargoLocationTypeCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Material_CargoLocationType_Data.cargoLocationTypeCanUseCount
     *
     * @return the value of Material_CargoLocationType_Data.cargoLocationTypeCanUseCount
     *
     * @mbg.generated
     */
    public Integer getCargoLocationTypeCanUseCount() {
        return cargoLocationTypeCanUseCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Material_CargoLocationType_Data.cargoLocationTypeCanUseCount
     *
     * @param cargoLocationTypeCanUseCount the value for Material_CargoLocationType_Data.cargoLocationTypeCanUseCount
     *
     * @mbg.generated
     */
    public void setCargoLocationTypeCanUseCount(Integer cargoLocationTypeCanUseCount) {
        this.cargoLocationTypeCanUseCount = cargoLocationTypeCanUseCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Material_CargoLocationType_Data.cargoLocationTypeLength
     *
     * @return the value of Material_CargoLocationType_Data.cargoLocationTypeLength
     *
     * @mbg.generated
     */
    public Double getCargoLocationTypeLength() {
        return cargoLocationTypeLength;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Material_CargoLocationType_Data.cargoLocationTypeLength
     *
     * @param cargoLocationTypeLength the value for Material_CargoLocationType_Data.cargoLocationTypeLength
     *
     * @mbg.generated
     */
    public void setCargoLocationTypeLength(Double cargoLocationTypeLength) {
        this.cargoLocationTypeLength = cargoLocationTypeLength;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Material_CargoLocationType_Data.cargoLocationTypeWidth
     *
     * @return the value of Material_CargoLocationType_Data.cargoLocationTypeWidth
     *
     * @mbg.generated
     */
    public Double getCargoLocationTypeWidth() {
        return cargoLocationTypeWidth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Material_CargoLocationType_Data.cargoLocationTypeWidth
     *
     * @param cargoLocationTypeWidth the value for Material_CargoLocationType_Data.cargoLocationTypeWidth
     *
     * @mbg.generated
     */
    public void setCargoLocationTypeWidth(Double cargoLocationTypeWidth) {
        this.cargoLocationTypeWidth = cargoLocationTypeWidth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Material_CargoLocationType_Data.cargoLocationTypeHeight
     *
     * @return the value of Material_CargoLocationType_Data.cargoLocationTypeHeight
     *
     * @mbg.generated
     */
    public Double getCargoLocationTypeHeight() {
        return cargoLocationTypeHeight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Material_CargoLocationType_Data.cargoLocationTypeHeight
     *
     * @param cargoLocationTypeHeight the value for Material_CargoLocationType_Data.cargoLocationTypeHeight
     *
     * @mbg.generated
     */
    public void setCargoLocationTypeHeight(Double cargoLocationTypeHeight) {
        this.cargoLocationTypeHeight = cargoLocationTypeHeight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Material_CargoLocationType_Data.cargoLocationTypeExtend
     *
     * @return the value of Material_CargoLocationType_Data.cargoLocationTypeExtend
     *
     * @mbg.generated
     */
    public Boolean getCargoLocationTypeExtend() {
        return cargoLocationTypeExtend;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Material_CargoLocationType_Data.cargoLocationTypeExtend
     *
     * @param cargoLocationTypeExtend the value for Material_CargoLocationType_Data.cargoLocationTypeExtend
     *
     * @mbg.generated
     */
    public void setCargoLocationTypeExtend(Boolean cargoLocationTypeExtend) {
        this.cargoLocationTypeExtend = cargoLocationTypeExtend;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Material_CargoLocationType_Data.cargoLocationTypePallet
     *
     * @return the value of Material_CargoLocationType_Data.cargoLocationTypePallet
     *
     * @mbg.generated
     */
    public Boolean getCargoLocationTypePallet() {
        return cargoLocationTypePallet;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Material_CargoLocationType_Data.cargoLocationTypePallet
     *
     * @param cargoLocationTypePallet the value for Material_CargoLocationType_Data.cargoLocationTypePallet
     *
     * @mbg.generated
     */
    public void setCargoLocationTypePallet(Boolean cargoLocationTypePallet) {
        this.cargoLocationTypePallet = cargoLocationTypePallet;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Material_CargoLocationType_Data.storeCount
     *
     * @return the value of Material_CargoLocationType_Data.storeCount
     *
     * @mbg.generated
     */
    public Integer getStoreCount() {
        return storeCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Material_CargoLocationType_Data.storeCount
     *
     * @param storeCount the value for Material_CargoLocationType_Data.storeCount
     *
     * @mbg.generated
     */
    public void setStoreCount(Integer storeCount) {
        this.storeCount = storeCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Material_CargoLocationType_Data.usageRate
     *
     * @return the value of Material_CargoLocationType_Data.usageRate
     *
     * @mbg.generated
     */
    public Double getUsageRate() {
        return usageRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Material_CargoLocationType_Data.usageRate
     *
     * @param usageRate the value for Material_CargoLocationType_Data.usageRate
     *
     * @mbg.generated
     */
    public void setUsageRate(Double usageRate) {
        this.usageRate = usageRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Material_CargoLocationType_Data.cargoLocationTypeVolume
     *
     * @return the value of Material_CargoLocationType_Data.cargoLocationTypeVolume
     *
     * @mbg.generated
     */
    public Double getCargoLocationTypeVolume() {
        return cargoLocationTypeVolume;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Material_CargoLocationType_Data.cargoLocationTypeVolume
     *
     * @param cargoLocationTypeVolume the value for Material_CargoLocationType_Data.cargoLocationTypeVolume
     *
     * @mbg.generated
     */
    public void setCargoLocationTypeVolume(Double cargoLocationTypeVolume) {
        this.cargoLocationTypeVolume = cargoLocationTypeVolume;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Material_CargoLocationType_Data.placement
     *
     * @return the value of Material_CargoLocationType_Data.placement
     *
     * @mbg.generated
     */
    public String getPlacement() {
        return placement;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Material_CargoLocationType_Data.placement
     *
     * @param placement the value for Material_CargoLocationType_Data.placement
     *
     * @mbg.generated
     */
    public void setPlacement(String placement) {
        this.placement = placement == null ? null : placement.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Material_CargoLocationType_Data
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", wareHouseId=").append(wareHouseId);
        sb.append(", wareHouseCode=").append(wareHouseCode);
        sb.append(", materialId=").append(materialId);
        sb.append(", materialCode=").append(materialCode);
        sb.append(", materialLength=").append(materialLength);
        sb.append(", materialWidth=").append(materialWidth);
        sb.append(", materialHeight=").append(materialHeight);
        sb.append(", materialMaxStore=").append(materialMaxStore);
        sb.append(", cargoLocationTypeId=").append(cargoLocationTypeId);
        sb.append(", cargoLocationTypeCode=").append(cargoLocationTypeCode);
        sb.append(", cargoLocationTypeCanUseCount=").append(cargoLocationTypeCanUseCount);
        sb.append(", cargoLocationTypeLength=").append(cargoLocationTypeLength);
        sb.append(", cargoLocationTypeWidth=").append(cargoLocationTypeWidth);
        sb.append(", cargoLocationTypeHeight=").append(cargoLocationTypeHeight);
        sb.append(", cargoLocationTypeExtend=").append(cargoLocationTypeExtend);
        sb.append(", cargoLocationTypePallet=").append(cargoLocationTypePallet);
        sb.append(", storeCount=").append(storeCount);
        sb.append(", usageRate=").append(usageRate);
        sb.append(", cargoLocationTypeVolume=").append(cargoLocationTypeVolume);
        sb.append(", placement=").append(placement);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}