package com.dhl.tools.domain;

import java.io.Serializable;
import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table Material
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class Material implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Material.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Material.code
     *
     * @mbg.generated
     */
    private String code;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Material.maxStore
     *
     * @mbg.generated
     */
    private Integer maxStore;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Material.length
     *
     * @mbg.generated
     */
    private Double length;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Material.width
     *
     * @mbg.generated
     */
    private Double width;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Material.height
     *
     * @mbg.generated
     */
    private Double height;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Material.faceUp
     *
     * @mbg.generated
     */
    private Boolean faceUp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Material.wareHouseId
     *
     * @mbg.generated
     */
    private Integer wareHouseId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Material.cargoLocationId
     *
     * @mbg.generated
     */
    private Integer cargoLocationId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Material.cargoLocationCode
     *
     * @mbg.generated
     */
    private String cargoLocationCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Material.cargoLocationScore
     *
     * @mbg.generated
     */
    private Double cargoLocationScore;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Material.recommendedLocationId
     *
     * @mbg.generated
     */
    private Integer recommendedLocationId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Material.recommendedLocationCode
     *
     * @mbg.generated
     */
    private String recommendedLocationCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Material.recommendedLocationScore
     *
     * @mbg.generated
     */
    private Double recommendedLocationScore;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Material.allAppropriateLibraryTypes
     *
     * @mbg.generated
     */
    private String allAppropriateLibraryTypes;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Material.extendAllAppropriateLibraryTypes
     *
     * @mbg.generated
     */
    private String extendAllAppropriateLibraryTypes;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Material.optimalLocationType
     *
     * @mbg.generated
     */
    private String optimalLocationType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Material.optimalPlacement
     *
     * @mbg.generated
     */
    private String optimalPlacement;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Material.recommendedLocationType
     *
     * @mbg.generated
     */
    private String recommendedLocationType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Material.recommendedPlacement
     *
     * @mbg.generated
     */
    private String recommendedPlacement;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Material.batchSerialNumber
     *
     * @mbg.generated
     */
    private Integer batchSerialNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Material.batchNum
     *
     * @mbg.generated
     */
    private String batchNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Material.cargoLocationTypeId
     *
     * @mbg.generated
     */
    private Integer cargoLocationTypeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Material.optimizationRecommend
     *
     * @mbg.generated
     */
    private String optimizationRecommend;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Material.pickUpRate
     *
     * @mbg.generated
     */
    private Integer pickUpRate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Material.createBy
     *
     * @mbg.generated
     */
    private String createBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Material.createDate
     *
     * @mbg.generated
     */
    private Date createDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Material.lastModifiedBy
     *
     * @mbg.generated
     */
    private String lastModifiedBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Material.lastModifiedDate
     *
     * @mbg.generated
     */
    private Date lastModifiedDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table Material
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Material.id
     *
     * @return the value of Material.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Material.id
     *
     * @param id the value for Material.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Material.code
     *
     * @return the value of Material.code
     *
     * @mbg.generated
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Material.code
     *
     * @param code the value for Material.code
     *
     * @mbg.generated
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Material.maxStore
     *
     * @return the value of Material.maxStore
     *
     * @mbg.generated
     */
    public Integer getMaxStore() {
        return maxStore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Material.maxStore
     *
     * @param maxStore the value for Material.maxStore
     *
     * @mbg.generated
     */
    public void setMaxStore(Integer maxStore) {
        this.maxStore = maxStore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Material.length
     *
     * @return the value of Material.length
     *
     * @mbg.generated
     */
    public Double getLength() {
        return length;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Material.length
     *
     * @param length the value for Material.length
     *
     * @mbg.generated
     */
    public void setLength(Double length) {
        this.length = length;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Material.width
     *
     * @return the value of Material.width
     *
     * @mbg.generated
     */
    public Double getWidth() {
        return width;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Material.width
     *
     * @param width the value for Material.width
     *
     * @mbg.generated
     */
    public void setWidth(Double width) {
        this.width = width;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Material.height
     *
     * @return the value of Material.height
     *
     * @mbg.generated
     */
    public Double getHeight() {
        return height;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Material.height
     *
     * @param height the value for Material.height
     *
     * @mbg.generated
     */
    public void setHeight(Double height) {
        this.height = height;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Material.faceUp
     *
     * @return the value of Material.faceUp
     *
     * @mbg.generated
     */
    public Boolean getFaceUp() {
        return faceUp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Material.faceUp
     *
     * @param faceUp the value for Material.faceUp
     *
     * @mbg.generated
     */
    public void setFaceUp(Boolean faceUp) {
        this.faceUp = faceUp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Material.wareHouseId
     *
     * @return the value of Material.wareHouseId
     *
     * @mbg.generated
     */
    public Integer getWareHouseId() {
        return wareHouseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Material.wareHouseId
     *
     * @param wareHouseId the value for Material.wareHouseId
     *
     * @mbg.generated
     */
    public void setWareHouseId(Integer wareHouseId) {
        this.wareHouseId = wareHouseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Material.cargoLocationId
     *
     * @return the value of Material.cargoLocationId
     *
     * @mbg.generated
     */
    public Integer getCargoLocationId() {
        return cargoLocationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Material.cargoLocationId
     *
     * @param cargoLocationId the value for Material.cargoLocationId
     *
     * @mbg.generated
     */
    public void setCargoLocationId(Integer cargoLocationId) {
        this.cargoLocationId = cargoLocationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Material.cargoLocationCode
     *
     * @return the value of Material.cargoLocationCode
     *
     * @mbg.generated
     */
    public String getCargoLocationCode() {
        return cargoLocationCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Material.cargoLocationCode
     *
     * @param cargoLocationCode the value for Material.cargoLocationCode
     *
     * @mbg.generated
     */
    public void setCargoLocationCode(String cargoLocationCode) {
        this.cargoLocationCode = cargoLocationCode == null ? null : cargoLocationCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Material.cargoLocationScore
     *
     * @return the value of Material.cargoLocationScore
     *
     * @mbg.generated
     */
    public Double getCargoLocationScore() {
        return cargoLocationScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Material.cargoLocationScore
     *
     * @param cargoLocationScore the value for Material.cargoLocationScore
     *
     * @mbg.generated
     */
    public void setCargoLocationScore(Double cargoLocationScore) {
        this.cargoLocationScore = cargoLocationScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Material.recommendedLocationId
     *
     * @return the value of Material.recommendedLocationId
     *
     * @mbg.generated
     */
    public Integer getRecommendedLocationId() {
        return recommendedLocationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Material.recommendedLocationId
     *
     * @param recommendedLocationId the value for Material.recommendedLocationId
     *
     * @mbg.generated
     */
    public void setRecommendedLocationId(Integer recommendedLocationId) {
        this.recommendedLocationId = recommendedLocationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Material.recommendedLocationCode
     *
     * @return the value of Material.recommendedLocationCode
     *
     * @mbg.generated
     */
    public String getRecommendedLocationCode() {
        return recommendedLocationCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Material.recommendedLocationCode
     *
     * @param recommendedLocationCode the value for Material.recommendedLocationCode
     *
     * @mbg.generated
     */
    public void setRecommendedLocationCode(String recommendedLocationCode) {
        this.recommendedLocationCode = recommendedLocationCode == null ? null : recommendedLocationCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Material.recommendedLocationScore
     *
     * @return the value of Material.recommendedLocationScore
     *
     * @mbg.generated
     */
    public Double getRecommendedLocationScore() {
        return recommendedLocationScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Material.recommendedLocationScore
     *
     * @param recommendedLocationScore the value for Material.recommendedLocationScore
     *
     * @mbg.generated
     */
    public void setRecommendedLocationScore(Double recommendedLocationScore) {
        this.recommendedLocationScore = recommendedLocationScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Material.allAppropriateLibraryTypes
     *
     * @return the value of Material.allAppropriateLibraryTypes
     *
     * @mbg.generated
     */
    public String getAllAppropriateLibraryTypes() {
        return allAppropriateLibraryTypes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Material.allAppropriateLibraryTypes
     *
     * @param allAppropriateLibraryTypes the value for Material.allAppropriateLibraryTypes
     *
     * @mbg.generated
     */
    public void setAllAppropriateLibraryTypes(String allAppropriateLibraryTypes) {
        this.allAppropriateLibraryTypes = allAppropriateLibraryTypes == null ? null : allAppropriateLibraryTypes.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Material.extendAllAppropriateLibraryTypes
     *
     * @return the value of Material.extendAllAppropriateLibraryTypes
     *
     * @mbg.generated
     */
    public String getExtendAllAppropriateLibraryTypes() {
        return extendAllAppropriateLibraryTypes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Material.extendAllAppropriateLibraryTypes
     *
     * @param extendAllAppropriateLibraryTypes the value for Material.extendAllAppropriateLibraryTypes
     *
     * @mbg.generated
     */
    public void setExtendAllAppropriateLibraryTypes(String extendAllAppropriateLibraryTypes) {
        this.extendAllAppropriateLibraryTypes = extendAllAppropriateLibraryTypes == null ? null : extendAllAppropriateLibraryTypes.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Material.optimalLocationType
     *
     * @return the value of Material.optimalLocationType
     *
     * @mbg.generated
     */
    public String getOptimalLocationType() {
        return optimalLocationType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Material.optimalLocationType
     *
     * @param optimalLocationType the value for Material.optimalLocationType
     *
     * @mbg.generated
     */
    public void setOptimalLocationType(String optimalLocationType) {
        this.optimalLocationType = optimalLocationType == null ? null : optimalLocationType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Material.optimalPlacement
     *
     * @return the value of Material.optimalPlacement
     *
     * @mbg.generated
     */
    public String getOptimalPlacement() {
        return optimalPlacement;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Material.optimalPlacement
     *
     * @param optimalPlacement the value for Material.optimalPlacement
     *
     * @mbg.generated
     */
    public void setOptimalPlacement(String optimalPlacement) {
        this.optimalPlacement = optimalPlacement == null ? null : optimalPlacement.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Material.recommendedLocationType
     *
     * @return the value of Material.recommendedLocationType
     *
     * @mbg.generated
     */
    public String getRecommendedLocationType() {
        return recommendedLocationType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Material.recommendedLocationType
     *
     * @param recommendedLocationType the value for Material.recommendedLocationType
     *
     * @mbg.generated
     */
    public void setRecommendedLocationType(String recommendedLocationType) {
        this.recommendedLocationType = recommendedLocationType == null ? null : recommendedLocationType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Material.recommendedPlacement
     *
     * @return the value of Material.recommendedPlacement
     *
     * @mbg.generated
     */
    public String getRecommendedPlacement() {
        return recommendedPlacement;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Material.recommendedPlacement
     *
     * @param recommendedPlacement the value for Material.recommendedPlacement
     *
     * @mbg.generated
     */
    public void setRecommendedPlacement(String recommendedPlacement) {
        this.recommendedPlacement = recommendedPlacement == null ? null : recommendedPlacement.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Material.batchSerialNumber
     *
     * @return the value of Material.batchSerialNumber
     *
     * @mbg.generated
     */
    public Integer getBatchSerialNumber() {
        return batchSerialNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Material.batchSerialNumber
     *
     * @param batchSerialNumber the value for Material.batchSerialNumber
     *
     * @mbg.generated
     */
    public void setBatchSerialNumber(Integer batchSerialNumber) {
        this.batchSerialNumber = batchSerialNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Material.batchNum
     *
     * @return the value of Material.batchNum
     *
     * @mbg.generated
     */
    public String getBatchNum() {
        return batchNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Material.batchNum
     *
     * @param batchNum the value for Material.batchNum
     *
     * @mbg.generated
     */
    public void setBatchNum(String batchNum) {
        this.batchNum = batchNum == null ? null : batchNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Material.cargoLocationTypeId
     *
     * @return the value of Material.cargoLocationTypeId
     *
     * @mbg.generated
     */
    public Integer getCargoLocationTypeId() {
        return cargoLocationTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Material.cargoLocationTypeId
     *
     * @param cargoLocationTypeId the value for Material.cargoLocationTypeId
     *
     * @mbg.generated
     */
    public void setCargoLocationTypeId(Integer cargoLocationTypeId) {
        this.cargoLocationTypeId = cargoLocationTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Material.optimizationRecommend
     *
     * @return the value of Material.optimizationRecommend
     *
     * @mbg.generated
     */
    public String getOptimizationRecommend() {
        return optimizationRecommend;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Material.optimizationRecommend
     *
     * @param optimizationRecommend the value for Material.optimizationRecommend
     *
     * @mbg.generated
     */
    public void setOptimizationRecommend(String optimizationRecommend) {
        this.optimizationRecommend = optimizationRecommend == null ? null : optimizationRecommend.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Material.pickUpRate
     *
     * @return the value of Material.pickUpRate
     *
     * @mbg.generated
     */
    public Integer getPickUpRate() {
        return pickUpRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Material.pickUpRate
     *
     * @param pickUpRate the value for Material.pickUpRate
     *
     * @mbg.generated
     */
    public void setPickUpRate(Integer pickUpRate) {
        this.pickUpRate = pickUpRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Material.createBy
     *
     * @return the value of Material.createBy
     *
     * @mbg.generated
     */
    public String getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Material.createBy
     *
     * @param createBy the value for Material.createBy
     *
     * @mbg.generated
     */
    public void setCreateBy(String createBy) {
        this.createBy = createBy == null ? null : createBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Material.createDate
     *
     * @return the value of Material.createDate
     *
     * @mbg.generated
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Material.createDate
     *
     * @param createDate the value for Material.createDate
     *
     * @mbg.generated
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Material.lastModifiedBy
     *
     * @return the value of Material.lastModifiedBy
     *
     * @mbg.generated
     */
    public String getLastModifiedBy() {
        return lastModifiedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Material.lastModifiedBy
     *
     * @param lastModifiedBy the value for Material.lastModifiedBy
     *
     * @mbg.generated
     */
    public void setLastModifiedBy(String lastModifiedBy) {
        this.lastModifiedBy = lastModifiedBy == null ? null : lastModifiedBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Material.lastModifiedDate
     *
     * @return the value of Material.lastModifiedDate
     *
     * @mbg.generated
     */
    public Date getLastModifiedDate() {
        return lastModifiedDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Material.lastModifiedDate
     *
     * @param lastModifiedDate the value for Material.lastModifiedDate
     *
     * @mbg.generated
     */
    public void setLastModifiedDate(Date lastModifiedDate) {
        this.lastModifiedDate = lastModifiedDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Material
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", code=").append(code);
        sb.append(", maxStore=").append(maxStore);
        sb.append(", length=").append(length);
        sb.append(", width=").append(width);
        sb.append(", height=").append(height);
        sb.append(", faceUp=").append(faceUp);
        sb.append(", wareHouseId=").append(wareHouseId);
        sb.append(", cargoLocationId=").append(cargoLocationId);
        sb.append(", cargoLocationCode=").append(cargoLocationCode);
        sb.append(", cargoLocationScore=").append(cargoLocationScore);
        sb.append(", recommendedLocationId=").append(recommendedLocationId);
        sb.append(", recommendedLocationCode=").append(recommendedLocationCode);
        sb.append(", recommendedLocationScore=").append(recommendedLocationScore);
        sb.append(", allAppropriateLibraryTypes=").append(allAppropriateLibraryTypes);
        sb.append(", extendAllAppropriateLibraryTypes=").append(extendAllAppropriateLibraryTypes);
        sb.append(", optimalLocationType=").append(optimalLocationType);
        sb.append(", optimalPlacement=").append(optimalPlacement);
        sb.append(", recommendedLocationType=").append(recommendedLocationType);
        sb.append(", recommendedPlacement=").append(recommendedPlacement);
        sb.append(", batchSerialNumber=").append(batchSerialNumber);
        sb.append(", batchNum=").append(batchNum);
        sb.append(", cargoLocationTypeId=").append(cargoLocationTypeId);
        sb.append(", optimizationRecommend=").append(optimizationRecommend);
        sb.append(", pickUpRate=").append(pickUpRate);
        sb.append(", createBy=").append(createBy);
        sb.append(", createDate=").append(createDate);
        sb.append(", lastModifiedBy=").append(lastModifiedBy);
        sb.append(", lastModifiedDate=").append(lastModifiedDate);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}