package com.dhl.tools.domain;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class MaterialExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table Material
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table Material
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table Material
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Material
     *
     * @mbg.generated
     */
    public MaterialExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Material
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Material
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Material
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Material
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Material
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Material
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Material
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Material
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Material
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Material
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table Material
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andCodeIsNull() {
            addCriterion("code is null");
            return (Criteria) this;
        }

        public Criteria andCodeIsNotNull() {
            addCriterion("code is not null");
            return (Criteria) this;
        }

        public Criteria andCodeEqualTo(String value) {
            addCriterion("code =", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeNotEqualTo(String value) {
            addCriterion("code <>", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeGreaterThan(String value) {
            addCriterion("code >", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeGreaterThanOrEqualTo(String value) {
            addCriterion("code >=", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeLessThan(String value) {
            addCriterion("code <", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeLessThanOrEqualTo(String value) {
            addCriterion("code <=", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeLike(String value) {
            addCriterion("code like", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeNotLike(String value) {
            addCriterion("code not like", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeIn(List<String> values) {
            addCriterion("code in", values, "code");
            return (Criteria) this;
        }

        public Criteria andCodeNotIn(List<String> values) {
            addCriterion("code not in", values, "code");
            return (Criteria) this;
        }

        public Criteria andCodeBetween(String value1, String value2) {
            addCriterion("code between", value1, value2, "code");
            return (Criteria) this;
        }

        public Criteria andCodeNotBetween(String value1, String value2) {
            addCriterion("code not between", value1, value2, "code");
            return (Criteria) this;
        }

        public Criteria andMaxStoreIsNull() {
            addCriterion("maxStore is null");
            return (Criteria) this;
        }

        public Criteria andMaxStoreIsNotNull() {
            addCriterion("maxStore is not null");
            return (Criteria) this;
        }

        public Criteria andMaxStoreEqualTo(Integer value) {
            addCriterion("maxStore =", value, "maxStore");
            return (Criteria) this;
        }

        public Criteria andMaxStoreNotEqualTo(Integer value) {
            addCriterion("maxStore <>", value, "maxStore");
            return (Criteria) this;
        }

        public Criteria andMaxStoreGreaterThan(Integer value) {
            addCriterion("maxStore >", value, "maxStore");
            return (Criteria) this;
        }

        public Criteria andMaxStoreGreaterThanOrEqualTo(Integer value) {
            addCriterion("maxStore >=", value, "maxStore");
            return (Criteria) this;
        }

        public Criteria andMaxStoreLessThan(Integer value) {
            addCriterion("maxStore <", value, "maxStore");
            return (Criteria) this;
        }

        public Criteria andMaxStoreLessThanOrEqualTo(Integer value) {
            addCriterion("maxStore <=", value, "maxStore");
            return (Criteria) this;
        }

        public Criteria andMaxStoreIn(List<Integer> values) {
            addCriterion("maxStore in", values, "maxStore");
            return (Criteria) this;
        }

        public Criteria andMaxStoreNotIn(List<Integer> values) {
            addCriterion("maxStore not in", values, "maxStore");
            return (Criteria) this;
        }

        public Criteria andMaxStoreBetween(Integer value1, Integer value2) {
            addCriterion("maxStore between", value1, value2, "maxStore");
            return (Criteria) this;
        }

        public Criteria andMaxStoreNotBetween(Integer value1, Integer value2) {
            addCriterion("maxStore not between", value1, value2, "maxStore");
            return (Criteria) this;
        }

        public Criteria andLengthIsNull() {
            addCriterion("length is null");
            return (Criteria) this;
        }

        public Criteria andLengthIsNotNull() {
            addCriterion("length is not null");
            return (Criteria) this;
        }

        public Criteria andLengthEqualTo(Double value) {
            addCriterion("length =", value, "length");
            return (Criteria) this;
        }

        public Criteria andLengthNotEqualTo(Double value) {
            addCriterion("length <>", value, "length");
            return (Criteria) this;
        }

        public Criteria andLengthGreaterThan(Double value) {
            addCriterion("length >", value, "length");
            return (Criteria) this;
        }

        public Criteria andLengthGreaterThanOrEqualTo(Double value) {
            addCriterion("length >=", value, "length");
            return (Criteria) this;
        }

        public Criteria andLengthLessThan(Double value) {
            addCriterion("length <", value, "length");
            return (Criteria) this;
        }

        public Criteria andLengthLessThanOrEqualTo(Double value) {
            addCriterion("length <=", value, "length");
            return (Criteria) this;
        }

        public Criteria andLengthIn(List<Double> values) {
            addCriterion("length in", values, "length");
            return (Criteria) this;
        }

        public Criteria andLengthNotIn(List<Double> values) {
            addCriterion("length not in", values, "length");
            return (Criteria) this;
        }

        public Criteria andLengthBetween(Double value1, Double value2) {
            addCriterion("length between", value1, value2, "length");
            return (Criteria) this;
        }

        public Criteria andLengthNotBetween(Double value1, Double value2) {
            addCriterion("length not between", value1, value2, "length");
            return (Criteria) this;
        }

        public Criteria andWidthIsNull() {
            addCriterion("width is null");
            return (Criteria) this;
        }

        public Criteria andWidthIsNotNull() {
            addCriterion("width is not null");
            return (Criteria) this;
        }

        public Criteria andWidthEqualTo(Double value) {
            addCriterion("width =", value, "width");
            return (Criteria) this;
        }

        public Criteria andWidthNotEqualTo(Double value) {
            addCriterion("width <>", value, "width");
            return (Criteria) this;
        }

        public Criteria andWidthGreaterThan(Double value) {
            addCriterion("width >", value, "width");
            return (Criteria) this;
        }

        public Criteria andWidthGreaterThanOrEqualTo(Double value) {
            addCriterion("width >=", value, "width");
            return (Criteria) this;
        }

        public Criteria andWidthLessThan(Double value) {
            addCriterion("width <", value, "width");
            return (Criteria) this;
        }

        public Criteria andWidthLessThanOrEqualTo(Double value) {
            addCriterion("width <=", value, "width");
            return (Criteria) this;
        }

        public Criteria andWidthIn(List<Double> values) {
            addCriterion("width in", values, "width");
            return (Criteria) this;
        }

        public Criteria andWidthNotIn(List<Double> values) {
            addCriterion("width not in", values, "width");
            return (Criteria) this;
        }

        public Criteria andWidthBetween(Double value1, Double value2) {
            addCriterion("width between", value1, value2, "width");
            return (Criteria) this;
        }

        public Criteria andWidthNotBetween(Double value1, Double value2) {
            addCriterion("width not between", value1, value2, "width");
            return (Criteria) this;
        }

        public Criteria andHeightIsNull() {
            addCriterion("height is null");
            return (Criteria) this;
        }

        public Criteria andHeightIsNotNull() {
            addCriterion("height is not null");
            return (Criteria) this;
        }

        public Criteria andHeightEqualTo(Double value) {
            addCriterion("height =", value, "height");
            return (Criteria) this;
        }

        public Criteria andHeightNotEqualTo(Double value) {
            addCriterion("height <>", value, "height");
            return (Criteria) this;
        }

        public Criteria andHeightGreaterThan(Double value) {
            addCriterion("height >", value, "height");
            return (Criteria) this;
        }

        public Criteria andHeightGreaterThanOrEqualTo(Double value) {
            addCriterion("height >=", value, "height");
            return (Criteria) this;
        }

        public Criteria andHeightLessThan(Double value) {
            addCriterion("height <", value, "height");
            return (Criteria) this;
        }

        public Criteria andHeightLessThanOrEqualTo(Double value) {
            addCriterion("height <=", value, "height");
            return (Criteria) this;
        }

        public Criteria andHeightIn(List<Double> values) {
            addCriterion("height in", values, "height");
            return (Criteria) this;
        }

        public Criteria andHeightNotIn(List<Double> values) {
            addCriterion("height not in", values, "height");
            return (Criteria) this;
        }

        public Criteria andHeightBetween(Double value1, Double value2) {
            addCriterion("height between", value1, value2, "height");
            return (Criteria) this;
        }

        public Criteria andHeightNotBetween(Double value1, Double value2) {
            addCriterion("height not between", value1, value2, "height");
            return (Criteria) this;
        }

        public Criteria andFaceUpIsNull() {
            addCriterion("faceUp is null");
            return (Criteria) this;
        }

        public Criteria andFaceUpIsNotNull() {
            addCriterion("faceUp is not null");
            return (Criteria) this;
        }

        public Criteria andFaceUpEqualTo(Boolean value) {
            addCriterion("faceUp =", value, "faceUp");
            return (Criteria) this;
        }

        public Criteria andFaceUpNotEqualTo(Boolean value) {
            addCriterion("faceUp <>", value, "faceUp");
            return (Criteria) this;
        }

        public Criteria andFaceUpGreaterThan(Boolean value) {
            addCriterion("faceUp >", value, "faceUp");
            return (Criteria) this;
        }

        public Criteria andFaceUpGreaterThanOrEqualTo(Boolean value) {
            addCriterion("faceUp >=", value, "faceUp");
            return (Criteria) this;
        }

        public Criteria andFaceUpLessThan(Boolean value) {
            addCriterion("faceUp <", value, "faceUp");
            return (Criteria) this;
        }

        public Criteria andFaceUpLessThanOrEqualTo(Boolean value) {
            addCriterion("faceUp <=", value, "faceUp");
            return (Criteria) this;
        }

        public Criteria andFaceUpIn(List<Boolean> values) {
            addCriterion("faceUp in", values, "faceUp");
            return (Criteria) this;
        }

        public Criteria andFaceUpNotIn(List<Boolean> values) {
            addCriterion("faceUp not in", values, "faceUp");
            return (Criteria) this;
        }

        public Criteria andFaceUpBetween(Boolean value1, Boolean value2) {
            addCriterion("faceUp between", value1, value2, "faceUp");
            return (Criteria) this;
        }

        public Criteria andFaceUpNotBetween(Boolean value1, Boolean value2) {
            addCriterion("faceUp not between", value1, value2, "faceUp");
            return (Criteria) this;
        }

        public Criteria andWareHouseIdIsNull() {
            addCriterion("wareHouseId is null");
            return (Criteria) this;
        }

        public Criteria andWareHouseIdIsNotNull() {
            addCriterion("wareHouseId is not null");
            return (Criteria) this;
        }

        public Criteria andWareHouseIdEqualTo(Integer value) {
            addCriterion("wareHouseId =", value, "wareHouseId");
            return (Criteria) this;
        }

        public Criteria andWareHouseIdNotEqualTo(Integer value) {
            addCriterion("wareHouseId <>", value, "wareHouseId");
            return (Criteria) this;
        }

        public Criteria andWareHouseIdGreaterThan(Integer value) {
            addCriterion("wareHouseId >", value, "wareHouseId");
            return (Criteria) this;
        }

        public Criteria andWareHouseIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("wareHouseId >=", value, "wareHouseId");
            return (Criteria) this;
        }

        public Criteria andWareHouseIdLessThan(Integer value) {
            addCriterion("wareHouseId <", value, "wareHouseId");
            return (Criteria) this;
        }

        public Criteria andWareHouseIdLessThanOrEqualTo(Integer value) {
            addCriterion("wareHouseId <=", value, "wareHouseId");
            return (Criteria) this;
        }

        public Criteria andWareHouseIdIn(List<Integer> values) {
            addCriterion("wareHouseId in", values, "wareHouseId");
            return (Criteria) this;
        }

        public Criteria andWareHouseIdNotIn(List<Integer> values) {
            addCriterion("wareHouseId not in", values, "wareHouseId");
            return (Criteria) this;
        }

        public Criteria andWareHouseIdBetween(Integer value1, Integer value2) {
            addCriterion("wareHouseId between", value1, value2, "wareHouseId");
            return (Criteria) this;
        }

        public Criteria andWareHouseIdNotBetween(Integer value1, Integer value2) {
            addCriterion("wareHouseId not between", value1, value2, "wareHouseId");
            return (Criteria) this;
        }

        public Criteria andCargoLocationIdIsNull() {
            addCriterion("cargoLocationId is null");
            return (Criteria) this;
        }

        public Criteria andCargoLocationIdIsNotNull() {
            addCriterion("cargoLocationId is not null");
            return (Criteria) this;
        }

        public Criteria andCargoLocationIdEqualTo(Integer value) {
            addCriterion("cargoLocationId =", value, "cargoLocationId");
            return (Criteria) this;
        }

        public Criteria andCargoLocationIdNotEqualTo(Integer value) {
            addCriterion("cargoLocationId <>", value, "cargoLocationId");
            return (Criteria) this;
        }

        public Criteria andCargoLocationIdGreaterThan(Integer value) {
            addCriterion("cargoLocationId >", value, "cargoLocationId");
            return (Criteria) this;
        }

        public Criteria andCargoLocationIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("cargoLocationId >=", value, "cargoLocationId");
            return (Criteria) this;
        }

        public Criteria andCargoLocationIdLessThan(Integer value) {
            addCriterion("cargoLocationId <", value, "cargoLocationId");
            return (Criteria) this;
        }

        public Criteria andCargoLocationIdLessThanOrEqualTo(Integer value) {
            addCriterion("cargoLocationId <=", value, "cargoLocationId");
            return (Criteria) this;
        }

        public Criteria andCargoLocationIdIn(List<Integer> values) {
            addCriterion("cargoLocationId in", values, "cargoLocationId");
            return (Criteria) this;
        }

        public Criteria andCargoLocationIdNotIn(List<Integer> values) {
            addCriterion("cargoLocationId not in", values, "cargoLocationId");
            return (Criteria) this;
        }

        public Criteria andCargoLocationIdBetween(Integer value1, Integer value2) {
            addCriterion("cargoLocationId between", value1, value2, "cargoLocationId");
            return (Criteria) this;
        }

        public Criteria andCargoLocationIdNotBetween(Integer value1, Integer value2) {
            addCriterion("cargoLocationId not between", value1, value2, "cargoLocationId");
            return (Criteria) this;
        }

        public Criteria andCargoLocationCodeIsNull() {
            addCriterion("cargoLocationCode is null");
            return (Criteria) this;
        }

        public Criteria andCargoLocationCodeIsNotNull() {
            addCriterion("cargoLocationCode is not null");
            return (Criteria) this;
        }

        public Criteria andCargoLocationCodeEqualTo(String value) {
            addCriterion("cargoLocationCode =", value, "cargoLocationCode");
            return (Criteria) this;
        }

        public Criteria andCargoLocationCodeNotEqualTo(String value) {
            addCriterion("cargoLocationCode <>", value, "cargoLocationCode");
            return (Criteria) this;
        }

        public Criteria andCargoLocationCodeGreaterThan(String value) {
            addCriterion("cargoLocationCode >", value, "cargoLocationCode");
            return (Criteria) this;
        }

        public Criteria andCargoLocationCodeGreaterThanOrEqualTo(String value) {
            addCriterion("cargoLocationCode >=", value, "cargoLocationCode");
            return (Criteria) this;
        }

        public Criteria andCargoLocationCodeLessThan(String value) {
            addCriterion("cargoLocationCode <", value, "cargoLocationCode");
            return (Criteria) this;
        }

        public Criteria andCargoLocationCodeLessThanOrEqualTo(String value) {
            addCriterion("cargoLocationCode <=", value, "cargoLocationCode");
            return (Criteria) this;
        }

        public Criteria andCargoLocationCodeLike(String value) {
            addCriterion("cargoLocationCode like", value, "cargoLocationCode");
            return (Criteria) this;
        }

        public Criteria andCargoLocationCodeNotLike(String value) {
            addCriterion("cargoLocationCode not like", value, "cargoLocationCode");
            return (Criteria) this;
        }

        public Criteria andCargoLocationCodeIn(List<String> values) {
            addCriterion("cargoLocationCode in", values, "cargoLocationCode");
            return (Criteria) this;
        }

        public Criteria andCargoLocationCodeNotIn(List<String> values) {
            addCriterion("cargoLocationCode not in", values, "cargoLocationCode");
            return (Criteria) this;
        }

        public Criteria andCargoLocationCodeBetween(String value1, String value2) {
            addCriterion("cargoLocationCode between", value1, value2, "cargoLocationCode");
            return (Criteria) this;
        }

        public Criteria andCargoLocationCodeNotBetween(String value1, String value2) {
            addCriterion("cargoLocationCode not between", value1, value2, "cargoLocationCode");
            return (Criteria) this;
        }

        public Criteria andCargoLocationScoreIsNull() {
            addCriterion("cargoLocationScore is null");
            return (Criteria) this;
        }

        public Criteria andCargoLocationScoreIsNotNull() {
            addCriterion("cargoLocationScore is not null");
            return (Criteria) this;
        }

        public Criteria andCargoLocationScoreEqualTo(Double value) {
            addCriterion("cargoLocationScore =", value, "cargoLocationScore");
            return (Criteria) this;
        }

        public Criteria andCargoLocationScoreNotEqualTo(Double value) {
            addCriterion("cargoLocationScore <>", value, "cargoLocationScore");
            return (Criteria) this;
        }

        public Criteria andCargoLocationScoreGreaterThan(Double value) {
            addCriterion("cargoLocationScore >", value, "cargoLocationScore");
            return (Criteria) this;
        }

        public Criteria andCargoLocationScoreGreaterThanOrEqualTo(Double value) {
            addCriterion("cargoLocationScore >=", value, "cargoLocationScore");
            return (Criteria) this;
        }

        public Criteria andCargoLocationScoreLessThan(Double value) {
            addCriterion("cargoLocationScore <", value, "cargoLocationScore");
            return (Criteria) this;
        }

        public Criteria andCargoLocationScoreLessThanOrEqualTo(Double value) {
            addCriterion("cargoLocationScore <=", value, "cargoLocationScore");
            return (Criteria) this;
        }

        public Criteria andCargoLocationScoreIn(List<Double> values) {
            addCriterion("cargoLocationScore in", values, "cargoLocationScore");
            return (Criteria) this;
        }

        public Criteria andCargoLocationScoreNotIn(List<Double> values) {
            addCriterion("cargoLocationScore not in", values, "cargoLocationScore");
            return (Criteria) this;
        }

        public Criteria andCargoLocationScoreBetween(Double value1, Double value2) {
            addCriterion("cargoLocationScore between", value1, value2, "cargoLocationScore");
            return (Criteria) this;
        }

        public Criteria andCargoLocationScoreNotBetween(Double value1, Double value2) {
            addCriterion("cargoLocationScore not between", value1, value2, "cargoLocationScore");
            return (Criteria) this;
        }

        public Criteria andRecommendedLocationIdIsNull() {
            addCriterion("recommendedLocationId is null");
            return (Criteria) this;
        }

        public Criteria andRecommendedLocationIdIsNotNull() {
            addCriterion("recommendedLocationId is not null");
            return (Criteria) this;
        }

        public Criteria andRecommendedLocationIdEqualTo(Integer value) {
            addCriterion("recommendedLocationId =", value, "recommendedLocationId");
            return (Criteria) this;
        }

        public Criteria andRecommendedLocationIdNotEqualTo(Integer value) {
            addCriterion("recommendedLocationId <>", value, "recommendedLocationId");
            return (Criteria) this;
        }

        public Criteria andRecommendedLocationIdGreaterThan(Integer value) {
            addCriterion("recommendedLocationId >", value, "recommendedLocationId");
            return (Criteria) this;
        }

        public Criteria andRecommendedLocationIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("recommendedLocationId >=", value, "recommendedLocationId");
            return (Criteria) this;
        }

        public Criteria andRecommendedLocationIdLessThan(Integer value) {
            addCriterion("recommendedLocationId <", value, "recommendedLocationId");
            return (Criteria) this;
        }

        public Criteria andRecommendedLocationIdLessThanOrEqualTo(Integer value) {
            addCriterion("recommendedLocationId <=", value, "recommendedLocationId");
            return (Criteria) this;
        }

        public Criteria andRecommendedLocationIdIn(List<Integer> values) {
            addCriterion("recommendedLocationId in", values, "recommendedLocationId");
            return (Criteria) this;
        }

        public Criteria andRecommendedLocationIdNotIn(List<Integer> values) {
            addCriterion("recommendedLocationId not in", values, "recommendedLocationId");
            return (Criteria) this;
        }

        public Criteria andRecommendedLocationIdBetween(Integer value1, Integer value2) {
            addCriterion("recommendedLocationId between", value1, value2, "recommendedLocationId");
            return (Criteria) this;
        }

        public Criteria andRecommendedLocationIdNotBetween(Integer value1, Integer value2) {
            addCriterion("recommendedLocationId not between", value1, value2, "recommendedLocationId");
            return (Criteria) this;
        }

        public Criteria andRecommendedLocationCodeIsNull() {
            addCriterion("recommendedLocationCode is null");
            return (Criteria) this;
        }

        public Criteria andRecommendedLocationCodeIsNotNull() {
            addCriterion("recommendedLocationCode is not null");
            return (Criteria) this;
        }

        public Criteria andRecommendedLocationCodeEqualTo(String value) {
            addCriterion("recommendedLocationCode =", value, "recommendedLocationCode");
            return (Criteria) this;
        }

        public Criteria andRecommendedLocationCodeNotEqualTo(String value) {
            addCriterion("recommendedLocationCode <>", value, "recommendedLocationCode");
            return (Criteria) this;
        }

        public Criteria andRecommendedLocationCodeGreaterThan(String value) {
            addCriterion("recommendedLocationCode >", value, "recommendedLocationCode");
            return (Criteria) this;
        }

        public Criteria andRecommendedLocationCodeGreaterThanOrEqualTo(String value) {
            addCriterion("recommendedLocationCode >=", value, "recommendedLocationCode");
            return (Criteria) this;
        }

        public Criteria andRecommendedLocationCodeLessThan(String value) {
            addCriterion("recommendedLocationCode <", value, "recommendedLocationCode");
            return (Criteria) this;
        }

        public Criteria andRecommendedLocationCodeLessThanOrEqualTo(String value) {
            addCriterion("recommendedLocationCode <=", value, "recommendedLocationCode");
            return (Criteria) this;
        }

        public Criteria andRecommendedLocationCodeLike(String value) {
            addCriterion("recommendedLocationCode like", value, "recommendedLocationCode");
            return (Criteria) this;
        }

        public Criteria andRecommendedLocationCodeNotLike(String value) {
            addCriterion("recommendedLocationCode not like", value, "recommendedLocationCode");
            return (Criteria) this;
        }

        public Criteria andRecommendedLocationCodeIn(List<String> values) {
            addCriterion("recommendedLocationCode in", values, "recommendedLocationCode");
            return (Criteria) this;
        }

        public Criteria andRecommendedLocationCodeNotIn(List<String> values) {
            addCriterion("recommendedLocationCode not in", values, "recommendedLocationCode");
            return (Criteria) this;
        }

        public Criteria andRecommendedLocationCodeBetween(String value1, String value2) {
            addCriterion("recommendedLocationCode between", value1, value2, "recommendedLocationCode");
            return (Criteria) this;
        }

        public Criteria andRecommendedLocationCodeNotBetween(String value1, String value2) {
            addCriterion("recommendedLocationCode not between", value1, value2, "recommendedLocationCode");
            return (Criteria) this;
        }

        public Criteria andRecommendedLocationScoreIsNull() {
            addCriterion("recommendedLocationScore is null");
            return (Criteria) this;
        }

        public Criteria andRecommendedLocationScoreIsNotNull() {
            addCriterion("recommendedLocationScore is not null");
            return (Criteria) this;
        }

        public Criteria andRecommendedLocationScoreEqualTo(Double value) {
            addCriterion("recommendedLocationScore =", value, "recommendedLocationScore");
            return (Criteria) this;
        }

        public Criteria andRecommendedLocationScoreNotEqualTo(Double value) {
            addCriterion("recommendedLocationScore <>", value, "recommendedLocationScore");
            return (Criteria) this;
        }

        public Criteria andRecommendedLocationScoreGreaterThan(Double value) {
            addCriterion("recommendedLocationScore >", value, "recommendedLocationScore");
            return (Criteria) this;
        }

        public Criteria andRecommendedLocationScoreGreaterThanOrEqualTo(Double value) {
            addCriterion("recommendedLocationScore >=", value, "recommendedLocationScore");
            return (Criteria) this;
        }

        public Criteria andRecommendedLocationScoreLessThan(Double value) {
            addCriterion("recommendedLocationScore <", value, "recommendedLocationScore");
            return (Criteria) this;
        }

        public Criteria andRecommendedLocationScoreLessThanOrEqualTo(Double value) {
            addCriterion("recommendedLocationScore <=", value, "recommendedLocationScore");
            return (Criteria) this;
        }

        public Criteria andRecommendedLocationScoreIn(List<Double> values) {
            addCriterion("recommendedLocationScore in", values, "recommendedLocationScore");
            return (Criteria) this;
        }

        public Criteria andRecommendedLocationScoreNotIn(List<Double> values) {
            addCriterion("recommendedLocationScore not in", values, "recommendedLocationScore");
            return (Criteria) this;
        }

        public Criteria andRecommendedLocationScoreBetween(Double value1, Double value2) {
            addCriterion("recommendedLocationScore between", value1, value2, "recommendedLocationScore");
            return (Criteria) this;
        }

        public Criteria andRecommendedLocationScoreNotBetween(Double value1, Double value2) {
            addCriterion("recommendedLocationScore not between", value1, value2, "recommendedLocationScore");
            return (Criteria) this;
        }

        public Criteria andAllAppropriateLibraryTypesIsNull() {
            addCriterion("allAppropriateLibraryTypes is null");
            return (Criteria) this;
        }

        public Criteria andAllAppropriateLibraryTypesIsNotNull() {
            addCriterion("allAppropriateLibraryTypes is not null");
            return (Criteria) this;
        }

        public Criteria andAllAppropriateLibraryTypesEqualTo(String value) {
            addCriterion("allAppropriateLibraryTypes =", value, "allAppropriateLibraryTypes");
            return (Criteria) this;
        }

        public Criteria andAllAppropriateLibraryTypesNotEqualTo(String value) {
            addCriterion("allAppropriateLibraryTypes <>", value, "allAppropriateLibraryTypes");
            return (Criteria) this;
        }

        public Criteria andAllAppropriateLibraryTypesGreaterThan(String value) {
            addCriterion("allAppropriateLibraryTypes >", value, "allAppropriateLibraryTypes");
            return (Criteria) this;
        }

        public Criteria andAllAppropriateLibraryTypesGreaterThanOrEqualTo(String value) {
            addCriterion("allAppropriateLibraryTypes >=", value, "allAppropriateLibraryTypes");
            return (Criteria) this;
        }

        public Criteria andAllAppropriateLibraryTypesLessThan(String value) {
            addCriterion("allAppropriateLibraryTypes <", value, "allAppropriateLibraryTypes");
            return (Criteria) this;
        }

        public Criteria andAllAppropriateLibraryTypesLessThanOrEqualTo(String value) {
            addCriterion("allAppropriateLibraryTypes <=", value, "allAppropriateLibraryTypes");
            return (Criteria) this;
        }

        public Criteria andAllAppropriateLibraryTypesLike(String value) {
            addCriterion("allAppropriateLibraryTypes like", value, "allAppropriateLibraryTypes");
            return (Criteria) this;
        }

        public Criteria andAllAppropriateLibraryTypesNotLike(String value) {
            addCriterion("allAppropriateLibraryTypes not like", value, "allAppropriateLibraryTypes");
            return (Criteria) this;
        }

        public Criteria andAllAppropriateLibraryTypesIn(List<String> values) {
            addCriterion("allAppropriateLibraryTypes in", values, "allAppropriateLibraryTypes");
            return (Criteria) this;
        }

        public Criteria andAllAppropriateLibraryTypesNotIn(List<String> values) {
            addCriterion("allAppropriateLibraryTypes not in", values, "allAppropriateLibraryTypes");
            return (Criteria) this;
        }

        public Criteria andAllAppropriateLibraryTypesBetween(String value1, String value2) {
            addCriterion("allAppropriateLibraryTypes between", value1, value2, "allAppropriateLibraryTypes");
            return (Criteria) this;
        }

        public Criteria andAllAppropriateLibraryTypesNotBetween(String value1, String value2) {
            addCriterion("allAppropriateLibraryTypes not between", value1, value2, "allAppropriateLibraryTypes");
            return (Criteria) this;
        }

        public Criteria andExtendAllAppropriateLibraryTypesIsNull() {
            addCriterion("extendAllAppropriateLibraryTypes is null");
            return (Criteria) this;
        }

        public Criteria andExtendAllAppropriateLibraryTypesIsNotNull() {
            addCriterion("extendAllAppropriateLibraryTypes is not null");
            return (Criteria) this;
        }

        public Criteria andExtendAllAppropriateLibraryTypesEqualTo(String value) {
            addCriterion("extendAllAppropriateLibraryTypes =", value, "extendAllAppropriateLibraryTypes");
            return (Criteria) this;
        }

        public Criteria andExtendAllAppropriateLibraryTypesNotEqualTo(String value) {
            addCriterion("extendAllAppropriateLibraryTypes <>", value, "extendAllAppropriateLibraryTypes");
            return (Criteria) this;
        }

        public Criteria andExtendAllAppropriateLibraryTypesGreaterThan(String value) {
            addCriterion("extendAllAppropriateLibraryTypes >", value, "extendAllAppropriateLibraryTypes");
            return (Criteria) this;
        }

        public Criteria andExtendAllAppropriateLibraryTypesGreaterThanOrEqualTo(String value) {
            addCriterion("extendAllAppropriateLibraryTypes >=", value, "extendAllAppropriateLibraryTypes");
            return (Criteria) this;
        }

        public Criteria andExtendAllAppropriateLibraryTypesLessThan(String value) {
            addCriterion("extendAllAppropriateLibraryTypes <", value, "extendAllAppropriateLibraryTypes");
            return (Criteria) this;
        }

        public Criteria andExtendAllAppropriateLibraryTypesLessThanOrEqualTo(String value) {
            addCriterion("extendAllAppropriateLibraryTypes <=", value, "extendAllAppropriateLibraryTypes");
            return (Criteria) this;
        }

        public Criteria andExtendAllAppropriateLibraryTypesLike(String value) {
            addCriterion("extendAllAppropriateLibraryTypes like", value, "extendAllAppropriateLibraryTypes");
            return (Criteria) this;
        }

        public Criteria andExtendAllAppropriateLibraryTypesNotLike(String value) {
            addCriterion("extendAllAppropriateLibraryTypes not like", value, "extendAllAppropriateLibraryTypes");
            return (Criteria) this;
        }

        public Criteria andExtendAllAppropriateLibraryTypesIn(List<String> values) {
            addCriterion("extendAllAppropriateLibraryTypes in", values, "extendAllAppropriateLibraryTypes");
            return (Criteria) this;
        }

        public Criteria andExtendAllAppropriateLibraryTypesNotIn(List<String> values) {
            addCriterion("extendAllAppropriateLibraryTypes not in", values, "extendAllAppropriateLibraryTypes");
            return (Criteria) this;
        }

        public Criteria andExtendAllAppropriateLibraryTypesBetween(String value1, String value2) {
            addCriterion("extendAllAppropriateLibraryTypes between", value1, value2, "extendAllAppropriateLibraryTypes");
            return (Criteria) this;
        }

        public Criteria andExtendAllAppropriateLibraryTypesNotBetween(String value1, String value2) {
            addCriterion("extendAllAppropriateLibraryTypes not between", value1, value2, "extendAllAppropriateLibraryTypes");
            return (Criteria) this;
        }

        public Criteria andOptimalLocationTypeIsNull() {
            addCriterion("optimalLocationType is null");
            return (Criteria) this;
        }

        public Criteria andOptimalLocationTypeIsNotNull() {
            addCriterion("optimalLocationType is not null");
            return (Criteria) this;
        }

        public Criteria andOptimalLocationTypeEqualTo(String value) {
            addCriterion("optimalLocationType =", value, "optimalLocationType");
            return (Criteria) this;
        }

        public Criteria andOptimalLocationTypeNotEqualTo(String value) {
            addCriterion("optimalLocationType <>", value, "optimalLocationType");
            return (Criteria) this;
        }

        public Criteria andOptimalLocationTypeGreaterThan(String value) {
            addCriterion("optimalLocationType >", value, "optimalLocationType");
            return (Criteria) this;
        }

        public Criteria andOptimalLocationTypeGreaterThanOrEqualTo(String value) {
            addCriterion("optimalLocationType >=", value, "optimalLocationType");
            return (Criteria) this;
        }

        public Criteria andOptimalLocationTypeLessThan(String value) {
            addCriterion("optimalLocationType <", value, "optimalLocationType");
            return (Criteria) this;
        }

        public Criteria andOptimalLocationTypeLessThanOrEqualTo(String value) {
            addCriterion("optimalLocationType <=", value, "optimalLocationType");
            return (Criteria) this;
        }

        public Criteria andOptimalLocationTypeLike(String value) {
            addCriterion("optimalLocationType like", value, "optimalLocationType");
            return (Criteria) this;
        }

        public Criteria andOptimalLocationTypeNotLike(String value) {
            addCriterion("optimalLocationType not like", value, "optimalLocationType");
            return (Criteria) this;
        }

        public Criteria andOptimalLocationTypeIn(List<String> values) {
            addCriterion("optimalLocationType in", values, "optimalLocationType");
            return (Criteria) this;
        }

        public Criteria andOptimalLocationTypeNotIn(List<String> values) {
            addCriterion("optimalLocationType not in", values, "optimalLocationType");
            return (Criteria) this;
        }

        public Criteria andOptimalLocationTypeBetween(String value1, String value2) {
            addCriterion("optimalLocationType between", value1, value2, "optimalLocationType");
            return (Criteria) this;
        }

        public Criteria andOptimalLocationTypeNotBetween(String value1, String value2) {
            addCriterion("optimalLocationType not between", value1, value2, "optimalLocationType");
            return (Criteria) this;
        }

        public Criteria andOptimalPlacementIsNull() {
            addCriterion("optimalPlacement is null");
            return (Criteria) this;
        }

        public Criteria andOptimalPlacementIsNotNull() {
            addCriterion("optimalPlacement is not null");
            return (Criteria) this;
        }

        public Criteria andOptimalPlacementEqualTo(String value) {
            addCriterion("optimalPlacement =", value, "optimalPlacement");
            return (Criteria) this;
        }

        public Criteria andOptimalPlacementNotEqualTo(String value) {
            addCriterion("optimalPlacement <>", value, "optimalPlacement");
            return (Criteria) this;
        }

        public Criteria andOptimalPlacementGreaterThan(String value) {
            addCriterion("optimalPlacement >", value, "optimalPlacement");
            return (Criteria) this;
        }

        public Criteria andOptimalPlacementGreaterThanOrEqualTo(String value) {
            addCriterion("optimalPlacement >=", value, "optimalPlacement");
            return (Criteria) this;
        }

        public Criteria andOptimalPlacementLessThan(String value) {
            addCriterion("optimalPlacement <", value, "optimalPlacement");
            return (Criteria) this;
        }

        public Criteria andOptimalPlacementLessThanOrEqualTo(String value) {
            addCriterion("optimalPlacement <=", value, "optimalPlacement");
            return (Criteria) this;
        }

        public Criteria andOptimalPlacementLike(String value) {
            addCriterion("optimalPlacement like", value, "optimalPlacement");
            return (Criteria) this;
        }

        public Criteria andOptimalPlacementNotLike(String value) {
            addCriterion("optimalPlacement not like", value, "optimalPlacement");
            return (Criteria) this;
        }

        public Criteria andOptimalPlacementIn(List<String> values) {
            addCriterion("optimalPlacement in", values, "optimalPlacement");
            return (Criteria) this;
        }

        public Criteria andOptimalPlacementNotIn(List<String> values) {
            addCriterion("optimalPlacement not in", values, "optimalPlacement");
            return (Criteria) this;
        }

        public Criteria andOptimalPlacementBetween(String value1, String value2) {
            addCriterion("optimalPlacement between", value1, value2, "optimalPlacement");
            return (Criteria) this;
        }

        public Criteria andOptimalPlacementNotBetween(String value1, String value2) {
            addCriterion("optimalPlacement not between", value1, value2, "optimalPlacement");
            return (Criteria) this;
        }

        public Criteria andRecommendedLocationTypeIsNull() {
            addCriterion("recommendedLocationType is null");
            return (Criteria) this;
        }

        public Criteria andRecommendedLocationTypeIsNotNull() {
            addCriterion("recommendedLocationType is not null");
            return (Criteria) this;
        }

        public Criteria andRecommendedLocationTypeEqualTo(String value) {
            addCriterion("recommendedLocationType =", value, "recommendedLocationType");
            return (Criteria) this;
        }

        public Criteria andRecommendedLocationTypeNotEqualTo(String value) {
            addCriterion("recommendedLocationType <>", value, "recommendedLocationType");
            return (Criteria) this;
        }

        public Criteria andRecommendedLocationTypeGreaterThan(String value) {
            addCriterion("recommendedLocationType >", value, "recommendedLocationType");
            return (Criteria) this;
        }

        public Criteria andRecommendedLocationTypeGreaterThanOrEqualTo(String value) {
            addCriterion("recommendedLocationType >=", value, "recommendedLocationType");
            return (Criteria) this;
        }

        public Criteria andRecommendedLocationTypeLessThan(String value) {
            addCriterion("recommendedLocationType <", value, "recommendedLocationType");
            return (Criteria) this;
        }

        public Criteria andRecommendedLocationTypeLessThanOrEqualTo(String value) {
            addCriterion("recommendedLocationType <=", value, "recommendedLocationType");
            return (Criteria) this;
        }

        public Criteria andRecommendedLocationTypeLike(String value) {
            addCriterion("recommendedLocationType like", value, "recommendedLocationType");
            return (Criteria) this;
        }

        public Criteria andRecommendedLocationTypeNotLike(String value) {
            addCriterion("recommendedLocationType not like", value, "recommendedLocationType");
            return (Criteria) this;
        }

        public Criteria andRecommendedLocationTypeIn(List<String> values) {
            addCriterion("recommendedLocationType in", values, "recommendedLocationType");
            return (Criteria) this;
        }

        public Criteria andRecommendedLocationTypeNotIn(List<String> values) {
            addCriterion("recommendedLocationType not in", values, "recommendedLocationType");
            return (Criteria) this;
        }

        public Criteria andRecommendedLocationTypeBetween(String value1, String value2) {
            addCriterion("recommendedLocationType between", value1, value2, "recommendedLocationType");
            return (Criteria) this;
        }

        public Criteria andRecommendedLocationTypeNotBetween(String value1, String value2) {
            addCriterion("recommendedLocationType not between", value1, value2, "recommendedLocationType");
            return (Criteria) this;
        }

        public Criteria andRecommendedPlacementIsNull() {
            addCriterion("recommendedPlacement is null");
            return (Criteria) this;
        }

        public Criteria andRecommendedPlacementIsNotNull() {
            addCriterion("recommendedPlacement is not null");
            return (Criteria) this;
        }

        public Criteria andRecommendedPlacementEqualTo(String value) {
            addCriterion("recommendedPlacement =", value, "recommendedPlacement");
            return (Criteria) this;
        }

        public Criteria andRecommendedPlacementNotEqualTo(String value) {
            addCriterion("recommendedPlacement <>", value, "recommendedPlacement");
            return (Criteria) this;
        }

        public Criteria andRecommendedPlacementGreaterThan(String value) {
            addCriterion("recommendedPlacement >", value, "recommendedPlacement");
            return (Criteria) this;
        }

        public Criteria andRecommendedPlacementGreaterThanOrEqualTo(String value) {
            addCriterion("recommendedPlacement >=", value, "recommendedPlacement");
            return (Criteria) this;
        }

        public Criteria andRecommendedPlacementLessThan(String value) {
            addCriterion("recommendedPlacement <", value, "recommendedPlacement");
            return (Criteria) this;
        }

        public Criteria andRecommendedPlacementLessThanOrEqualTo(String value) {
            addCriterion("recommendedPlacement <=", value, "recommendedPlacement");
            return (Criteria) this;
        }

        public Criteria andRecommendedPlacementLike(String value) {
            addCriterion("recommendedPlacement like", value, "recommendedPlacement");
            return (Criteria) this;
        }

        public Criteria andRecommendedPlacementNotLike(String value) {
            addCriterion("recommendedPlacement not like", value, "recommendedPlacement");
            return (Criteria) this;
        }

        public Criteria andRecommendedPlacementIn(List<String> values) {
            addCriterion("recommendedPlacement in", values, "recommendedPlacement");
            return (Criteria) this;
        }

        public Criteria andRecommendedPlacementNotIn(List<String> values) {
            addCriterion("recommendedPlacement not in", values, "recommendedPlacement");
            return (Criteria) this;
        }

        public Criteria andRecommendedPlacementBetween(String value1, String value2) {
            addCriterion("recommendedPlacement between", value1, value2, "recommendedPlacement");
            return (Criteria) this;
        }

        public Criteria andRecommendedPlacementNotBetween(String value1, String value2) {
            addCriterion("recommendedPlacement not between", value1, value2, "recommendedPlacement");
            return (Criteria) this;
        }

        public Criteria andBatchSerialNumberIsNull() {
            addCriterion("batchSerialNumber is null");
            return (Criteria) this;
        }

        public Criteria andBatchSerialNumberIsNotNull() {
            addCriterion("batchSerialNumber is not null");
            return (Criteria) this;
        }

        public Criteria andBatchSerialNumberEqualTo(Integer value) {
            addCriterion("batchSerialNumber =", value, "batchSerialNumber");
            return (Criteria) this;
        }

        public Criteria andBatchSerialNumberNotEqualTo(Integer value) {
            addCriterion("batchSerialNumber <>", value, "batchSerialNumber");
            return (Criteria) this;
        }

        public Criteria andBatchSerialNumberGreaterThan(Integer value) {
            addCriterion("batchSerialNumber >", value, "batchSerialNumber");
            return (Criteria) this;
        }

        public Criteria andBatchSerialNumberGreaterThanOrEqualTo(Integer value) {
            addCriterion("batchSerialNumber >=", value, "batchSerialNumber");
            return (Criteria) this;
        }

        public Criteria andBatchSerialNumberLessThan(Integer value) {
            addCriterion("batchSerialNumber <", value, "batchSerialNumber");
            return (Criteria) this;
        }

        public Criteria andBatchSerialNumberLessThanOrEqualTo(Integer value) {
            addCriterion("batchSerialNumber <=", value, "batchSerialNumber");
            return (Criteria) this;
        }

        public Criteria andBatchSerialNumberIn(List<Integer> values) {
            addCriterion("batchSerialNumber in", values, "batchSerialNumber");
            return (Criteria) this;
        }

        public Criteria andBatchSerialNumberNotIn(List<Integer> values) {
            addCriterion("batchSerialNumber not in", values, "batchSerialNumber");
            return (Criteria) this;
        }

        public Criteria andBatchSerialNumberBetween(Integer value1, Integer value2) {
            addCriterion("batchSerialNumber between", value1, value2, "batchSerialNumber");
            return (Criteria) this;
        }

        public Criteria andBatchSerialNumberNotBetween(Integer value1, Integer value2) {
            addCriterion("batchSerialNumber not between", value1, value2, "batchSerialNumber");
            return (Criteria) this;
        }

        public Criteria andBatchNumIsNull() {
            addCriterion("batchNum is null");
            return (Criteria) this;
        }

        public Criteria andBatchNumIsNotNull() {
            addCriterion("batchNum is not null");
            return (Criteria) this;
        }

        public Criteria andBatchNumEqualTo(String value) {
            addCriterion("batchNum =", value, "batchNum");
            return (Criteria) this;
        }

        public Criteria andBatchNumNotEqualTo(String value) {
            addCriterion("batchNum <>", value, "batchNum");
            return (Criteria) this;
        }

        public Criteria andBatchNumGreaterThan(String value) {
            addCriterion("batchNum >", value, "batchNum");
            return (Criteria) this;
        }

        public Criteria andBatchNumGreaterThanOrEqualTo(String value) {
            addCriterion("batchNum >=", value, "batchNum");
            return (Criteria) this;
        }

        public Criteria andBatchNumLessThan(String value) {
            addCriterion("batchNum <", value, "batchNum");
            return (Criteria) this;
        }

        public Criteria andBatchNumLessThanOrEqualTo(String value) {
            addCriterion("batchNum <=", value, "batchNum");
            return (Criteria) this;
        }

        public Criteria andBatchNumLike(String value) {
            addCriterion("batchNum like", value, "batchNum");
            return (Criteria) this;
        }

        public Criteria andBatchNumNotLike(String value) {
            addCriterion("batchNum not like", value, "batchNum");
            return (Criteria) this;
        }

        public Criteria andBatchNumIn(List<String> values) {
            addCriterion("batchNum in", values, "batchNum");
            return (Criteria) this;
        }

        public Criteria andBatchNumNotIn(List<String> values) {
            addCriterion("batchNum not in", values, "batchNum");
            return (Criteria) this;
        }

        public Criteria andBatchNumBetween(String value1, String value2) {
            addCriterion("batchNum between", value1, value2, "batchNum");
            return (Criteria) this;
        }

        public Criteria andBatchNumNotBetween(String value1, String value2) {
            addCriterion("batchNum not between", value1, value2, "batchNum");
            return (Criteria) this;
        }

        public Criteria andCargoLocationTypeIdIsNull() {
            addCriterion("cargoLocationTypeId is null");
            return (Criteria) this;
        }

        public Criteria andCargoLocationTypeIdIsNotNull() {
            addCriterion("cargoLocationTypeId is not null");
            return (Criteria) this;
        }

        public Criteria andCargoLocationTypeIdEqualTo(Integer value) {
            addCriterion("cargoLocationTypeId =", value, "cargoLocationTypeId");
            return (Criteria) this;
        }

        public Criteria andCargoLocationTypeIdNotEqualTo(Integer value) {
            addCriterion("cargoLocationTypeId <>", value, "cargoLocationTypeId");
            return (Criteria) this;
        }

        public Criteria andCargoLocationTypeIdGreaterThan(Integer value) {
            addCriterion("cargoLocationTypeId >", value, "cargoLocationTypeId");
            return (Criteria) this;
        }

        public Criteria andCargoLocationTypeIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("cargoLocationTypeId >=", value, "cargoLocationTypeId");
            return (Criteria) this;
        }

        public Criteria andCargoLocationTypeIdLessThan(Integer value) {
            addCriterion("cargoLocationTypeId <", value, "cargoLocationTypeId");
            return (Criteria) this;
        }

        public Criteria andCargoLocationTypeIdLessThanOrEqualTo(Integer value) {
            addCriterion("cargoLocationTypeId <=", value, "cargoLocationTypeId");
            return (Criteria) this;
        }

        public Criteria andCargoLocationTypeIdIn(List<Integer> values) {
            addCriterion("cargoLocationTypeId in", values, "cargoLocationTypeId");
            return (Criteria) this;
        }

        public Criteria andCargoLocationTypeIdNotIn(List<Integer> values) {
            addCriterion("cargoLocationTypeId not in", values, "cargoLocationTypeId");
            return (Criteria) this;
        }

        public Criteria andCargoLocationTypeIdBetween(Integer value1, Integer value2) {
            addCriterion("cargoLocationTypeId between", value1, value2, "cargoLocationTypeId");
            return (Criteria) this;
        }

        public Criteria andCargoLocationTypeIdNotBetween(Integer value1, Integer value2) {
            addCriterion("cargoLocationTypeId not between", value1, value2, "cargoLocationTypeId");
            return (Criteria) this;
        }

        public Criteria andOptimizationRecommendIsNull() {
            addCriterion("optimizationRecommend is null");
            return (Criteria) this;
        }

        public Criteria andOptimizationRecommendIsNotNull() {
            addCriterion("optimizationRecommend is not null");
            return (Criteria) this;
        }

        public Criteria andOptimizationRecommendEqualTo(String value) {
            addCriterion("optimizationRecommend =", value, "optimizationRecommend");
            return (Criteria) this;
        }

        public Criteria andOptimizationRecommendNotEqualTo(String value) {
            addCriterion("optimizationRecommend <>", value, "optimizationRecommend");
            return (Criteria) this;
        }

        public Criteria andOptimizationRecommendGreaterThan(String value) {
            addCriterion("optimizationRecommend >", value, "optimizationRecommend");
            return (Criteria) this;
        }

        public Criteria andOptimizationRecommendGreaterThanOrEqualTo(String value) {
            addCriterion("optimizationRecommend >=", value, "optimizationRecommend");
            return (Criteria) this;
        }

        public Criteria andOptimizationRecommendLessThan(String value) {
            addCriterion("optimizationRecommend <", value, "optimizationRecommend");
            return (Criteria) this;
        }

        public Criteria andOptimizationRecommendLessThanOrEqualTo(String value) {
            addCriterion("optimizationRecommend <=", value, "optimizationRecommend");
            return (Criteria) this;
        }

        public Criteria andOptimizationRecommendLike(String value) {
            addCriterion("optimizationRecommend like", value, "optimizationRecommend");
            return (Criteria) this;
        }

        public Criteria andOptimizationRecommendNotLike(String value) {
            addCriterion("optimizationRecommend not like", value, "optimizationRecommend");
            return (Criteria) this;
        }

        public Criteria andOptimizationRecommendIn(List<String> values) {
            addCriterion("optimizationRecommend in", values, "optimizationRecommend");
            return (Criteria) this;
        }

        public Criteria andOptimizationRecommendNotIn(List<String> values) {
            addCriterion("optimizationRecommend not in", values, "optimizationRecommend");
            return (Criteria) this;
        }

        public Criteria andOptimizationRecommendBetween(String value1, String value2) {
            addCriterion("optimizationRecommend between", value1, value2, "optimizationRecommend");
            return (Criteria) this;
        }

        public Criteria andOptimizationRecommendNotBetween(String value1, String value2) {
            addCriterion("optimizationRecommend not between", value1, value2, "optimizationRecommend");
            return (Criteria) this;
        }

        public Criteria andPickUpRateIsNull() {
            addCriterion("pickUpRate is null");
            return (Criteria) this;
        }

        public Criteria andPickUpRateIsNotNull() {
            addCriterion("pickUpRate is not null");
            return (Criteria) this;
        }

        public Criteria andPickUpRateEqualTo(Integer value) {
            addCriterion("pickUpRate =", value, "pickUpRate");
            return (Criteria) this;
        }

        public Criteria andPickUpRateNotEqualTo(Integer value) {
            addCriterion("pickUpRate <>", value, "pickUpRate");
            return (Criteria) this;
        }

        public Criteria andPickUpRateGreaterThan(Integer value) {
            addCriterion("pickUpRate >", value, "pickUpRate");
            return (Criteria) this;
        }

        public Criteria andPickUpRateGreaterThanOrEqualTo(Integer value) {
            addCriterion("pickUpRate >=", value, "pickUpRate");
            return (Criteria) this;
        }

        public Criteria andPickUpRateLessThan(Integer value) {
            addCriterion("pickUpRate <", value, "pickUpRate");
            return (Criteria) this;
        }

        public Criteria andPickUpRateLessThanOrEqualTo(Integer value) {
            addCriterion("pickUpRate <=", value, "pickUpRate");
            return (Criteria) this;
        }

        public Criteria andPickUpRateIn(List<Integer> values) {
            addCriterion("pickUpRate in", values, "pickUpRate");
            return (Criteria) this;
        }

        public Criteria andPickUpRateNotIn(List<Integer> values) {
            addCriterion("pickUpRate not in", values, "pickUpRate");
            return (Criteria) this;
        }

        public Criteria andPickUpRateBetween(Integer value1, Integer value2) {
            addCriterion("pickUpRate between", value1, value2, "pickUpRate");
            return (Criteria) this;
        }

        public Criteria andPickUpRateNotBetween(Integer value1, Integer value2) {
            addCriterion("pickUpRate not between", value1, value2, "pickUpRate");
            return (Criteria) this;
        }

        public Criteria andCreateByIsNull() {
            addCriterion("createBy is null");
            return (Criteria) this;
        }

        public Criteria andCreateByIsNotNull() {
            addCriterion("createBy is not null");
            return (Criteria) this;
        }

        public Criteria andCreateByEqualTo(String value) {
            addCriterion("createBy =", value, "createBy");
            return (Criteria) this;
        }

        public Criteria andCreateByNotEqualTo(String value) {
            addCriterion("createBy <>", value, "createBy");
            return (Criteria) this;
        }

        public Criteria andCreateByGreaterThan(String value) {
            addCriterion("createBy >", value, "createBy");
            return (Criteria) this;
        }

        public Criteria andCreateByGreaterThanOrEqualTo(String value) {
            addCriterion("createBy >=", value, "createBy");
            return (Criteria) this;
        }

        public Criteria andCreateByLessThan(String value) {
            addCriterion("createBy <", value, "createBy");
            return (Criteria) this;
        }

        public Criteria andCreateByLessThanOrEqualTo(String value) {
            addCriterion("createBy <=", value, "createBy");
            return (Criteria) this;
        }

        public Criteria andCreateByLike(String value) {
            addCriterion("createBy like", value, "createBy");
            return (Criteria) this;
        }

        public Criteria andCreateByNotLike(String value) {
            addCriterion("createBy not like", value, "createBy");
            return (Criteria) this;
        }

        public Criteria andCreateByIn(List<String> values) {
            addCriterion("createBy in", values, "createBy");
            return (Criteria) this;
        }

        public Criteria andCreateByNotIn(List<String> values) {
            addCriterion("createBy not in", values, "createBy");
            return (Criteria) this;
        }

        public Criteria andCreateByBetween(String value1, String value2) {
            addCriterion("createBy between", value1, value2, "createBy");
            return (Criteria) this;
        }

        public Criteria andCreateByNotBetween(String value1, String value2) {
            addCriterion("createBy not between", value1, value2, "createBy");
            return (Criteria) this;
        }

        public Criteria andCreateDateIsNull() {
            addCriterion("createDate is null");
            return (Criteria) this;
        }

        public Criteria andCreateDateIsNotNull() {
            addCriterion("createDate is not null");
            return (Criteria) this;
        }

        public Criteria andCreateDateEqualTo(Date value) {
            addCriterion("createDate =", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateNotEqualTo(Date value) {
            addCriterion("createDate <>", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateGreaterThan(Date value) {
            addCriterion("createDate >", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateGreaterThanOrEqualTo(Date value) {
            addCriterion("createDate >=", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateLessThan(Date value) {
            addCriterion("createDate <", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateLessThanOrEqualTo(Date value) {
            addCriterion("createDate <=", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateIn(List<Date> values) {
            addCriterion("createDate in", values, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateNotIn(List<Date> values) {
            addCriterion("createDate not in", values, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateBetween(Date value1, Date value2) {
            addCriterion("createDate between", value1, value2, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateNotBetween(Date value1, Date value2) {
            addCriterion("createDate not between", value1, value2, "createDate");
            return (Criteria) this;
        }

        public Criteria andLastModifiedByIsNull() {
            addCriterion("lastModifiedBy is null");
            return (Criteria) this;
        }

        public Criteria andLastModifiedByIsNotNull() {
            addCriterion("lastModifiedBy is not null");
            return (Criteria) this;
        }

        public Criteria andLastModifiedByEqualTo(String value) {
            addCriterion("lastModifiedBy =", value, "lastModifiedBy");
            return (Criteria) this;
        }

        public Criteria andLastModifiedByNotEqualTo(String value) {
            addCriterion("lastModifiedBy <>", value, "lastModifiedBy");
            return (Criteria) this;
        }

        public Criteria andLastModifiedByGreaterThan(String value) {
            addCriterion("lastModifiedBy >", value, "lastModifiedBy");
            return (Criteria) this;
        }

        public Criteria andLastModifiedByGreaterThanOrEqualTo(String value) {
            addCriterion("lastModifiedBy >=", value, "lastModifiedBy");
            return (Criteria) this;
        }

        public Criteria andLastModifiedByLessThan(String value) {
            addCriterion("lastModifiedBy <", value, "lastModifiedBy");
            return (Criteria) this;
        }

        public Criteria andLastModifiedByLessThanOrEqualTo(String value) {
            addCriterion("lastModifiedBy <=", value, "lastModifiedBy");
            return (Criteria) this;
        }

        public Criteria andLastModifiedByLike(String value) {
            addCriterion("lastModifiedBy like", value, "lastModifiedBy");
            return (Criteria) this;
        }

        public Criteria andLastModifiedByNotLike(String value) {
            addCriterion("lastModifiedBy not like", value, "lastModifiedBy");
            return (Criteria) this;
        }

        public Criteria andLastModifiedByIn(List<String> values) {
            addCriterion("lastModifiedBy in", values, "lastModifiedBy");
            return (Criteria) this;
        }

        public Criteria andLastModifiedByNotIn(List<String> values) {
            addCriterion("lastModifiedBy not in", values, "lastModifiedBy");
            return (Criteria) this;
        }

        public Criteria andLastModifiedByBetween(String value1, String value2) {
            addCriterion("lastModifiedBy between", value1, value2, "lastModifiedBy");
            return (Criteria) this;
        }

        public Criteria andLastModifiedByNotBetween(String value1, String value2) {
            addCriterion("lastModifiedBy not between", value1, value2, "lastModifiedBy");
            return (Criteria) this;
        }

        public Criteria andLastModifiedDateIsNull() {
            addCriterion("lastModifiedDate is null");
            return (Criteria) this;
        }

        public Criteria andLastModifiedDateIsNotNull() {
            addCriterion("lastModifiedDate is not null");
            return (Criteria) this;
        }

        public Criteria andLastModifiedDateEqualTo(Date value) {
            addCriterion("lastModifiedDate =", value, "lastModifiedDate");
            return (Criteria) this;
        }

        public Criteria andLastModifiedDateNotEqualTo(Date value) {
            addCriterion("lastModifiedDate <>", value, "lastModifiedDate");
            return (Criteria) this;
        }

        public Criteria andLastModifiedDateGreaterThan(Date value) {
            addCriterion("lastModifiedDate >", value, "lastModifiedDate");
            return (Criteria) this;
        }

        public Criteria andLastModifiedDateGreaterThanOrEqualTo(Date value) {
            addCriterion("lastModifiedDate >=", value, "lastModifiedDate");
            return (Criteria) this;
        }

        public Criteria andLastModifiedDateLessThan(Date value) {
            addCriterion("lastModifiedDate <", value, "lastModifiedDate");
            return (Criteria) this;
        }

        public Criteria andLastModifiedDateLessThanOrEqualTo(Date value) {
            addCriterion("lastModifiedDate <=", value, "lastModifiedDate");
            return (Criteria) this;
        }

        public Criteria andLastModifiedDateIn(List<Date> values) {
            addCriterion("lastModifiedDate in", values, "lastModifiedDate");
            return (Criteria) this;
        }

        public Criteria andLastModifiedDateNotIn(List<Date> values) {
            addCriterion("lastModifiedDate not in", values, "lastModifiedDate");
            return (Criteria) this;
        }

        public Criteria andLastModifiedDateBetween(Date value1, Date value2) {
            addCriterion("lastModifiedDate between", value1, value2, "lastModifiedDate");
            return (Criteria) this;
        }

        public Criteria andLastModifiedDateNotBetween(Date value1, Date value2) {
            addCriterion("lastModifiedDate not between", value1, value2, "lastModifiedDate");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table Material
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table Material
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}