package com.dhl.tools.domain;

import java.util.ArrayList;
import java.util.List;

public class MaterialCargoLocationTypeDataExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table Material_CargoLocationType_Data
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table Material_CargoLocationType_Data
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table Material_CargoLocationType_Data
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Material_CargoLocationType_Data
     *
     * @mbg.generated
     */
    public MaterialCargoLocationTypeDataExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Material_CargoLocationType_Data
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Material_CargoLocationType_Data
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Material_CargoLocationType_Data
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Material_CargoLocationType_Data
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Material_CargoLocationType_Data
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Material_CargoLocationType_Data
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Material_CargoLocationType_Data
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Material_CargoLocationType_Data
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Material_CargoLocationType_Data
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Material_CargoLocationType_Data
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table Material_CargoLocationType_Data
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andWareHouseIdIsNull() {
            addCriterion("wareHouseId is null");
            return (Criteria) this;
        }

        public Criteria andWareHouseIdIsNotNull() {
            addCriterion("wareHouseId is not null");
            return (Criteria) this;
        }

        public Criteria andWareHouseIdEqualTo(Integer value) {
            addCriterion("wareHouseId =", value, "wareHouseId");
            return (Criteria) this;
        }

        public Criteria andWareHouseIdNotEqualTo(Integer value) {
            addCriterion("wareHouseId <>", value, "wareHouseId");
            return (Criteria) this;
        }

        public Criteria andWareHouseIdGreaterThan(Integer value) {
            addCriterion("wareHouseId >", value, "wareHouseId");
            return (Criteria) this;
        }

        public Criteria andWareHouseIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("wareHouseId >=", value, "wareHouseId");
            return (Criteria) this;
        }

        public Criteria andWareHouseIdLessThan(Integer value) {
            addCriterion("wareHouseId <", value, "wareHouseId");
            return (Criteria) this;
        }

        public Criteria andWareHouseIdLessThanOrEqualTo(Integer value) {
            addCriterion("wareHouseId <=", value, "wareHouseId");
            return (Criteria) this;
        }

        public Criteria andWareHouseIdIn(List<Integer> values) {
            addCriterion("wareHouseId in", values, "wareHouseId");
            return (Criteria) this;
        }

        public Criteria andWareHouseIdNotIn(List<Integer> values) {
            addCriterion("wareHouseId not in", values, "wareHouseId");
            return (Criteria) this;
        }

        public Criteria andWareHouseIdBetween(Integer value1, Integer value2) {
            addCriterion("wareHouseId between", value1, value2, "wareHouseId");
            return (Criteria) this;
        }

        public Criteria andWareHouseIdNotBetween(Integer value1, Integer value2) {
            addCriterion("wareHouseId not between", value1, value2, "wareHouseId");
            return (Criteria) this;
        }

        public Criteria andWareHouseCodeIsNull() {
            addCriterion("wareHouseCode is null");
            return (Criteria) this;
        }

        public Criteria andWareHouseCodeIsNotNull() {
            addCriterion("wareHouseCode is not null");
            return (Criteria) this;
        }

        public Criteria andWareHouseCodeEqualTo(String value) {
            addCriterion("wareHouseCode =", value, "wareHouseCode");
            return (Criteria) this;
        }

        public Criteria andWareHouseCodeNotEqualTo(String value) {
            addCriterion("wareHouseCode <>", value, "wareHouseCode");
            return (Criteria) this;
        }

        public Criteria andWareHouseCodeGreaterThan(String value) {
            addCriterion("wareHouseCode >", value, "wareHouseCode");
            return (Criteria) this;
        }

        public Criteria andWareHouseCodeGreaterThanOrEqualTo(String value) {
            addCriterion("wareHouseCode >=", value, "wareHouseCode");
            return (Criteria) this;
        }

        public Criteria andWareHouseCodeLessThan(String value) {
            addCriterion("wareHouseCode <", value, "wareHouseCode");
            return (Criteria) this;
        }

        public Criteria andWareHouseCodeLessThanOrEqualTo(String value) {
            addCriterion("wareHouseCode <=", value, "wareHouseCode");
            return (Criteria) this;
        }

        public Criteria andWareHouseCodeLike(String value) {
            addCriterion("wareHouseCode like", value, "wareHouseCode");
            return (Criteria) this;
        }

        public Criteria andWareHouseCodeNotLike(String value) {
            addCriterion("wareHouseCode not like", value, "wareHouseCode");
            return (Criteria) this;
        }

        public Criteria andWareHouseCodeIn(List<String> values) {
            addCriterion("wareHouseCode in", values, "wareHouseCode");
            return (Criteria) this;
        }

        public Criteria andWareHouseCodeNotIn(List<String> values) {
            addCriterion("wareHouseCode not in", values, "wareHouseCode");
            return (Criteria) this;
        }

        public Criteria andWareHouseCodeBetween(String value1, String value2) {
            addCriterion("wareHouseCode between", value1, value2, "wareHouseCode");
            return (Criteria) this;
        }

        public Criteria andWareHouseCodeNotBetween(String value1, String value2) {
            addCriterion("wareHouseCode not between", value1, value2, "wareHouseCode");
            return (Criteria) this;
        }

        public Criteria andMaterialIdIsNull() {
            addCriterion("materialId is null");
            return (Criteria) this;
        }

        public Criteria andMaterialIdIsNotNull() {
            addCriterion("materialId is not null");
            return (Criteria) this;
        }

        public Criteria andMaterialIdEqualTo(Integer value) {
            addCriterion("materialId =", value, "materialId");
            return (Criteria) this;
        }

        public Criteria andMaterialIdNotEqualTo(Integer value) {
            addCriterion("materialId <>", value, "materialId");
            return (Criteria) this;
        }

        public Criteria andMaterialIdGreaterThan(Integer value) {
            addCriterion("materialId >", value, "materialId");
            return (Criteria) this;
        }

        public Criteria andMaterialIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("materialId >=", value, "materialId");
            return (Criteria) this;
        }

        public Criteria andMaterialIdLessThan(Integer value) {
            addCriterion("materialId <", value, "materialId");
            return (Criteria) this;
        }

        public Criteria andMaterialIdLessThanOrEqualTo(Integer value) {
            addCriterion("materialId <=", value, "materialId");
            return (Criteria) this;
        }

        public Criteria andMaterialIdIn(List<Integer> values) {
            addCriterion("materialId in", values, "materialId");
            return (Criteria) this;
        }

        public Criteria andMaterialIdNotIn(List<Integer> values) {
            addCriterion("materialId not in", values, "materialId");
            return (Criteria) this;
        }

        public Criteria andMaterialIdBetween(Integer value1, Integer value2) {
            addCriterion("materialId between", value1, value2, "materialId");
            return (Criteria) this;
        }

        public Criteria andMaterialIdNotBetween(Integer value1, Integer value2) {
            addCriterion("materialId not between", value1, value2, "materialId");
            return (Criteria) this;
        }

        public Criteria andMaterialCodeIsNull() {
            addCriterion("materialCode is null");
            return (Criteria) this;
        }

        public Criteria andMaterialCodeIsNotNull() {
            addCriterion("materialCode is not null");
            return (Criteria) this;
        }

        public Criteria andMaterialCodeEqualTo(String value) {
            addCriterion("materialCode =", value, "materialCode");
            return (Criteria) this;
        }

        public Criteria andMaterialCodeNotEqualTo(String value) {
            addCriterion("materialCode <>", value, "materialCode");
            return (Criteria) this;
        }

        public Criteria andMaterialCodeGreaterThan(String value) {
            addCriterion("materialCode >", value, "materialCode");
            return (Criteria) this;
        }

        public Criteria andMaterialCodeGreaterThanOrEqualTo(String value) {
            addCriterion("materialCode >=", value, "materialCode");
            return (Criteria) this;
        }

        public Criteria andMaterialCodeLessThan(String value) {
            addCriterion("materialCode <", value, "materialCode");
            return (Criteria) this;
        }

        public Criteria andMaterialCodeLessThanOrEqualTo(String value) {
            addCriterion("materialCode <=", value, "materialCode");
            return (Criteria) this;
        }

        public Criteria andMaterialCodeLike(String value) {
            addCriterion("materialCode like", value, "materialCode");
            return (Criteria) this;
        }

        public Criteria andMaterialCodeNotLike(String value) {
            addCriterion("materialCode not like", value, "materialCode");
            return (Criteria) this;
        }

        public Criteria andMaterialCodeIn(List<String> values) {
            addCriterion("materialCode in", values, "materialCode");
            return (Criteria) this;
        }

        public Criteria andMaterialCodeNotIn(List<String> values) {
            addCriterion("materialCode not in", values, "materialCode");
            return (Criteria) this;
        }

        public Criteria andMaterialCodeBetween(String value1, String value2) {
            addCriterion("materialCode between", value1, value2, "materialCode");
            return (Criteria) this;
        }

        public Criteria andMaterialCodeNotBetween(String value1, String value2) {
            addCriterion("materialCode not between", value1, value2, "materialCode");
            return (Criteria) this;
        }

        public Criteria andMaterialLengthIsNull() {
            addCriterion("materialLength is null");
            return (Criteria) this;
        }

        public Criteria andMaterialLengthIsNotNull() {
            addCriterion("materialLength is not null");
            return (Criteria) this;
        }

        public Criteria andMaterialLengthEqualTo(Double value) {
            addCriterion("materialLength =", value, "materialLength");
            return (Criteria) this;
        }

        public Criteria andMaterialLengthNotEqualTo(Double value) {
            addCriterion("materialLength <>", value, "materialLength");
            return (Criteria) this;
        }

        public Criteria andMaterialLengthGreaterThan(Double value) {
            addCriterion("materialLength >", value, "materialLength");
            return (Criteria) this;
        }

        public Criteria andMaterialLengthGreaterThanOrEqualTo(Double value) {
            addCriterion("materialLength >=", value, "materialLength");
            return (Criteria) this;
        }

        public Criteria andMaterialLengthLessThan(Double value) {
            addCriterion("materialLength <", value, "materialLength");
            return (Criteria) this;
        }

        public Criteria andMaterialLengthLessThanOrEqualTo(Double value) {
            addCriterion("materialLength <=", value, "materialLength");
            return (Criteria) this;
        }

        public Criteria andMaterialLengthIn(List<Double> values) {
            addCriterion("materialLength in", values, "materialLength");
            return (Criteria) this;
        }

        public Criteria andMaterialLengthNotIn(List<Double> values) {
            addCriterion("materialLength not in", values, "materialLength");
            return (Criteria) this;
        }

        public Criteria andMaterialLengthBetween(Double value1, Double value2) {
            addCriterion("materialLength between", value1, value2, "materialLength");
            return (Criteria) this;
        }

        public Criteria andMaterialLengthNotBetween(Double value1, Double value2) {
            addCriterion("materialLength not between", value1, value2, "materialLength");
            return (Criteria) this;
        }

        public Criteria andMaterialWidthIsNull() {
            addCriterion("materialWidth is null");
            return (Criteria) this;
        }

        public Criteria andMaterialWidthIsNotNull() {
            addCriterion("materialWidth is not null");
            return (Criteria) this;
        }

        public Criteria andMaterialWidthEqualTo(Double value) {
            addCriterion("materialWidth =", value, "materialWidth");
            return (Criteria) this;
        }

        public Criteria andMaterialWidthNotEqualTo(Double value) {
            addCriterion("materialWidth <>", value, "materialWidth");
            return (Criteria) this;
        }

        public Criteria andMaterialWidthGreaterThan(Double value) {
            addCriterion("materialWidth >", value, "materialWidth");
            return (Criteria) this;
        }

        public Criteria andMaterialWidthGreaterThanOrEqualTo(Double value) {
            addCriterion("materialWidth >=", value, "materialWidth");
            return (Criteria) this;
        }

        public Criteria andMaterialWidthLessThan(Double value) {
            addCriterion("materialWidth <", value, "materialWidth");
            return (Criteria) this;
        }

        public Criteria andMaterialWidthLessThanOrEqualTo(Double value) {
            addCriterion("materialWidth <=", value, "materialWidth");
            return (Criteria) this;
        }

        public Criteria andMaterialWidthIn(List<Double> values) {
            addCriterion("materialWidth in", values, "materialWidth");
            return (Criteria) this;
        }

        public Criteria andMaterialWidthNotIn(List<Double> values) {
            addCriterion("materialWidth not in", values, "materialWidth");
            return (Criteria) this;
        }

        public Criteria andMaterialWidthBetween(Double value1, Double value2) {
            addCriterion("materialWidth between", value1, value2, "materialWidth");
            return (Criteria) this;
        }

        public Criteria andMaterialWidthNotBetween(Double value1, Double value2) {
            addCriterion("materialWidth not between", value1, value2, "materialWidth");
            return (Criteria) this;
        }

        public Criteria andMaterialHeightIsNull() {
            addCriterion("materialHeight is null");
            return (Criteria) this;
        }

        public Criteria andMaterialHeightIsNotNull() {
            addCriterion("materialHeight is not null");
            return (Criteria) this;
        }

        public Criteria andMaterialHeightEqualTo(Double value) {
            addCriterion("materialHeight =", value, "materialHeight");
            return (Criteria) this;
        }

        public Criteria andMaterialHeightNotEqualTo(Double value) {
            addCriterion("materialHeight <>", value, "materialHeight");
            return (Criteria) this;
        }

        public Criteria andMaterialHeightGreaterThan(Double value) {
            addCriterion("materialHeight >", value, "materialHeight");
            return (Criteria) this;
        }

        public Criteria andMaterialHeightGreaterThanOrEqualTo(Double value) {
            addCriterion("materialHeight >=", value, "materialHeight");
            return (Criteria) this;
        }

        public Criteria andMaterialHeightLessThan(Double value) {
            addCriterion("materialHeight <", value, "materialHeight");
            return (Criteria) this;
        }

        public Criteria andMaterialHeightLessThanOrEqualTo(Double value) {
            addCriterion("materialHeight <=", value, "materialHeight");
            return (Criteria) this;
        }

        public Criteria andMaterialHeightIn(List<Double> values) {
            addCriterion("materialHeight in", values, "materialHeight");
            return (Criteria) this;
        }

        public Criteria andMaterialHeightNotIn(List<Double> values) {
            addCriterion("materialHeight not in", values, "materialHeight");
            return (Criteria) this;
        }

        public Criteria andMaterialHeightBetween(Double value1, Double value2) {
            addCriterion("materialHeight between", value1, value2, "materialHeight");
            return (Criteria) this;
        }

        public Criteria andMaterialHeightNotBetween(Double value1, Double value2) {
            addCriterion("materialHeight not between", value1, value2, "materialHeight");
            return (Criteria) this;
        }

        public Criteria andMaterialMaxStoreIsNull() {
            addCriterion("materialMaxStore is null");
            return (Criteria) this;
        }

        public Criteria andMaterialMaxStoreIsNotNull() {
            addCriterion("materialMaxStore is not null");
            return (Criteria) this;
        }

        public Criteria andMaterialMaxStoreEqualTo(Integer value) {
            addCriterion("materialMaxStore =", value, "materialMaxStore");
            return (Criteria) this;
        }

        public Criteria andMaterialMaxStoreNotEqualTo(Integer value) {
            addCriterion("materialMaxStore <>", value, "materialMaxStore");
            return (Criteria) this;
        }

        public Criteria andMaterialMaxStoreGreaterThan(Integer value) {
            addCriterion("materialMaxStore >", value, "materialMaxStore");
            return (Criteria) this;
        }

        public Criteria andMaterialMaxStoreGreaterThanOrEqualTo(Integer value) {
            addCriterion("materialMaxStore >=", value, "materialMaxStore");
            return (Criteria) this;
        }

        public Criteria andMaterialMaxStoreLessThan(Integer value) {
            addCriterion("materialMaxStore <", value, "materialMaxStore");
            return (Criteria) this;
        }

        public Criteria andMaterialMaxStoreLessThanOrEqualTo(Integer value) {
            addCriterion("materialMaxStore <=", value, "materialMaxStore");
            return (Criteria) this;
        }

        public Criteria andMaterialMaxStoreIn(List<Integer> values) {
            addCriterion("materialMaxStore in", values, "materialMaxStore");
            return (Criteria) this;
        }

        public Criteria andMaterialMaxStoreNotIn(List<Integer> values) {
            addCriterion("materialMaxStore not in", values, "materialMaxStore");
            return (Criteria) this;
        }

        public Criteria andMaterialMaxStoreBetween(Integer value1, Integer value2) {
            addCriterion("materialMaxStore between", value1, value2, "materialMaxStore");
            return (Criteria) this;
        }

        public Criteria andMaterialMaxStoreNotBetween(Integer value1, Integer value2) {
            addCriterion("materialMaxStore not between", value1, value2, "materialMaxStore");
            return (Criteria) this;
        }

        public Criteria andCargoLocationTypeIdIsNull() {
            addCriterion("cargoLocationTypeId is null");
            return (Criteria) this;
        }

        public Criteria andCargoLocationTypeIdIsNotNull() {
            addCriterion("cargoLocationTypeId is not null");
            return (Criteria) this;
        }

        public Criteria andCargoLocationTypeIdEqualTo(Integer value) {
            addCriterion("cargoLocationTypeId =", value, "cargoLocationTypeId");
            return (Criteria) this;
        }

        public Criteria andCargoLocationTypeIdNotEqualTo(Integer value) {
            addCriterion("cargoLocationTypeId <>", value, "cargoLocationTypeId");
            return (Criteria) this;
        }

        public Criteria andCargoLocationTypeIdGreaterThan(Integer value) {
            addCriterion("cargoLocationTypeId >", value, "cargoLocationTypeId");
            return (Criteria) this;
        }

        public Criteria andCargoLocationTypeIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("cargoLocationTypeId >=", value, "cargoLocationTypeId");
            return (Criteria) this;
        }

        public Criteria andCargoLocationTypeIdLessThan(Integer value) {
            addCriterion("cargoLocationTypeId <", value, "cargoLocationTypeId");
            return (Criteria) this;
        }

        public Criteria andCargoLocationTypeIdLessThanOrEqualTo(Integer value) {
            addCriterion("cargoLocationTypeId <=", value, "cargoLocationTypeId");
            return (Criteria) this;
        }

        public Criteria andCargoLocationTypeIdIn(List<Integer> values) {
            addCriterion("cargoLocationTypeId in", values, "cargoLocationTypeId");
            return (Criteria) this;
        }

        public Criteria andCargoLocationTypeIdNotIn(List<Integer> values) {
            addCriterion("cargoLocationTypeId not in", values, "cargoLocationTypeId");
            return (Criteria) this;
        }

        public Criteria andCargoLocationTypeIdBetween(Integer value1, Integer value2) {
            addCriterion("cargoLocationTypeId between", value1, value2, "cargoLocationTypeId");
            return (Criteria) this;
        }

        public Criteria andCargoLocationTypeIdNotBetween(Integer value1, Integer value2) {
            addCriterion("cargoLocationTypeId not between", value1, value2, "cargoLocationTypeId");
            return (Criteria) this;
        }

        public Criteria andCargoLocationTypeCodeIsNull() {
            addCriterion("cargoLocationTypeCode is null");
            return (Criteria) this;
        }

        public Criteria andCargoLocationTypeCodeIsNotNull() {
            addCriterion("cargoLocationTypeCode is not null");
            return (Criteria) this;
        }

        public Criteria andCargoLocationTypeCodeEqualTo(String value) {
            addCriterion("cargoLocationTypeCode =", value, "cargoLocationTypeCode");
            return (Criteria) this;
        }

        public Criteria andCargoLocationTypeCodeNotEqualTo(String value) {
            addCriterion("cargoLocationTypeCode <>", value, "cargoLocationTypeCode");
            return (Criteria) this;
        }

        public Criteria andCargoLocationTypeCodeGreaterThan(String value) {
            addCriterion("cargoLocationTypeCode >", value, "cargoLocationTypeCode");
            return (Criteria) this;
        }

        public Criteria andCargoLocationTypeCodeGreaterThanOrEqualTo(String value) {
            addCriterion("cargoLocationTypeCode >=", value, "cargoLocationTypeCode");
            return (Criteria) this;
        }

        public Criteria andCargoLocationTypeCodeLessThan(String value) {
            addCriterion("cargoLocationTypeCode <", value, "cargoLocationTypeCode");
            return (Criteria) this;
        }

        public Criteria andCargoLocationTypeCodeLessThanOrEqualTo(String value) {
            addCriterion("cargoLocationTypeCode <=", value, "cargoLocationTypeCode");
            return (Criteria) this;
        }

        public Criteria andCargoLocationTypeCodeLike(String value) {
            addCriterion("cargoLocationTypeCode like", value, "cargoLocationTypeCode");
            return (Criteria) this;
        }

        public Criteria andCargoLocationTypeCodeNotLike(String value) {
            addCriterion("cargoLocationTypeCode not like", value, "cargoLocationTypeCode");
            return (Criteria) this;
        }

        public Criteria andCargoLocationTypeCodeIn(List<String> values) {
            addCriterion("cargoLocationTypeCode in", values, "cargoLocationTypeCode");
            return (Criteria) this;
        }

        public Criteria andCargoLocationTypeCodeNotIn(List<String> values) {
            addCriterion("cargoLocationTypeCode not in", values, "cargoLocationTypeCode");
            return (Criteria) this;
        }

        public Criteria andCargoLocationTypeCodeBetween(String value1, String value2) {
            addCriterion("cargoLocationTypeCode between", value1, value2, "cargoLocationTypeCode");
            return (Criteria) this;
        }

        public Criteria andCargoLocationTypeCodeNotBetween(String value1, String value2) {
            addCriterion("cargoLocationTypeCode not between", value1, value2, "cargoLocationTypeCode");
            return (Criteria) this;
        }

        public Criteria andCargoLocationTypeCanUseCountIsNull() {
            addCriterion("cargoLocationTypeCanUseCount is null");
            return (Criteria) this;
        }

        public Criteria andCargoLocationTypeCanUseCountIsNotNull() {
            addCriterion("cargoLocationTypeCanUseCount is not null");
            return (Criteria) this;
        }

        public Criteria andCargoLocationTypeCanUseCountEqualTo(Integer value) {
            addCriterion("cargoLocationTypeCanUseCount =", value, "cargoLocationTypeCanUseCount");
            return (Criteria) this;
        }

        public Criteria andCargoLocationTypeCanUseCountNotEqualTo(Integer value) {
            addCriterion("cargoLocationTypeCanUseCount <>", value, "cargoLocationTypeCanUseCount");
            return (Criteria) this;
        }

        public Criteria andCargoLocationTypeCanUseCountGreaterThan(Integer value) {
            addCriterion("cargoLocationTypeCanUseCount >", value, "cargoLocationTypeCanUseCount");
            return (Criteria) this;
        }

        public Criteria andCargoLocationTypeCanUseCountGreaterThanOrEqualTo(Integer value) {
            addCriterion("cargoLocationTypeCanUseCount >=", value, "cargoLocationTypeCanUseCount");
            return (Criteria) this;
        }

        public Criteria andCargoLocationTypeCanUseCountLessThan(Integer value) {
            addCriterion("cargoLocationTypeCanUseCount <", value, "cargoLocationTypeCanUseCount");
            return (Criteria) this;
        }

        public Criteria andCargoLocationTypeCanUseCountLessThanOrEqualTo(Integer value) {
            addCriterion("cargoLocationTypeCanUseCount <=", value, "cargoLocationTypeCanUseCount");
            return (Criteria) this;
        }

        public Criteria andCargoLocationTypeCanUseCountIn(List<Integer> values) {
            addCriterion("cargoLocationTypeCanUseCount in", values, "cargoLocationTypeCanUseCount");
            return (Criteria) this;
        }

        public Criteria andCargoLocationTypeCanUseCountNotIn(List<Integer> values) {
            addCriterion("cargoLocationTypeCanUseCount not in", values, "cargoLocationTypeCanUseCount");
            return (Criteria) this;
        }

        public Criteria andCargoLocationTypeCanUseCountBetween(Integer value1, Integer value2) {
            addCriterion("cargoLocationTypeCanUseCount between", value1, value2, "cargoLocationTypeCanUseCount");
            return (Criteria) this;
        }

        public Criteria andCargoLocationTypeCanUseCountNotBetween(Integer value1, Integer value2) {
            addCriterion("cargoLocationTypeCanUseCount not between", value1, value2, "cargoLocationTypeCanUseCount");
            return (Criteria) this;
        }

        public Criteria andCargoLocationTypeLengthIsNull() {
            addCriterion("cargoLocationTypeLength is null");
            return (Criteria) this;
        }

        public Criteria andCargoLocationTypeLengthIsNotNull() {
            addCriterion("cargoLocationTypeLength is not null");
            return (Criteria) this;
        }

        public Criteria andCargoLocationTypeLengthEqualTo(Double value) {
            addCriterion("cargoLocationTypeLength =", value, "cargoLocationTypeLength");
            return (Criteria) this;
        }

        public Criteria andCargoLocationTypeLengthNotEqualTo(Double value) {
            addCriterion("cargoLocationTypeLength <>", value, "cargoLocationTypeLength");
            return (Criteria) this;
        }

        public Criteria andCargoLocationTypeLengthGreaterThan(Double value) {
            addCriterion("cargoLocationTypeLength >", value, "cargoLocationTypeLength");
            return (Criteria) this;
        }

        public Criteria andCargoLocationTypeLengthGreaterThanOrEqualTo(Double value) {
            addCriterion("cargoLocationTypeLength >=", value, "cargoLocationTypeLength");
            return (Criteria) this;
        }

        public Criteria andCargoLocationTypeLengthLessThan(Double value) {
            addCriterion("cargoLocationTypeLength <", value, "cargoLocationTypeLength");
            return (Criteria) this;
        }

        public Criteria andCargoLocationTypeLengthLessThanOrEqualTo(Double value) {
            addCriterion("cargoLocationTypeLength <=", value, "cargoLocationTypeLength");
            return (Criteria) this;
        }

        public Criteria andCargoLocationTypeLengthIn(List<Double> values) {
            addCriterion("cargoLocationTypeLength in", values, "cargoLocationTypeLength");
            return (Criteria) this;
        }

        public Criteria andCargoLocationTypeLengthNotIn(List<Double> values) {
            addCriterion("cargoLocationTypeLength not in", values, "cargoLocationTypeLength");
            return (Criteria) this;
        }

        public Criteria andCargoLocationTypeLengthBetween(Double value1, Double value2) {
            addCriterion("cargoLocationTypeLength between", value1, value2, "cargoLocationTypeLength");
            return (Criteria) this;
        }

        public Criteria andCargoLocationTypeLengthNotBetween(Double value1, Double value2) {
            addCriterion("cargoLocationTypeLength not between", value1, value2, "cargoLocationTypeLength");
            return (Criteria) this;
        }

        public Criteria andCargoLocationTypeWidthIsNull() {
            addCriterion("cargoLocationTypeWidth is null");
            return (Criteria) this;
        }

        public Criteria andCargoLocationTypeWidthIsNotNull() {
            addCriterion("cargoLocationTypeWidth is not null");
            return (Criteria) this;
        }

        public Criteria andCargoLocationTypeWidthEqualTo(Double value) {
            addCriterion("cargoLocationTypeWidth =", value, "cargoLocationTypeWidth");
            return (Criteria) this;
        }

        public Criteria andCargoLocationTypeWidthNotEqualTo(Double value) {
            addCriterion("cargoLocationTypeWidth <>", value, "cargoLocationTypeWidth");
            return (Criteria) this;
        }

        public Criteria andCargoLocationTypeWidthGreaterThan(Double value) {
            addCriterion("cargoLocationTypeWidth >", value, "cargoLocationTypeWidth");
            return (Criteria) this;
        }

        public Criteria andCargoLocationTypeWidthGreaterThanOrEqualTo(Double value) {
            addCriterion("cargoLocationTypeWidth >=", value, "cargoLocationTypeWidth");
            return (Criteria) this;
        }

        public Criteria andCargoLocationTypeWidthLessThan(Double value) {
            addCriterion("cargoLocationTypeWidth <", value, "cargoLocationTypeWidth");
            return (Criteria) this;
        }

        public Criteria andCargoLocationTypeWidthLessThanOrEqualTo(Double value) {
            addCriterion("cargoLocationTypeWidth <=", value, "cargoLocationTypeWidth");
            return (Criteria) this;
        }

        public Criteria andCargoLocationTypeWidthIn(List<Double> values) {
            addCriterion("cargoLocationTypeWidth in", values, "cargoLocationTypeWidth");
            return (Criteria) this;
        }

        public Criteria andCargoLocationTypeWidthNotIn(List<Double> values) {
            addCriterion("cargoLocationTypeWidth not in", values, "cargoLocationTypeWidth");
            return (Criteria) this;
        }

        public Criteria andCargoLocationTypeWidthBetween(Double value1, Double value2) {
            addCriterion("cargoLocationTypeWidth between", value1, value2, "cargoLocationTypeWidth");
            return (Criteria) this;
        }

        public Criteria andCargoLocationTypeWidthNotBetween(Double value1, Double value2) {
            addCriterion("cargoLocationTypeWidth not between", value1, value2, "cargoLocationTypeWidth");
            return (Criteria) this;
        }

        public Criteria andCargoLocationTypeHeightIsNull() {
            addCriterion("cargoLocationTypeHeight is null");
            return (Criteria) this;
        }

        public Criteria andCargoLocationTypeHeightIsNotNull() {
            addCriterion("cargoLocationTypeHeight is not null");
            return (Criteria) this;
        }

        public Criteria andCargoLocationTypeHeightEqualTo(Double value) {
            addCriterion("cargoLocationTypeHeight =", value, "cargoLocationTypeHeight");
            return (Criteria) this;
        }

        public Criteria andCargoLocationTypeHeightNotEqualTo(Double value) {
            addCriterion("cargoLocationTypeHeight <>", value, "cargoLocationTypeHeight");
            return (Criteria) this;
        }

        public Criteria andCargoLocationTypeHeightGreaterThan(Double value) {
            addCriterion("cargoLocationTypeHeight >", value, "cargoLocationTypeHeight");
            return (Criteria) this;
        }

        public Criteria andCargoLocationTypeHeightGreaterThanOrEqualTo(Double value) {
            addCriterion("cargoLocationTypeHeight >=", value, "cargoLocationTypeHeight");
            return (Criteria) this;
        }

        public Criteria andCargoLocationTypeHeightLessThan(Double value) {
            addCriterion("cargoLocationTypeHeight <", value, "cargoLocationTypeHeight");
            return (Criteria) this;
        }

        public Criteria andCargoLocationTypeHeightLessThanOrEqualTo(Double value) {
            addCriterion("cargoLocationTypeHeight <=", value, "cargoLocationTypeHeight");
            return (Criteria) this;
        }

        public Criteria andCargoLocationTypeHeightIn(List<Double> values) {
            addCriterion("cargoLocationTypeHeight in", values, "cargoLocationTypeHeight");
            return (Criteria) this;
        }

        public Criteria andCargoLocationTypeHeightNotIn(List<Double> values) {
            addCriterion("cargoLocationTypeHeight not in", values, "cargoLocationTypeHeight");
            return (Criteria) this;
        }

        public Criteria andCargoLocationTypeHeightBetween(Double value1, Double value2) {
            addCriterion("cargoLocationTypeHeight between", value1, value2, "cargoLocationTypeHeight");
            return (Criteria) this;
        }

        public Criteria andCargoLocationTypeHeightNotBetween(Double value1, Double value2) {
            addCriterion("cargoLocationTypeHeight not between", value1, value2, "cargoLocationTypeHeight");
            return (Criteria) this;
        }

        public Criteria andCargoLocationTypeExtendIsNull() {
            addCriterion("cargoLocationTypeExtend is null");
            return (Criteria) this;
        }

        public Criteria andCargoLocationTypeExtendIsNotNull() {
            addCriterion("cargoLocationTypeExtend is not null");
            return (Criteria) this;
        }

        public Criteria andCargoLocationTypeExtendEqualTo(Boolean value) {
            addCriterion("cargoLocationTypeExtend =", value, "cargoLocationTypeExtend");
            return (Criteria) this;
        }

        public Criteria andCargoLocationTypeExtendNotEqualTo(Boolean value) {
            addCriterion("cargoLocationTypeExtend <>", value, "cargoLocationTypeExtend");
            return (Criteria) this;
        }

        public Criteria andCargoLocationTypeExtendGreaterThan(Boolean value) {
            addCriterion("cargoLocationTypeExtend >", value, "cargoLocationTypeExtend");
            return (Criteria) this;
        }

        public Criteria andCargoLocationTypeExtendGreaterThanOrEqualTo(Boolean value) {
            addCriterion("cargoLocationTypeExtend >=", value, "cargoLocationTypeExtend");
            return (Criteria) this;
        }

        public Criteria andCargoLocationTypeExtendLessThan(Boolean value) {
            addCriterion("cargoLocationTypeExtend <", value, "cargoLocationTypeExtend");
            return (Criteria) this;
        }

        public Criteria andCargoLocationTypeExtendLessThanOrEqualTo(Boolean value) {
            addCriterion("cargoLocationTypeExtend <=", value, "cargoLocationTypeExtend");
            return (Criteria) this;
        }

        public Criteria andCargoLocationTypeExtendIn(List<Boolean> values) {
            addCriterion("cargoLocationTypeExtend in", values, "cargoLocationTypeExtend");
            return (Criteria) this;
        }

        public Criteria andCargoLocationTypeExtendNotIn(List<Boolean> values) {
            addCriterion("cargoLocationTypeExtend not in", values, "cargoLocationTypeExtend");
            return (Criteria) this;
        }

        public Criteria andCargoLocationTypeExtendBetween(Boolean value1, Boolean value2) {
            addCriterion("cargoLocationTypeExtend between", value1, value2, "cargoLocationTypeExtend");
            return (Criteria) this;
        }

        public Criteria andCargoLocationTypeExtendNotBetween(Boolean value1, Boolean value2) {
            addCriterion("cargoLocationTypeExtend not between", value1, value2, "cargoLocationTypeExtend");
            return (Criteria) this;
        }

        public Criteria andCargoLocationTypePalletIsNull() {
            addCriterion("cargoLocationTypePallet is null");
            return (Criteria) this;
        }

        public Criteria andCargoLocationTypePalletIsNotNull() {
            addCriterion("cargoLocationTypePallet is not null");
            return (Criteria) this;
        }

        public Criteria andCargoLocationTypePalletEqualTo(Boolean value) {
            addCriterion("cargoLocationTypePallet =", value, "cargoLocationTypePallet");
            return (Criteria) this;
        }

        public Criteria andCargoLocationTypePalletNotEqualTo(Boolean value) {
            addCriterion("cargoLocationTypePallet <>", value, "cargoLocationTypePallet");
            return (Criteria) this;
        }

        public Criteria andCargoLocationTypePalletGreaterThan(Boolean value) {
            addCriterion("cargoLocationTypePallet >", value, "cargoLocationTypePallet");
            return (Criteria) this;
        }

        public Criteria andCargoLocationTypePalletGreaterThanOrEqualTo(Boolean value) {
            addCriterion("cargoLocationTypePallet >=", value, "cargoLocationTypePallet");
            return (Criteria) this;
        }

        public Criteria andCargoLocationTypePalletLessThan(Boolean value) {
            addCriterion("cargoLocationTypePallet <", value, "cargoLocationTypePallet");
            return (Criteria) this;
        }

        public Criteria andCargoLocationTypePalletLessThanOrEqualTo(Boolean value) {
            addCriterion("cargoLocationTypePallet <=", value, "cargoLocationTypePallet");
            return (Criteria) this;
        }

        public Criteria andCargoLocationTypePalletIn(List<Boolean> values) {
            addCriterion("cargoLocationTypePallet in", values, "cargoLocationTypePallet");
            return (Criteria) this;
        }

        public Criteria andCargoLocationTypePalletNotIn(List<Boolean> values) {
            addCriterion("cargoLocationTypePallet not in", values, "cargoLocationTypePallet");
            return (Criteria) this;
        }

        public Criteria andCargoLocationTypePalletBetween(Boolean value1, Boolean value2) {
            addCriterion("cargoLocationTypePallet between", value1, value2, "cargoLocationTypePallet");
            return (Criteria) this;
        }

        public Criteria andCargoLocationTypePalletNotBetween(Boolean value1, Boolean value2) {
            addCriterion("cargoLocationTypePallet not between", value1, value2, "cargoLocationTypePallet");
            return (Criteria) this;
        }

        public Criteria andStoreCountIsNull() {
            addCriterion("storeCount is null");
            return (Criteria) this;
        }

        public Criteria andStoreCountIsNotNull() {
            addCriterion("storeCount is not null");
            return (Criteria) this;
        }

        public Criteria andStoreCountEqualTo(Integer value) {
            addCriterion("storeCount =", value, "storeCount");
            return (Criteria) this;
        }

        public Criteria andStoreCountNotEqualTo(Integer value) {
            addCriterion("storeCount <>", value, "storeCount");
            return (Criteria) this;
        }

        public Criteria andStoreCountGreaterThan(Integer value) {
            addCriterion("storeCount >", value, "storeCount");
            return (Criteria) this;
        }

        public Criteria andStoreCountGreaterThanOrEqualTo(Integer value) {
            addCriterion("storeCount >=", value, "storeCount");
            return (Criteria) this;
        }

        public Criteria andStoreCountLessThan(Integer value) {
            addCriterion("storeCount <", value, "storeCount");
            return (Criteria) this;
        }

        public Criteria andStoreCountLessThanOrEqualTo(Integer value) {
            addCriterion("storeCount <=", value, "storeCount");
            return (Criteria) this;
        }

        public Criteria andStoreCountIn(List<Integer> values) {
            addCriterion("storeCount in", values, "storeCount");
            return (Criteria) this;
        }

        public Criteria andStoreCountNotIn(List<Integer> values) {
            addCriterion("storeCount not in", values, "storeCount");
            return (Criteria) this;
        }

        public Criteria andStoreCountBetween(Integer value1, Integer value2) {
            addCriterion("storeCount between", value1, value2, "storeCount");
            return (Criteria) this;
        }

        public Criteria andStoreCountNotBetween(Integer value1, Integer value2) {
            addCriterion("storeCount not between", value1, value2, "storeCount");
            return (Criteria) this;
        }

        public Criteria andUsageRateIsNull() {
            addCriterion("usageRate is null");
            return (Criteria) this;
        }

        public Criteria andUsageRateIsNotNull() {
            addCriterion("usageRate is not null");
            return (Criteria) this;
        }

        public Criteria andUsageRateEqualTo(Double value) {
            addCriterion("usageRate =", value, "usageRate");
            return (Criteria) this;
        }

        public Criteria andUsageRateNotEqualTo(Double value) {
            addCriterion("usageRate <>", value, "usageRate");
            return (Criteria) this;
        }

        public Criteria andUsageRateGreaterThan(Double value) {
            addCriterion("usageRate >", value, "usageRate");
            return (Criteria) this;
        }

        public Criteria andUsageRateGreaterThanOrEqualTo(Double value) {
            addCriterion("usageRate >=", value, "usageRate");
            return (Criteria) this;
        }

        public Criteria andUsageRateLessThan(Double value) {
            addCriterion("usageRate <", value, "usageRate");
            return (Criteria) this;
        }

        public Criteria andUsageRateLessThanOrEqualTo(Double value) {
            addCriterion("usageRate <=", value, "usageRate");
            return (Criteria) this;
        }

        public Criteria andUsageRateIn(List<Double> values) {
            addCriterion("usageRate in", values, "usageRate");
            return (Criteria) this;
        }

        public Criteria andUsageRateNotIn(List<Double> values) {
            addCriterion("usageRate not in", values, "usageRate");
            return (Criteria) this;
        }

        public Criteria andUsageRateBetween(Double value1, Double value2) {
            addCriterion("usageRate between", value1, value2, "usageRate");
            return (Criteria) this;
        }

        public Criteria andUsageRateNotBetween(Double value1, Double value2) {
            addCriterion("usageRate not between", value1, value2, "usageRate");
            return (Criteria) this;
        }

        public Criteria andCargoLocationTypeVolumeIsNull() {
            addCriterion("cargoLocationTypeVolume is null");
            return (Criteria) this;
        }

        public Criteria andCargoLocationTypeVolumeIsNotNull() {
            addCriterion("cargoLocationTypeVolume is not null");
            return (Criteria) this;
        }

        public Criteria andCargoLocationTypeVolumeEqualTo(Double value) {
            addCriterion("cargoLocationTypeVolume =", value, "cargoLocationTypeVolume");
            return (Criteria) this;
        }

        public Criteria andCargoLocationTypeVolumeNotEqualTo(Double value) {
            addCriterion("cargoLocationTypeVolume <>", value, "cargoLocationTypeVolume");
            return (Criteria) this;
        }

        public Criteria andCargoLocationTypeVolumeGreaterThan(Double value) {
            addCriterion("cargoLocationTypeVolume >", value, "cargoLocationTypeVolume");
            return (Criteria) this;
        }

        public Criteria andCargoLocationTypeVolumeGreaterThanOrEqualTo(Double value) {
            addCriterion("cargoLocationTypeVolume >=", value, "cargoLocationTypeVolume");
            return (Criteria) this;
        }

        public Criteria andCargoLocationTypeVolumeLessThan(Double value) {
            addCriterion("cargoLocationTypeVolume <", value, "cargoLocationTypeVolume");
            return (Criteria) this;
        }

        public Criteria andCargoLocationTypeVolumeLessThanOrEqualTo(Double value) {
            addCriterion("cargoLocationTypeVolume <=", value, "cargoLocationTypeVolume");
            return (Criteria) this;
        }

        public Criteria andCargoLocationTypeVolumeIn(List<Double> values) {
            addCriterion("cargoLocationTypeVolume in", values, "cargoLocationTypeVolume");
            return (Criteria) this;
        }

        public Criteria andCargoLocationTypeVolumeNotIn(List<Double> values) {
            addCriterion("cargoLocationTypeVolume not in", values, "cargoLocationTypeVolume");
            return (Criteria) this;
        }

        public Criteria andCargoLocationTypeVolumeBetween(Double value1, Double value2) {
            addCriterion("cargoLocationTypeVolume between", value1, value2, "cargoLocationTypeVolume");
            return (Criteria) this;
        }

        public Criteria andCargoLocationTypeVolumeNotBetween(Double value1, Double value2) {
            addCriterion("cargoLocationTypeVolume not between", value1, value2, "cargoLocationTypeVolume");
            return (Criteria) this;
        }

        public Criteria andPlacementIsNull() {
            addCriterion("placement is null");
            return (Criteria) this;
        }

        public Criteria andPlacementIsNotNull() {
            addCriterion("placement is not null");
            return (Criteria) this;
        }

        public Criteria andPlacementEqualTo(String value) {
            addCriterion("placement =", value, "placement");
            return (Criteria) this;
        }

        public Criteria andPlacementNotEqualTo(String value) {
            addCriterion("placement <>", value, "placement");
            return (Criteria) this;
        }

        public Criteria andPlacementGreaterThan(String value) {
            addCriterion("placement >", value, "placement");
            return (Criteria) this;
        }

        public Criteria andPlacementGreaterThanOrEqualTo(String value) {
            addCriterion("placement >=", value, "placement");
            return (Criteria) this;
        }

        public Criteria andPlacementLessThan(String value) {
            addCriterion("placement <", value, "placement");
            return (Criteria) this;
        }

        public Criteria andPlacementLessThanOrEqualTo(String value) {
            addCriterion("placement <=", value, "placement");
            return (Criteria) this;
        }

        public Criteria andPlacementLike(String value) {
            addCriterion("placement like", value, "placement");
            return (Criteria) this;
        }

        public Criteria andPlacementNotLike(String value) {
            addCriterion("placement not like", value, "placement");
            return (Criteria) this;
        }

        public Criteria andPlacementIn(List<String> values) {
            addCriterion("placement in", values, "placement");
            return (Criteria) this;
        }

        public Criteria andPlacementNotIn(List<String> values) {
            addCriterion("placement not in", values, "placement");
            return (Criteria) this;
        }

        public Criteria andPlacementBetween(String value1, String value2) {
            addCriterion("placement between", value1, value2, "placement");
            return (Criteria) this;
        }

        public Criteria andPlacementNotBetween(String value1, String value2) {
            addCriterion("placement not between", value1, value2, "placement");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table Material_CargoLocationType_Data
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table Material_CargoLocationType_Data
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }
    }
}