package com.dhl.tools.domain;

import java.io.Serializable;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table RecommendedLocation
 *
 * @mbg.generated do_not_delete_during_merge Sat Apr 15 16:39:20 CST 2017
 */
public class RecommendedLocation implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table RecommendedLocation
     *
     * @mbg.generated Sat Apr 15 16:39:20 CST 2017
     */
    private static final long serialVersionUID = 1L;
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RecommendedLocation.id
     *
     * @mbg.generated Sat Apr 15 16:39:20 CST 2017
     */
    private Integer id;
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RecommendedLocation.materialId
     *
     * @mbg.generated Sat Apr 15 16:39:20 CST 2017
     */
    private Integer materialId;
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RecommendedLocation.cargoLocationId
     *
     * @mbg.generated Sat Apr 15 16:39:20 CST 2017
     */
    private Integer cargoLocationId;
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RecommendedLocation.cargoLocationTypeId
     *
     * @mbg.generated Sat Apr 15 16:39:20 CST 2017
     */
    private Integer cargoLocationTypeId;
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RecommendedLocation.pickingFrequency
     *
     * @mbg.generated Sat Apr 15 16:39:20 CST 2017
     */
    private Integer pickingFrequency;
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RecommendedLocation.cargoLocationScore
     *
     * @mbg.generated Sat Apr 15 16:39:20 CST 2017
     */
    private Integer cargoLocationScore;
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RecommendedLocation.recommendedCargoLocationId
     *
     * @mbg.generated Sat Apr 15 16:39:20 CST 2017
     */
    private Integer recommendedCargoLocationId;
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RecommendedLocation.recommendedCargoLocationScore
     *
     * @mbg.generated Sat Apr 15 16:39:20 CST 2017
     */
    private Integer recommendedCargoLocationScore;
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RecommendedLocation.optimizationRecommend
     *
     * @mbg.generated Sat Apr 15 16:39:20 CST 2017
     */
    private Integer optimizationRecommend;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RecommendedLocation.id
     *
     * @return the value of RecommendedLocation.id
     *
     * @mbg.generated Sat Apr 15 16:39:20 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RecommendedLocation.id
     *
     * @param id the value for RecommendedLocation.id
     *
     * @mbg.generated Sat Apr 15 16:39:20 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RecommendedLocation.materialId
     *
     * @return the value of RecommendedLocation.materialId
     *
     * @mbg.generated Sat Apr 15 16:39:20 CST 2017
     */
    public Integer getMaterialId() {
        return materialId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RecommendedLocation.materialId
     *
     * @param materialId the value for RecommendedLocation.materialId
     *
     * @mbg.generated Sat Apr 15 16:39:20 CST 2017
     */
    public void setMaterialId(Integer materialId) {
        this.materialId = materialId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RecommendedLocation.cargoLocationId
     *
     * @return the value of RecommendedLocation.cargoLocationId
     *
     * @mbg.generated Sat Apr 15 16:39:20 CST 2017
     */
    public Integer getCargoLocationId() {
        return cargoLocationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RecommendedLocation.cargoLocationId
     *
     * @param cargoLocationId the value for RecommendedLocation.cargoLocationId
     *
     * @mbg.generated Sat Apr 15 16:39:20 CST 2017
     */
    public void setCargoLocationId(Integer cargoLocationId) {
        this.cargoLocationId = cargoLocationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RecommendedLocation.cargoLocationTypeId
     *
     * @return the value of RecommendedLocation.cargoLocationTypeId
     *
     * @mbg.generated Sat Apr 15 16:39:20 CST 2017
     */
    public Integer getCargoLocationTypeId() {
        return cargoLocationTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RecommendedLocation.cargoLocationTypeId
     *
     * @param cargoLocationTypeId the value for RecommendedLocation.cargoLocationTypeId
     *
     * @mbg.generated Sat Apr 15 16:39:20 CST 2017
     */
    public void setCargoLocationTypeId(Integer cargoLocationTypeId) {
        this.cargoLocationTypeId = cargoLocationTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RecommendedLocation.pickingFrequency
     *
     * @return the value of RecommendedLocation.pickingFrequency
     *
     * @mbg.generated Sat Apr 15 16:39:20 CST 2017
     */
    public Integer getPickingFrequency() {
        return pickingFrequency;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RecommendedLocation.pickingFrequency
     *
     * @param pickingFrequency the value for RecommendedLocation.pickingFrequency
     *
     * @mbg.generated Sat Apr 15 16:39:20 CST 2017
     */
    public void setPickingFrequency(Integer pickingFrequency) {
        this.pickingFrequency = pickingFrequency;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RecommendedLocation.cargoLocationScore
     *
     * @return the value of RecommendedLocation.cargoLocationScore
     *
     * @mbg.generated Sat Apr 15 16:39:20 CST 2017
     */
    public Integer getCargoLocationScore() {
        return cargoLocationScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RecommendedLocation.cargoLocationScore
     *
     * @param cargoLocationScore the value for RecommendedLocation.cargoLocationScore
     *
     * @mbg.generated Sat Apr 15 16:39:20 CST 2017
     */
    public void setCargoLocationScore(Integer cargoLocationScore) {
        this.cargoLocationScore = cargoLocationScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RecommendedLocation.recommendedCargoLocationId
     *
     * @return the value of RecommendedLocation.recommendedCargoLocationId
     *
     * @mbg.generated Sat Apr 15 16:39:20 CST 2017
     */
    public Integer getRecommendedCargoLocationId() {
        return recommendedCargoLocationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RecommendedLocation.recommendedCargoLocationId
     *
     * @param recommendedCargoLocationId the value for RecommendedLocation.recommendedCargoLocationId
     *
     * @mbg.generated Sat Apr 15 16:39:20 CST 2017
     */
    public void setRecommendedCargoLocationId(Integer recommendedCargoLocationId) {
        this.recommendedCargoLocationId = recommendedCargoLocationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RecommendedLocation.recommendedCargoLocationScore
     *
     * @return the value of RecommendedLocation.recommendedCargoLocationScore
     *
     * @mbg.generated Sat Apr 15 16:39:20 CST 2017
     */
    public Integer getRecommendedCargoLocationScore() {
        return recommendedCargoLocationScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RecommendedLocation.recommendedCargoLocationScore
     *
     * @param recommendedCargoLocationScore the value for RecommendedLocation.recommendedCargoLocationScore
     *
     * @mbg.generated Sat Apr 15 16:39:20 CST 2017
     */
    public void setRecommendedCargoLocationScore(Integer recommendedCargoLocationScore) {
        this.recommendedCargoLocationScore = recommendedCargoLocationScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RecommendedLocation.optimizationRecommend
     *
     * @return the value of RecommendedLocation.optimizationRecommend
     *
     * @mbg.generated Sat Apr 15 16:39:20 CST 2017
     */
    public Integer getOptimizationRecommend() {
        return optimizationRecommend;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RecommendedLocation.optimizationRecommend
     *
     * @param optimizationRecommend the value for RecommendedLocation.optimizationRecommend
     *
     * @mbg.generated Sat Apr 15 16:39:20 CST 2017
     */
    public void setOptimizationRecommend(Integer optimizationRecommend) {
        this.optimizationRecommend = optimizationRecommend;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RecommendedLocation
     *
     * @mbg.generated Sat Apr 15 16:39:20 CST 2017
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", materialId=").append(materialId);
        sb.append(", cargoLocationId=").append(cargoLocationId);
        sb.append(", cargoLocationTypeId=").append(cargoLocationTypeId);
        sb.append(", pickingFrequency=").append(pickingFrequency);
        sb.append(", cargoLocationScore=").append(cargoLocationScore);
        sb.append(", recommendedCargoLocationId=").append(recommendedCargoLocationId);
        sb.append(", recommendedCargoLocationScore=").append(recommendedCargoLocationScore);
        sb.append(", optimizationRecommend=").append(optimizationRecommend);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}