package com.dhl.tools.domain;

import java.io.Serializable;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table RoleInfo_AuthorityInfo
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class RoleInfoAuthorityInfo implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RoleInfo_AuthorityInfo.roleId
     *
     * @mbg.generated
     */
    private Integer roleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RoleInfo_AuthorityInfo.authorityId
     *
     * @mbg.generated
     */
    private Integer authorityId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table RoleInfo_AuthorityInfo
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RoleInfo_AuthorityInfo.roleId
     *
     * @return the value of RoleInfo_AuthorityInfo.roleId
     *
     * @mbg.generated
     */
    public Integer getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RoleInfo_AuthorityInfo.roleId
     *
     * @param roleId the value for RoleInfo_AuthorityInfo.roleId
     *
     * @mbg.generated
     */
    public void setRoleId(Integer roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RoleInfo_AuthorityInfo.authorityId
     *
     * @return the value of RoleInfo_AuthorityInfo.authorityId
     *
     * @mbg.generated
     */
    public Integer getAuthorityId() {
        return authorityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RoleInfo_AuthorityInfo.authorityId
     *
     * @param authorityId the value for RoleInfo_AuthorityInfo.authorityId
     *
     * @mbg.generated
     */
    public void setAuthorityId(Integer authorityId) {
        this.authorityId = authorityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RoleInfo_AuthorityInfo
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", roleId=").append(roleId);
        sb.append(", authorityId=").append(authorityId);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}