package com.dhl.tools.domain;

import java.io.Serializable;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table RoleInfo_WareHouse
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class RoleInfoWareHouse implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RoleInfo_WareHouse.roleId
     *
     * @mbg.generated
     */
    private Integer roleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RoleInfo_WareHouse.wareHouseId
     *
     * @mbg.generated
     */
    private Integer wareHouseId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table RoleInfo_WareHouse
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RoleInfo_WareHouse.roleId
     *
     * @return the value of RoleInfo_WareHouse.roleId
     *
     * @mbg.generated
     */
    public Integer getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RoleInfo_WareHouse.roleId
     *
     * @param roleId the value for RoleInfo_WareHouse.roleId
     *
     * @mbg.generated
     */
    public void setRoleId(Integer roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RoleInfo_WareHouse.wareHouseId
     *
     * @return the value of RoleInfo_WareHouse.wareHouseId
     *
     * @mbg.generated
     */
    public Integer getWareHouseId() {
        return wareHouseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RoleInfo_WareHouse.wareHouseId
     *
     * @param wareHouseId the value for RoleInfo_WareHouse.wareHouseId
     *
     * @mbg.generated
     */
    public void setWareHouseId(Integer wareHouseId) {
        this.wareHouseId = wareHouseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RoleInfo_WareHouse
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", roleId=").append(roleId);
        sb.append(", wareHouseId=").append(wareHouseId);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}