package com.dhl.tools.domain;

import java.io.Serializable;
import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table WareHouse
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class WareHouse implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WareHouse.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WareHouse.code
     *
     * @mbg.generated
     */
    private String code;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WareHouse.fullCodeLength
     *
     * @mbg.generated
     */
    private Integer fullCodeLength;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WareHouse.stallType
     *
     * @mbg.generated
     */
    private String stallType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WareHouse.personDrivingSpeed
     *
     * @mbg.generated
     */
    private Double personDrivingSpeed;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WareHouse.forkliftDrivingSpeed
     *
     * @mbg.generated
     */
    private Double forkliftDrivingSpeed;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WareHouse.pickTruckDrivingSpeed
     *
     * @mbg.generated
     */
    private Double pickTruckDrivingSpeed;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WareHouse.personPickUpSpeed
     *
     * @mbg.generated
     */
    private Double personPickUpSpeed;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WareHouse.forkliftPickUpSpeed
     *
     * @mbg.generated
     */
    private Double forkliftPickUpSpeed;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WareHouse.pickTuckPickUpSpeed
     *
     * @mbg.generated
     */
    private Double pickTuckPickUpSpeed;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WareHouse.createBy
     *
     * @mbg.generated
     */
    private String createBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WareHouse.createDate
     *
     * @mbg.generated
     */
    private Date createDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WareHouse.lastModifiedBy
     *
     * @mbg.generated
     */
    private String lastModifiedBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WareHouse.lastModifiedDate
     *
     * @mbg.generated
     */
    private Date lastModifiedDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table WareHouse
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WareHouse.id
     *
     * @return the value of WareHouse.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WareHouse.id
     *
     * @param id the value for WareHouse.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WareHouse.code
     *
     * @return the value of WareHouse.code
     *
     * @mbg.generated
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WareHouse.code
     *
     * @param code the value for WareHouse.code
     *
     * @mbg.generated
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WareHouse.fullCodeLength
     *
     * @return the value of WareHouse.fullCodeLength
     *
     * @mbg.generated
     */
    public Integer getFullCodeLength() {
        return fullCodeLength;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WareHouse.fullCodeLength
     *
     * @param fullCodeLength the value for WareHouse.fullCodeLength
     *
     * @mbg.generated
     */
    public void setFullCodeLength(Integer fullCodeLength) {
        this.fullCodeLength = fullCodeLength;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WareHouse.stallType
     *
     * @return the value of WareHouse.stallType
     *
     * @mbg.generated
     */
    public String getStallType() {
        return stallType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WareHouse.stallType
     *
     * @param stallType the value for WareHouse.stallType
     *
     * @mbg.generated
     */
    public void setStallType(String stallType) {
        this.stallType = stallType == null ? null : stallType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WareHouse.personDrivingSpeed
     *
     * @return the value of WareHouse.personDrivingSpeed
     *
     * @mbg.generated
     */
    public Double getPersonDrivingSpeed() {
        return personDrivingSpeed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WareHouse.personDrivingSpeed
     *
     * @param personDrivingSpeed the value for WareHouse.personDrivingSpeed
     *
     * @mbg.generated
     */
    public void setPersonDrivingSpeed(Double personDrivingSpeed) {
        this.personDrivingSpeed = personDrivingSpeed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WareHouse.forkliftDrivingSpeed
     *
     * @return the value of WareHouse.forkliftDrivingSpeed
     *
     * @mbg.generated
     */
    public Double getForkliftDrivingSpeed() {
        return forkliftDrivingSpeed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WareHouse.forkliftDrivingSpeed
     *
     * @param forkliftDrivingSpeed the value for WareHouse.forkliftDrivingSpeed
     *
     * @mbg.generated
     */
    public void setForkliftDrivingSpeed(Double forkliftDrivingSpeed) {
        this.forkliftDrivingSpeed = forkliftDrivingSpeed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WareHouse.pickTruckDrivingSpeed
     *
     * @return the value of WareHouse.pickTruckDrivingSpeed
     *
     * @mbg.generated
     */
    public Double getPickTruckDrivingSpeed() {
        return pickTruckDrivingSpeed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WareHouse.pickTruckDrivingSpeed
     *
     * @param pickTruckDrivingSpeed the value for WareHouse.pickTruckDrivingSpeed
     *
     * @mbg.generated
     */
    public void setPickTruckDrivingSpeed(Double pickTruckDrivingSpeed) {
        this.pickTruckDrivingSpeed = pickTruckDrivingSpeed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WareHouse.personPickUpSpeed
     *
     * @return the value of WareHouse.personPickUpSpeed
     *
     * @mbg.generated
     */
    public Double getPersonPickUpSpeed() {
        return personPickUpSpeed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WareHouse.personPickUpSpeed
     *
     * @param personPickUpSpeed the value for WareHouse.personPickUpSpeed
     *
     * @mbg.generated
     */
    public void setPersonPickUpSpeed(Double personPickUpSpeed) {
        this.personPickUpSpeed = personPickUpSpeed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WareHouse.forkliftPickUpSpeed
     *
     * @return the value of WareHouse.forkliftPickUpSpeed
     *
     * @mbg.generated
     */
    public Double getForkliftPickUpSpeed() {
        return forkliftPickUpSpeed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WareHouse.forkliftPickUpSpeed
     *
     * @param forkliftPickUpSpeed the value for WareHouse.forkliftPickUpSpeed
     *
     * @mbg.generated
     */
    public void setForkliftPickUpSpeed(Double forkliftPickUpSpeed) {
        this.forkliftPickUpSpeed = forkliftPickUpSpeed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WareHouse.pickTuckPickUpSpeed
     *
     * @return the value of WareHouse.pickTuckPickUpSpeed
     *
     * @mbg.generated
     */
    public Double getPickTuckPickUpSpeed() {
        return pickTuckPickUpSpeed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WareHouse.pickTuckPickUpSpeed
     *
     * @param pickTuckPickUpSpeed the value for WareHouse.pickTuckPickUpSpeed
     *
     * @mbg.generated
     */
    public void setPickTuckPickUpSpeed(Double pickTuckPickUpSpeed) {
        this.pickTuckPickUpSpeed = pickTuckPickUpSpeed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WareHouse.createBy
     *
     * @return the value of WareHouse.createBy
     *
     * @mbg.generated
     */
    public String getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WareHouse.createBy
     *
     * @param createBy the value for WareHouse.createBy
     *
     * @mbg.generated
     */
    public void setCreateBy(String createBy) {
        this.createBy = createBy == null ? null : createBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WareHouse.createDate
     *
     * @return the value of WareHouse.createDate
     *
     * @mbg.generated
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WareHouse.createDate
     *
     * @param createDate the value for WareHouse.createDate
     *
     * @mbg.generated
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WareHouse.lastModifiedBy
     *
     * @return the value of WareHouse.lastModifiedBy
     *
     * @mbg.generated
     */
    public String getLastModifiedBy() {
        return lastModifiedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WareHouse.lastModifiedBy
     *
     * @param lastModifiedBy the value for WareHouse.lastModifiedBy
     *
     * @mbg.generated
     */
    public void setLastModifiedBy(String lastModifiedBy) {
        this.lastModifiedBy = lastModifiedBy == null ? null : lastModifiedBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WareHouse.lastModifiedDate
     *
     * @return the value of WareHouse.lastModifiedDate
     *
     * @mbg.generated
     */
    public Date getLastModifiedDate() {
        return lastModifiedDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WareHouse.lastModifiedDate
     *
     * @param lastModifiedDate the value for WareHouse.lastModifiedDate
     *
     * @mbg.generated
     */
    public void setLastModifiedDate(Date lastModifiedDate) {
        this.lastModifiedDate = lastModifiedDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WareHouse
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", code=").append(code);
        sb.append(", fullCodeLength=").append(fullCodeLength);
        sb.append(", stallType=").append(stallType);
        sb.append(", personDrivingSpeed=").append(personDrivingSpeed);
        sb.append(", forkliftDrivingSpeed=").append(forkliftDrivingSpeed);
        sb.append(", pickTruckDrivingSpeed=").append(pickTruckDrivingSpeed);
        sb.append(", personPickUpSpeed=").append(personPickUpSpeed);
        sb.append(", forkliftPickUpSpeed=").append(forkliftPickUpSpeed);
        sb.append(", pickTuckPickUpSpeed=").append(pickTuckPickUpSpeed);
        sb.append(", createBy=").append(createBy);
        sb.append(", createDate=").append(createDate);
        sb.append(", lastModifiedBy=").append(lastModifiedBy);
        sb.append(", lastModifiedDate=").append(lastModifiedDate);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}