package com.dhl.tools.domain;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class WareHouseConfigExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table WareHouseConfig
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table WareHouseConfig
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table WareHouseConfig
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WareHouseConfig
     *
     * @mbg.generated
     */
    public WareHouseConfigExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WareHouseConfig
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WareHouseConfig
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WareHouseConfig
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WareHouseConfig
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WareHouseConfig
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WareHouseConfig
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WareHouseConfig
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WareHouseConfig
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WareHouseConfig
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WareHouseConfig
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table WareHouseConfig
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andWareHouseIdIsNull() {
            addCriterion("wareHouseId is null");
            return (Criteria) this;
        }

        public Criteria andWareHouseIdIsNotNull() {
            addCriterion("wareHouseId is not null");
            return (Criteria) this;
        }

        public Criteria andWareHouseIdEqualTo(Integer value) {
            addCriterion("wareHouseId =", value, "wareHouseId");
            return (Criteria) this;
        }

        public Criteria andWareHouseIdNotEqualTo(Integer value) {
            addCriterion("wareHouseId <>", value, "wareHouseId");
            return (Criteria) this;
        }

        public Criteria andWareHouseIdGreaterThan(Integer value) {
            addCriterion("wareHouseId >", value, "wareHouseId");
            return (Criteria) this;
        }

        public Criteria andWareHouseIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("wareHouseId >=", value, "wareHouseId");
            return (Criteria) this;
        }

        public Criteria andWareHouseIdLessThan(Integer value) {
            addCriterion("wareHouseId <", value, "wareHouseId");
            return (Criteria) this;
        }

        public Criteria andWareHouseIdLessThanOrEqualTo(Integer value) {
            addCriterion("wareHouseId <=", value, "wareHouseId");
            return (Criteria) this;
        }

        public Criteria andWareHouseIdIn(List<Integer> values) {
            addCriterion("wareHouseId in", values, "wareHouseId");
            return (Criteria) this;
        }

        public Criteria andWareHouseIdNotIn(List<Integer> values) {
            addCriterion("wareHouseId not in", values, "wareHouseId");
            return (Criteria) this;
        }

        public Criteria andWareHouseIdBetween(Integer value1, Integer value2) {
            addCriterion("wareHouseId between", value1, value2, "wareHouseId");
            return (Criteria) this;
        }

        public Criteria andWareHouseIdNotBetween(Integer value1, Integer value2) {
            addCriterion("wareHouseId not between", value1, value2, "wareHouseId");
            return (Criteria) this;
        }

        public Criteria andWareHouseTypeIdIsNull() {
            addCriterion("wareHouseTypeId is null");
            return (Criteria) this;
        }

        public Criteria andWareHouseTypeIdIsNotNull() {
            addCriterion("wareHouseTypeId is not null");
            return (Criteria) this;
        }

        public Criteria andWareHouseTypeIdEqualTo(Integer value) {
            addCriterion("wareHouseTypeId =", value, "wareHouseTypeId");
            return (Criteria) this;
        }

        public Criteria andWareHouseTypeIdNotEqualTo(Integer value) {
            addCriterion("wareHouseTypeId <>", value, "wareHouseTypeId");
            return (Criteria) this;
        }

        public Criteria andWareHouseTypeIdGreaterThan(Integer value) {
            addCriterion("wareHouseTypeId >", value, "wareHouseTypeId");
            return (Criteria) this;
        }

        public Criteria andWareHouseTypeIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("wareHouseTypeId >=", value, "wareHouseTypeId");
            return (Criteria) this;
        }

        public Criteria andWareHouseTypeIdLessThan(Integer value) {
            addCriterion("wareHouseTypeId <", value, "wareHouseTypeId");
            return (Criteria) this;
        }

        public Criteria andWareHouseTypeIdLessThanOrEqualTo(Integer value) {
            addCriterion("wareHouseTypeId <=", value, "wareHouseTypeId");
            return (Criteria) this;
        }

        public Criteria andWareHouseTypeIdIn(List<Integer> values) {
            addCriterion("wareHouseTypeId in", values, "wareHouseTypeId");
            return (Criteria) this;
        }

        public Criteria andWareHouseTypeIdNotIn(List<Integer> values) {
            addCriterion("wareHouseTypeId not in", values, "wareHouseTypeId");
            return (Criteria) this;
        }

        public Criteria andWareHouseTypeIdBetween(Integer value1, Integer value2) {
            addCriterion("wareHouseTypeId between", value1, value2, "wareHouseTypeId");
            return (Criteria) this;
        }

        public Criteria andWareHouseTypeIdNotBetween(Integer value1, Integer value2) {
            addCriterion("wareHouseTypeId not between", value1, value2, "wareHouseTypeId");
            return (Criteria) this;
        }

        public Criteria andWareHouseTypeAliasIsNull() {
            addCriterion("wareHouseTypeAlias is null");
            return (Criteria) this;
        }

        public Criteria andWareHouseTypeAliasIsNotNull() {
            addCriterion("wareHouseTypeAlias is not null");
            return (Criteria) this;
        }

        public Criteria andWareHouseTypeAliasEqualTo(String value) {
            addCriterion("wareHouseTypeAlias =", value, "wareHouseTypeAlias");
            return (Criteria) this;
        }

        public Criteria andWareHouseTypeAliasNotEqualTo(String value) {
            addCriterion("wareHouseTypeAlias <>", value, "wareHouseTypeAlias");
            return (Criteria) this;
        }

        public Criteria andWareHouseTypeAliasGreaterThan(String value) {
            addCriterion("wareHouseTypeAlias >", value, "wareHouseTypeAlias");
            return (Criteria) this;
        }

        public Criteria andWareHouseTypeAliasGreaterThanOrEqualTo(String value) {
            addCriterion("wareHouseTypeAlias >=", value, "wareHouseTypeAlias");
            return (Criteria) this;
        }

        public Criteria andWareHouseTypeAliasLessThan(String value) {
            addCriterion("wareHouseTypeAlias <", value, "wareHouseTypeAlias");
            return (Criteria) this;
        }

        public Criteria andWareHouseTypeAliasLessThanOrEqualTo(String value) {
            addCriterion("wareHouseTypeAlias <=", value, "wareHouseTypeAlias");
            return (Criteria) this;
        }

        public Criteria andWareHouseTypeAliasLike(String value) {
            addCriterion("wareHouseTypeAlias like", value, "wareHouseTypeAlias");
            return (Criteria) this;
        }

        public Criteria andWareHouseTypeAliasNotLike(String value) {
            addCriterion("wareHouseTypeAlias not like", value, "wareHouseTypeAlias");
            return (Criteria) this;
        }

        public Criteria andWareHouseTypeAliasIn(List<String> values) {
            addCriterion("wareHouseTypeAlias in", values, "wareHouseTypeAlias");
            return (Criteria) this;
        }

        public Criteria andWareHouseTypeAliasNotIn(List<String> values) {
            addCriterion("wareHouseTypeAlias not in", values, "wareHouseTypeAlias");
            return (Criteria) this;
        }

        public Criteria andWareHouseTypeAliasBetween(String value1, String value2) {
            addCriterion("wareHouseTypeAlias between", value1, value2, "wareHouseTypeAlias");
            return (Criteria) this;
        }

        public Criteria andWareHouseTypeAliasNotBetween(String value1, String value2) {
            addCriterion("wareHouseTypeAlias not between", value1, value2, "wareHouseTypeAlias");
            return (Criteria) this;
        }

        public Criteria andLengthIsNull() {
            addCriterion("length is null");
            return (Criteria) this;
        }

        public Criteria andLengthIsNotNull() {
            addCriterion("length is not null");
            return (Criteria) this;
        }

        public Criteria andLengthEqualTo(Integer value) {
            addCriterion("length =", value, "length");
            return (Criteria) this;
        }

        public Criteria andLengthNotEqualTo(Integer value) {
            addCriterion("length <>", value, "length");
            return (Criteria) this;
        }

        public Criteria andLengthGreaterThan(Integer value) {
            addCriterion("length >", value, "length");
            return (Criteria) this;
        }

        public Criteria andLengthGreaterThanOrEqualTo(Integer value) {
            addCriterion("length >=", value, "length");
            return (Criteria) this;
        }

        public Criteria andLengthLessThan(Integer value) {
            addCriterion("length <", value, "length");
            return (Criteria) this;
        }

        public Criteria andLengthLessThanOrEqualTo(Integer value) {
            addCriterion("length <=", value, "length");
            return (Criteria) this;
        }

        public Criteria andLengthIn(List<Integer> values) {
            addCriterion("length in", values, "length");
            return (Criteria) this;
        }

        public Criteria andLengthNotIn(List<Integer> values) {
            addCriterion("length not in", values, "length");
            return (Criteria) this;
        }

        public Criteria andLengthBetween(Integer value1, Integer value2) {
            addCriterion("length between", value1, value2, "length");
            return (Criteria) this;
        }

        public Criteria andLengthNotBetween(Integer value1, Integer value2) {
            addCriterion("length not between", value1, value2, "length");
            return (Criteria) this;
        }

        public Criteria andWidthIsNull() {
            addCriterion("width is null");
            return (Criteria) this;
        }

        public Criteria andWidthIsNotNull() {
            addCriterion("width is not null");
            return (Criteria) this;
        }

        public Criteria andWidthEqualTo(Integer value) {
            addCriterion("width =", value, "width");
            return (Criteria) this;
        }

        public Criteria andWidthNotEqualTo(Integer value) {
            addCriterion("width <>", value, "width");
            return (Criteria) this;
        }

        public Criteria andWidthGreaterThan(Integer value) {
            addCriterion("width >", value, "width");
            return (Criteria) this;
        }

        public Criteria andWidthGreaterThanOrEqualTo(Integer value) {
            addCriterion("width >=", value, "width");
            return (Criteria) this;
        }

        public Criteria andWidthLessThan(Integer value) {
            addCriterion("width <", value, "width");
            return (Criteria) this;
        }

        public Criteria andWidthLessThanOrEqualTo(Integer value) {
            addCriterion("width <=", value, "width");
            return (Criteria) this;
        }

        public Criteria andWidthIn(List<Integer> values) {
            addCriterion("width in", values, "width");
            return (Criteria) this;
        }

        public Criteria andWidthNotIn(List<Integer> values) {
            addCriterion("width not in", values, "width");
            return (Criteria) this;
        }

        public Criteria andWidthBetween(Integer value1, Integer value2) {
            addCriterion("width between", value1, value2, "width");
            return (Criteria) this;
        }

        public Criteria andWidthNotBetween(Integer value1, Integer value2) {
            addCriterion("width not between", value1, value2, "width");
            return (Criteria) this;
        }

        public Criteria andPrimaryPriorityIsNull() {
            addCriterion("primaryPriority is null");
            return (Criteria) this;
        }

        public Criteria andPrimaryPriorityIsNotNull() {
            addCriterion("primaryPriority is not null");
            return (Criteria) this;
        }

        public Criteria andPrimaryPriorityEqualTo(Integer value) {
            addCriterion("primaryPriority =", value, "primaryPriority");
            return (Criteria) this;
        }

        public Criteria andPrimaryPriorityNotEqualTo(Integer value) {
            addCriterion("primaryPriority <>", value, "primaryPriority");
            return (Criteria) this;
        }

        public Criteria andPrimaryPriorityGreaterThan(Integer value) {
            addCriterion("primaryPriority >", value, "primaryPriority");
            return (Criteria) this;
        }

        public Criteria andPrimaryPriorityGreaterThanOrEqualTo(Integer value) {
            addCriterion("primaryPriority >=", value, "primaryPriority");
            return (Criteria) this;
        }

        public Criteria andPrimaryPriorityLessThan(Integer value) {
            addCriterion("primaryPriority <", value, "primaryPriority");
            return (Criteria) this;
        }

        public Criteria andPrimaryPriorityLessThanOrEqualTo(Integer value) {
            addCriterion("primaryPriority <=", value, "primaryPriority");
            return (Criteria) this;
        }

        public Criteria andPrimaryPriorityIn(List<Integer> values) {
            addCriterion("primaryPriority in", values, "primaryPriority");
            return (Criteria) this;
        }

        public Criteria andPrimaryPriorityNotIn(List<Integer> values) {
            addCriterion("primaryPriority not in", values, "primaryPriority");
            return (Criteria) this;
        }

        public Criteria andPrimaryPriorityBetween(Integer value1, Integer value2) {
            addCriterion("primaryPriority between", value1, value2, "primaryPriority");
            return (Criteria) this;
        }

        public Criteria andPrimaryPriorityNotBetween(Integer value1, Integer value2) {
            addCriterion("primaryPriority not between", value1, value2, "primaryPriority");
            return (Criteria) this;
        }

        public Criteria andStandbyPriorityIsNull() {
            addCriterion("standbyPriority is null");
            return (Criteria) this;
        }

        public Criteria andStandbyPriorityIsNotNull() {
            addCriterion("standbyPriority is not null");
            return (Criteria) this;
        }

        public Criteria andStandbyPriorityEqualTo(Integer value) {
            addCriterion("standbyPriority =", value, "standbyPriority");
            return (Criteria) this;
        }

        public Criteria andStandbyPriorityNotEqualTo(Integer value) {
            addCriterion("standbyPriority <>", value, "standbyPriority");
            return (Criteria) this;
        }

        public Criteria andStandbyPriorityGreaterThan(Integer value) {
            addCriterion("standbyPriority >", value, "standbyPriority");
            return (Criteria) this;
        }

        public Criteria andStandbyPriorityGreaterThanOrEqualTo(Integer value) {
            addCriterion("standbyPriority >=", value, "standbyPriority");
            return (Criteria) this;
        }

        public Criteria andStandbyPriorityLessThan(Integer value) {
            addCriterion("standbyPriority <", value, "standbyPriority");
            return (Criteria) this;
        }

        public Criteria andStandbyPriorityLessThanOrEqualTo(Integer value) {
            addCriterion("standbyPriority <=", value, "standbyPriority");
            return (Criteria) this;
        }

        public Criteria andStandbyPriorityIn(List<Integer> values) {
            addCriterion("standbyPriority in", values, "standbyPriority");
            return (Criteria) this;
        }

        public Criteria andStandbyPriorityNotIn(List<Integer> values) {
            addCriterion("standbyPriority not in", values, "standbyPriority");
            return (Criteria) this;
        }

        public Criteria andStandbyPriorityBetween(Integer value1, Integer value2) {
            addCriterion("standbyPriority between", value1, value2, "standbyPriority");
            return (Criteria) this;
        }

        public Criteria andStandbyPriorityNotBetween(Integer value1, Integer value2) {
            addCriterion("standbyPriority not between", value1, value2, "standbyPriority");
            return (Criteria) this;
        }

        public Criteria andModeIsNull() {
            addCriterion("mode is null");
            return (Criteria) this;
        }

        public Criteria andModeIsNotNull() {
            addCriterion("mode is not null");
            return (Criteria) this;
        }

        public Criteria andModeEqualTo(Integer value) {
            addCriterion("mode =", value, "mode");
            return (Criteria) this;
        }

        public Criteria andModeNotEqualTo(Integer value) {
            addCriterion("mode <>", value, "mode");
            return (Criteria) this;
        }

        public Criteria andModeGreaterThan(Integer value) {
            addCriterion("mode >", value, "mode");
            return (Criteria) this;
        }

        public Criteria andModeGreaterThanOrEqualTo(Integer value) {
            addCriterion("mode >=", value, "mode");
            return (Criteria) this;
        }

        public Criteria andModeLessThan(Integer value) {
            addCriterion("mode <", value, "mode");
            return (Criteria) this;
        }

        public Criteria andModeLessThanOrEqualTo(Integer value) {
            addCriterion("mode <=", value, "mode");
            return (Criteria) this;
        }

        public Criteria andModeIn(List<Integer> values) {
            addCriterion("mode in", values, "mode");
            return (Criteria) this;
        }

        public Criteria andModeNotIn(List<Integer> values) {
            addCriterion("mode not in", values, "mode");
            return (Criteria) this;
        }

        public Criteria andModeBetween(Integer value1, Integer value2) {
            addCriterion("mode between", value1, value2, "mode");
            return (Criteria) this;
        }

        public Criteria andModeNotBetween(Integer value1, Integer value2) {
            addCriterion("mode not between", value1, value2, "mode");
            return (Criteria) this;
        }

        public Criteria andPickToolIsNull() {
            addCriterion("pickTool is null");
            return (Criteria) this;
        }

        public Criteria andPickToolIsNotNull() {
            addCriterion("pickTool is not null");
            return (Criteria) this;
        }

        public Criteria andPickToolEqualTo(Integer value) {
            addCriterion("pickTool =", value, "pickTool");
            return (Criteria) this;
        }

        public Criteria andPickToolNotEqualTo(Integer value) {
            addCriterion("pickTool <>", value, "pickTool");
            return (Criteria) this;
        }

        public Criteria andPickToolGreaterThan(Integer value) {
            addCriterion("pickTool >", value, "pickTool");
            return (Criteria) this;
        }

        public Criteria andPickToolGreaterThanOrEqualTo(Integer value) {
            addCriterion("pickTool >=", value, "pickTool");
            return (Criteria) this;
        }

        public Criteria andPickToolLessThan(Integer value) {
            addCriterion("pickTool <", value, "pickTool");
            return (Criteria) this;
        }

        public Criteria andPickToolLessThanOrEqualTo(Integer value) {
            addCriterion("pickTool <=", value, "pickTool");
            return (Criteria) this;
        }

        public Criteria andPickToolIn(List<Integer> values) {
            addCriterion("pickTool in", values, "pickTool");
            return (Criteria) this;
        }

        public Criteria andPickToolNotIn(List<Integer> values) {
            addCriterion("pickTool not in", values, "pickTool");
            return (Criteria) this;
        }

        public Criteria andPickToolBetween(Integer value1, Integer value2) {
            addCriterion("pickTool between", value1, value2, "pickTool");
            return (Criteria) this;
        }

        public Criteria andPickToolNotBetween(Integer value1, Integer value2) {
            addCriterion("pickTool not between", value1, value2, "pickTool");
            return (Criteria) this;
        }

        public Criteria andHandsUpDrivingSpeedIsNull() {
            addCriterion("handsUpDrivingSpeed is null");
            return (Criteria) this;
        }

        public Criteria andHandsUpDrivingSpeedIsNotNull() {
            addCriterion("handsUpDrivingSpeed is not null");
            return (Criteria) this;
        }

        public Criteria andHandsUpDrivingSpeedEqualTo(Double value) {
            addCriterion("handsUpDrivingSpeed =", value, "handsUpDrivingSpeed");
            return (Criteria) this;
        }

        public Criteria andHandsUpDrivingSpeedNotEqualTo(Double value) {
            addCriterion("handsUpDrivingSpeed <>", value, "handsUpDrivingSpeed");
            return (Criteria) this;
        }

        public Criteria andHandsUpDrivingSpeedGreaterThan(Double value) {
            addCriterion("handsUpDrivingSpeed >", value, "handsUpDrivingSpeed");
            return (Criteria) this;
        }

        public Criteria andHandsUpDrivingSpeedGreaterThanOrEqualTo(Double value) {
            addCriterion("handsUpDrivingSpeed >=", value, "handsUpDrivingSpeed");
            return (Criteria) this;
        }

        public Criteria andHandsUpDrivingSpeedLessThan(Double value) {
            addCriterion("handsUpDrivingSpeed <", value, "handsUpDrivingSpeed");
            return (Criteria) this;
        }

        public Criteria andHandsUpDrivingSpeedLessThanOrEqualTo(Double value) {
            addCriterion("handsUpDrivingSpeed <=", value, "handsUpDrivingSpeed");
            return (Criteria) this;
        }

        public Criteria andHandsUpDrivingSpeedIn(List<Double> values) {
            addCriterion("handsUpDrivingSpeed in", values, "handsUpDrivingSpeed");
            return (Criteria) this;
        }

        public Criteria andHandsUpDrivingSpeedNotIn(List<Double> values) {
            addCriterion("handsUpDrivingSpeed not in", values, "handsUpDrivingSpeed");
            return (Criteria) this;
        }

        public Criteria andHandsUpDrivingSpeedBetween(Double value1, Double value2) {
            addCriterion("handsUpDrivingSpeed between", value1, value2, "handsUpDrivingSpeed");
            return (Criteria) this;
        }

        public Criteria andHandsUpDrivingSpeedNotBetween(Double value1, Double value2) {
            addCriterion("handsUpDrivingSpeed not between", value1, value2, "handsUpDrivingSpeed");
            return (Criteria) this;
        }

        public Criteria andRankIsNull() {
            addCriterion("rank is null");
            return (Criteria) this;
        }

        public Criteria andRankIsNotNull() {
            addCriterion("rank is not null");
            return (Criteria) this;
        }

        public Criteria andRankEqualTo(Integer value) {
            addCriterion("rank =", value, "rank");
            return (Criteria) this;
        }

        public Criteria andRankNotEqualTo(Integer value) {
            addCriterion("rank <>", value, "rank");
            return (Criteria) this;
        }

        public Criteria andRankGreaterThan(Integer value) {
            addCriterion("rank >", value, "rank");
            return (Criteria) this;
        }

        public Criteria andRankGreaterThanOrEqualTo(Integer value) {
            addCriterion("rank >=", value, "rank");
            return (Criteria) this;
        }

        public Criteria andRankLessThan(Integer value) {
            addCriterion("rank <", value, "rank");
            return (Criteria) this;
        }

        public Criteria andRankLessThanOrEqualTo(Integer value) {
            addCriterion("rank <=", value, "rank");
            return (Criteria) this;
        }

        public Criteria andRankIn(List<Integer> values) {
            addCriterion("rank in", values, "rank");
            return (Criteria) this;
        }

        public Criteria andRankNotIn(List<Integer> values) {
            addCriterion("rank not in", values, "rank");
            return (Criteria) this;
        }

        public Criteria andRankBetween(Integer value1, Integer value2) {
            addCriterion("rank between", value1, value2, "rank");
            return (Criteria) this;
        }

        public Criteria andRankNotBetween(Integer value1, Integer value2) {
            addCriterion("rank not between", value1, value2, "rank");
            return (Criteria) this;
        }

        public Criteria andCreateByIsNull() {
            addCriterion("createBy is null");
            return (Criteria) this;
        }

        public Criteria andCreateByIsNotNull() {
            addCriterion("createBy is not null");
            return (Criteria) this;
        }

        public Criteria andCreateByEqualTo(String value) {
            addCriterion("createBy =", value, "createBy");
            return (Criteria) this;
        }

        public Criteria andCreateByNotEqualTo(String value) {
            addCriterion("createBy <>", value, "createBy");
            return (Criteria) this;
        }

        public Criteria andCreateByGreaterThan(String value) {
            addCriterion("createBy >", value, "createBy");
            return (Criteria) this;
        }

        public Criteria andCreateByGreaterThanOrEqualTo(String value) {
            addCriterion("createBy >=", value, "createBy");
            return (Criteria) this;
        }

        public Criteria andCreateByLessThan(String value) {
            addCriterion("createBy <", value, "createBy");
            return (Criteria) this;
        }

        public Criteria andCreateByLessThanOrEqualTo(String value) {
            addCriterion("createBy <=", value, "createBy");
            return (Criteria) this;
        }

        public Criteria andCreateByLike(String value) {
            addCriterion("createBy like", value, "createBy");
            return (Criteria) this;
        }

        public Criteria andCreateByNotLike(String value) {
            addCriterion("createBy not like", value, "createBy");
            return (Criteria) this;
        }

        public Criteria andCreateByIn(List<String> values) {
            addCriterion("createBy in", values, "createBy");
            return (Criteria) this;
        }

        public Criteria andCreateByNotIn(List<String> values) {
            addCriterion("createBy not in", values, "createBy");
            return (Criteria) this;
        }

        public Criteria andCreateByBetween(String value1, String value2) {
            addCriterion("createBy between", value1, value2, "createBy");
            return (Criteria) this;
        }

        public Criteria andCreateByNotBetween(String value1, String value2) {
            addCriterion("createBy not between", value1, value2, "createBy");
            return (Criteria) this;
        }

        public Criteria andCreateDateIsNull() {
            addCriterion("createDate is null");
            return (Criteria) this;
        }

        public Criteria andCreateDateIsNotNull() {
            addCriterion("createDate is not null");
            return (Criteria) this;
        }

        public Criteria andCreateDateEqualTo(Date value) {
            addCriterion("createDate =", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateNotEqualTo(Date value) {
            addCriterion("createDate <>", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateGreaterThan(Date value) {
            addCriterion("createDate >", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateGreaterThanOrEqualTo(Date value) {
            addCriterion("createDate >=", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateLessThan(Date value) {
            addCriterion("createDate <", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateLessThanOrEqualTo(Date value) {
            addCriterion("createDate <=", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateIn(List<Date> values) {
            addCriterion("createDate in", values, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateNotIn(List<Date> values) {
            addCriterion("createDate not in", values, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateBetween(Date value1, Date value2) {
            addCriterion("createDate between", value1, value2, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateNotBetween(Date value1, Date value2) {
            addCriterion("createDate not between", value1, value2, "createDate");
            return (Criteria) this;
        }

        public Criteria andLastModifiedByIsNull() {
            addCriterion("lastModifiedBy is null");
            return (Criteria) this;
        }

        public Criteria andLastModifiedByIsNotNull() {
            addCriterion("lastModifiedBy is not null");
            return (Criteria) this;
        }

        public Criteria andLastModifiedByEqualTo(String value) {
            addCriterion("lastModifiedBy =", value, "lastModifiedBy");
            return (Criteria) this;
        }

        public Criteria andLastModifiedByNotEqualTo(String value) {
            addCriterion("lastModifiedBy <>", value, "lastModifiedBy");
            return (Criteria) this;
        }

        public Criteria andLastModifiedByGreaterThan(String value) {
            addCriterion("lastModifiedBy >", value, "lastModifiedBy");
            return (Criteria) this;
        }

        public Criteria andLastModifiedByGreaterThanOrEqualTo(String value) {
            addCriterion("lastModifiedBy >=", value, "lastModifiedBy");
            return (Criteria) this;
        }

        public Criteria andLastModifiedByLessThan(String value) {
            addCriterion("lastModifiedBy <", value, "lastModifiedBy");
            return (Criteria) this;
        }

        public Criteria andLastModifiedByLessThanOrEqualTo(String value) {
            addCriterion("lastModifiedBy <=", value, "lastModifiedBy");
            return (Criteria) this;
        }

        public Criteria andLastModifiedByLike(String value) {
            addCriterion("lastModifiedBy like", value, "lastModifiedBy");
            return (Criteria) this;
        }

        public Criteria andLastModifiedByNotLike(String value) {
            addCriterion("lastModifiedBy not like", value, "lastModifiedBy");
            return (Criteria) this;
        }

        public Criteria andLastModifiedByIn(List<String> values) {
            addCriterion("lastModifiedBy in", values, "lastModifiedBy");
            return (Criteria) this;
        }

        public Criteria andLastModifiedByNotIn(List<String> values) {
            addCriterion("lastModifiedBy not in", values, "lastModifiedBy");
            return (Criteria) this;
        }

        public Criteria andLastModifiedByBetween(String value1, String value2) {
            addCriterion("lastModifiedBy between", value1, value2, "lastModifiedBy");
            return (Criteria) this;
        }

        public Criteria andLastModifiedByNotBetween(String value1, String value2) {
            addCriterion("lastModifiedBy not between", value1, value2, "lastModifiedBy");
            return (Criteria) this;
        }

        public Criteria andLastModifiedDateIsNull() {
            addCriterion("lastModifiedDate is null");
            return (Criteria) this;
        }

        public Criteria andLastModifiedDateIsNotNull() {
            addCriterion("lastModifiedDate is not null");
            return (Criteria) this;
        }

        public Criteria andLastModifiedDateEqualTo(Date value) {
            addCriterion("lastModifiedDate =", value, "lastModifiedDate");
            return (Criteria) this;
        }

        public Criteria andLastModifiedDateNotEqualTo(Date value) {
            addCriterion("lastModifiedDate <>", value, "lastModifiedDate");
            return (Criteria) this;
        }

        public Criteria andLastModifiedDateGreaterThan(Date value) {
            addCriterion("lastModifiedDate >", value, "lastModifiedDate");
            return (Criteria) this;
        }

        public Criteria andLastModifiedDateGreaterThanOrEqualTo(Date value) {
            addCriterion("lastModifiedDate >=", value, "lastModifiedDate");
            return (Criteria) this;
        }

        public Criteria andLastModifiedDateLessThan(Date value) {
            addCriterion("lastModifiedDate <", value, "lastModifiedDate");
            return (Criteria) this;
        }

        public Criteria andLastModifiedDateLessThanOrEqualTo(Date value) {
            addCriterion("lastModifiedDate <=", value, "lastModifiedDate");
            return (Criteria) this;
        }

        public Criteria andLastModifiedDateIn(List<Date> values) {
            addCriterion("lastModifiedDate in", values, "lastModifiedDate");
            return (Criteria) this;
        }

        public Criteria andLastModifiedDateNotIn(List<Date> values) {
            addCriterion("lastModifiedDate not in", values, "lastModifiedDate");
            return (Criteria) this;
        }

        public Criteria andLastModifiedDateBetween(Date value1, Date value2) {
            addCriterion("lastModifiedDate between", value1, value2, "lastModifiedDate");
            return (Criteria) this;
        }

        public Criteria andLastModifiedDateNotBetween(Date value1, Date value2) {
            addCriterion("lastModifiedDate not between", value1, value2, "lastModifiedDate");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table WareHouseConfig
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table WareHouseConfig
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }
    }
}